<h1>Gebruikerslijst</h1>

<table class="table">
  <thead>
    <tr>
      <th>#</th>
      <th>Login</th>
      <th>Wijzig / verwijder</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach ($users as $user): ?>
    <tr>
      <td><?= $user->getId() ?>
      <td><?= $user->getLogin() ?>
      <td>
          <a class="btn btn-primary btn-xs" href="<?= $this->url('settings/user/edit', ['id' => $user->getId()]) ?>">
             Wijzig / Verwijder
          </a>
      </td>
    </tr>
    <?php endforeach ?>
  </tbody>
</table>

<a href="<?= $this->url('settings/user/default', ['action' => 'create']); ?>" class="btn btn-success">
     <span class="glyphicon glyphicon-plus"></span> Maak nieuwe gebruiker</a>
