<h1><?= $this->translate('Users') ?></h1>

<?php if ($usesldap): ?>
    <div class="alert alert-danger" role="alert">
        <?=
            sprintf(
                $this->translate(
                    '<strong>Warning:</strong> The database currently requires the usage of GEWIS m-accounts to log in. Any accounts created here cannot be used to log in. Learn more about m-accounts %shere%s.'
                ),
                '<a target="_blank" href="https://support.gewis.nl/kb/faq.php?id=36">',
                '</a>',
            )
        ?>
    </div>
<?php endif; ?>

<table class="table">
    <thead>
        <tr>
            <th>#</th>
            <th><?= $this->translate('Username') ?>></th>
            <th><?= $this->translate('Edit / Delete') ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($users as $user): ?>
            <tr>
                <td><?= $user->getId() ?>
                <td><?= $user->getLogin() ?>
                <td>
                    <a class="btn btn-primary btn-xs" href="<?= $this->url(
                        'settings/user/edit',
                        ['id' => $user->getId()],
                    ) ?>">
                        <?= $this->translate('Edit / Delete') ?>
                    </a>
                </td>
            </tr>
        <?php endforeach ?>
    </tbody>
</table>

<a href="<?= $this->url('settings/user/default', ['action' => 'create']); ?>" class="btn btn-success">
    <span class="glyphicon glyphicon-plus"></span> <?= $this->translate('Add new user') ?>
</a>
