<h1>Gebruikerslijst</h1>

<?php if ($usesldap): ?>
<div class="alert alert-danger" role="alert">
  <b>Warning:</b> This system currently uses GEWIS m-accounts. This means that any accounts you create here can not be used to login.
  Learn more about m-accounts <a target="_blank" href="https://support.gewis.nl/kb/faq.php?id=36">here</a>.
</div>
<?php endif; ?>

<table class="table">
  <thead>
    <tr>
      <th>#</th>
      <th>Login</th>
      <th>Wijzig / verwijder</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach ($users as $user): ?>
    <tr>
      <td><?= $user->getId() ?>
      <td><?= $user->getLogin() ?>
      <td>
        <a class="btn btn-primary btn-xs" href="<?= $this->url('settings/user/edit', ['id' => $user->getId()]) ?>">
          Wijzig / Verwijder
        </a>
      </td>
    </tr>
    <?php endforeach ?>
  </tbody>
</table>

<a href="<?= $this->url('settings/user/default', ['action' => 'create']); ?>" class="btn btn-success">
     <span class="glyphicon glyphicon-plus"></span> Maak nieuwe gebruiker</a>
