<?php

declare(strict_types=1);

use Application\View\HelperTrait;
use Database\Form\MailingList as MailingListForm;
use Database\Model\MailingList as MailingListModel;
use Laminas\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer|HelperTrait $this
 * @var string $action
 * @var MailingListForm $form
 * @var MailingListModel $list
 */

if ('add' === $action) {
    $title = $this->translate('Add New Mailing List');
    $url = $this->url('settings/lists/add');
} else {
    $title = $this->translate('Edit Mailing List');
    $url = $this->url('settings/lists/edit', ['name' => $list->getName()]);
}
?>
<div class="row">
    <div class="col-md-12">
        <h2>
            <?= $title ?>
        </h2>
        <?php
        $form->prepare();

        $form->setAttribute('action', $url);
        $form->setAttribute('method', 'post');

        $form->setAttribute('role', 'form');
        $form->setAttribute('class', 'form-horizontal');
        ?>
        <?= $this->form()->openTag($form) ?>

        <div class="form-group">
            <?php
            $element = $form->get('name');
            $element->setAttribute('class', 'form-control');
            $element->setAttribute('placeholder', $element->getLabel());
            $element->setLabelAttributes(['class' => 'col-sm-2 control-label']);

            if ('add' !== $action) {
                $element->setAttribute('readonly', true);
            }
            ?>
            <?= $this->formLabel($element) ?>
            <div class="col-sm-10">
                <?= $this->formInput($element) ?>
                <?= $this->formElementErrors($element) ?>
            </div>
        </div>

        <div class="form-group">
            <?php
            $element = $form->get('nl_description');
            $element->setAttribute('class', 'form-control');
            $element->setAttribute('placeholder', $element->getLabel());
            $element->setLabelAttributes(['class' => 'col-sm-2 control-label']);
            ?>
            <?= $this->formLabel($element) ?>
            <div class="col-sm-10">
                <?= $this->formTextarea($element) ?>
                <?= $this->formElementErrors($element) ?>
            </div>
        </div>

        <div class="form-group">
            <?php
            $element = $form->get('en_description');
            $element->setAttribute('class', 'form-control');
            $element->setAttribute('placeholder', $element->getLabel());
            $element->setLabelAttributes(['class' => 'col-sm-2 control-label']);
            ?>
            <?= $this->formLabel($element) ?>
            <div class="col-sm-10">
                <?= $this->formTextarea($element) ?>
                <?= $this->formElementErrors($element) ?>
            </div>
        </div>

        <div class="form-group">
            <?php
            $element = $form->get('onForm');
            $element->setAttribute('placeholder', $element->getLabel());
            ?>
            <div class="col-sm-offset-2 col-sm-10">
                <div class="checkbox">
                    <label>
                        <?= $this->formCheckbox($element) ?>
                        <?= $element->getLabel() ?>
                    </label>
                    <?= $this->formElementErrors($element) ?>
                </div>
            </div>
        </div>

        <div class="form-group">
            <?php
            $element = $form->get('defaultSub');
            $element->setAttribute('placeholder', $element->getLabel());
            ?>
            <div class="col-sm-offset-2 col-sm-10">
                <div class="checkbox">
                    <label>
                        <?= $this->formCheckbox($element) ?>
                        <?= $element->getLabel() ?>
                    </label>
                    <?= $this->formElementErrors($element) ?>
                </div>
            </div>
        </div>

        <div class="form-group">
            <?php
            $element = $form->get('mailmanList');
            $element->setAttribute('placeholder', $element->getLabel());
            ?>
            <div class="col-sm-offset-2 col-sm-10">
                <label><?= $element->getLabel() ?></label>
                <?= $this->formSelect($element) ?>
                <?= $this->formElementErrors($element) ?>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <?php
                $submit = $form->get('submit');
                $submit->setLabel($title);
                $submit->setAttribute('class', 'btn btn-primary');
                ?>
                <?= $this->formButton($submit) ?>
            </div>
        </div>

        <?= $this->form()->closeTag() ?>
    </div>
</div>
