<?php if (!isset($form)): ?>
Mailing list verwijderd.
<?php else:
$form->prepare();

$form->setAttribute('action', $this->url('settings/list-delete', array(
    'name' => $name
)));
$form->setAttribute('method', 'post');
$form->setAttribute('role', 'form');

echo $this->form()->openTag($form);
?>

<p>
Weet je zeker dat de mailing lijst <?= $name ?> verwijderd moet worden?
</p>
<div class="form-group">
<?php
$submit = $form->get('submit_yes');
$submit->setLabel('Ja');
$submit->setAttribute('class', 'btn btn-primary');
?>
<?= $this->formButton($submit) ?>
&nbsp;&nbsp;&nbsp;
<?php
$submit = $form->get('submit_no');
$submit->setLabel('Nee');
$submit->setAttribute('class', 'btn btn-default');
?>
<?= $this->formButton($submit) ?>
</div>

<?= $this->form()->closeTag(); ?>
<?php endif ?>
