<?php

declare(strict_types=1);

use Application\View\HelperTrait;
use Laminas\View\Renderer\PhpRenderer;

/** @var PhpRenderer|HelperTrait $this */

if (!isset($form)): ?>
    <?= $this->translate('Mailing list deleted.') ?>
<?php else: ?>
    <?php
    $form->prepare();

    $form->setAttribute(
        'action',
        $this->url('settings/list-delete', [
            'name' => $name,
        ]),
    );
    $form->setAttribute('method', 'post');
    $form->setAttribute('role', 'form');

    echo $this->form()->openTag($form);
    ?>

    <p>
        <?=
            sprintf(
                $this->translate('Are you sure that you want to delete the %s mailing list?'),
                $this->escapeHtml($name),
            )
        ?>
    </p>
    <div class="form-group">
        <?php
        $submit = $form->get('submit_yes');
        $submit->setLabel($this->translate('Yes'));
        $submit->setAttribute('class', 'btn btn-primary');
        ?>
        <?= $this->formButton($submit) ?>
        &nbsp;&nbsp;&nbsp;
        <?php
        $submit = $form->get('submit_no');
        $submit->setLabel($this->translate('No'));
        $submit->setAttribute('class', 'btn btn-default');
        ?>
        <?= $this->formButton($submit) ?>
    </div>

    <?= $this->form()->closeTag(); ?>
<?php
endif ?>
