<h1>Huidige functies</h1>
<ul>
<?php foreach ($functions as $function): ?>
    <li><?= $function->getName() ?></li>
<?php endforeach; ?>
</ul>
<h2>Maak nieuwe functie</h2>
<?php
$form = $this->form;
$form->prepare();

$form->setAttribute('action', $this->url('settings/default', array('action' => 'function')));
$form->setAttribute('method', 'post');

$form->setAttribute('role', 'form');

echo $this->form()->openTag($form);
?>
<div class="form-group">
<?php
$element = $form->get('name');
$element->setAttribute('class', 'form-control');
$element->setAttribute('placeholder', 'Functienaam');
?>
    <?= $this->formLabel($element) ?>
    <?= $this->formInput($element) ?>
    <?= $this->formElementErrors($element) ?>
</div>

<?php
$submit = $form->get('submit');
$submit->setLabel('Maak functie');
$submit->setAttribute('class', 'btn btn-primary');
?>
<?= $this->formButton($submit) ?>

<?= $this->form()->closeTag(); ?>
