<?php

declare(strict_types=1);

use Application\View\HelperTrait;
use Laminas\View\Renderer\PhpRenderer;

/** @var PhpRenderer|HelperTrait $this */
?>
<h2><?= $this->translate('Current Functions') ?></h2>
<p><?= $this->translate('These organ functions can be selected when installing someone into a committee/fraternity')?></p>
<ul>
    <?php foreach ($currentFunctions as $key => $value): ?>
        <li><?= $this->escapeHtml($value) ?> (<code><?= $this->escapeHtml($key) ?></code>)</li>
    <?php endforeach; ?>
</ul>

<h2><?= $this->translate('Historic Functions') ?></h2>
<p><?= $this->translate('These organ functions were used in the past but can no longer be selected')?></p>
<ul>
    <?php foreach ($legacyFunctions as $key => $value): ?>
        <li><?= $this->escapeHtml($value) ?> (<code><?= $this->escapeHtml($key) ?></code>)</li>
    <?php endforeach; ?>
</ul>

<h2><?= $this->translate('Administrative Functions') ?></h2>
<p><?= $this->translate('These organ functions cannot be selected manually but are used by the database internally')?></p>
<ul>
    <?php foreach ($adminFunctions as $key => $value): ?>
        <li><?= $this->escapeHtml($value) ?> (<code><?= $this->escapeHtml($key) ?></code>)</li>
    <?php endforeach; ?>
</ul>

<em><?= $this->translate('Starting 2024, organ installation functions can only be changed through the code') ?></em>
