<h1><?= $this->translate('Current Functions') ?></h1>
<ul>
    <?php foreach ($functions as $function): ?>
        <li><?= $this->escapeHtml($function->getName()) ?></li>
    <?php endforeach; ?>
</ul>
<h2><?= $this->translate('Add New Function') ?></h2>
<?php
$form = $this->form;
$form->prepare();

$form->setAttribute('action', $this->url('settings/default', ['action' => 'function']));
$form->setAttribute('method', 'post');

$form->setAttribute('role', 'form');

echo $this->form()->openTag($form);
?>
<div class="form-group">
    <?php
    $element = $form->get('name');
    $element->setAttribute('class', 'form-control');
    $element->setAttribute('placeholder', 'Functienaam');
    ?>
    <?= $this->formLabel($element) ?>
    <?= $this->formInput($element) ?>
    <?= $this->formElementErrors($element) ?>
</div>

<?php
$submit = $form->get('submit');
$submit->setLabel($this->translate('Add Function'));
$submit->setAttribute('class', 'btn btn-primary');
?>
<?= $this->formButton($submit) ?>

<?= $this->form()->closeTag(); ?>
