<?php

declare(strict_types=1);

use Application\View\HelperTrait;
use Laminas\View\Renderer\PhpRenderer;

/** @var PhpRenderer|HelperTrait $this */
?>
<h1>Settings</h1>

<ul>
    <li>
        <a href="<?= $this->url('settings/api-principals') ?>">
            <?= $this->translate('API Tokens') ?>
        </a>
    </li>
    <li>
        <a href="<?= $this->url('settings/default', ['action' => 'function']) ?>">
            <?= $this->translate('Functions') ?>
        </a>
    </li>
    <li>
        <a href="<?= $this->url('settings/default', ['action' => 'list']) ?>">
            <?= $this->translate('Mailing Lists') ?>
        </a>
    </li>
    <li>
        <a href="<?= $this->url('settings/user') ?>">
            <?= $this->translate('Users') ?>
        </a>
    </li>
</ul>
