<?php

declare(strict_types=1);

?>
<div class="row">
    <div class="col-md-12">
        <h2><?= $this->translate('Current Mailing Lists') ?></h2>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th><?= $this->translate('Name') ?></th>
                    <th><?= $this->translate('Dutch Description') ?></th>
                    <th><?= $this->translate('English Description') ?></th>
                    <th><?= $this->translate('On Form') ?></th>
                    <th><?= $this->translate('Auto-subscription') ?></th>
                    <th><?= $this->translate('Delete') ?></th>
                </tr>
            </thead>
            <tbody>
            <?php foreach ($lists as $list): ?>
                <tr>
                    <td><?= $this->escapeHtml($list->getName()) ?></td>
                    <td><?= $this->escapeHtml($list->getNlDescription()) ?></td>
                    <td><?= $this->escapeHtml($list->getEnDescription()) ?></td>
                    <td><span class="glyphicon glyphicon-<?= $list->getOnForm() ? 'ok' : 'remove' ?>"></span></td>
                    <td><span class="glyphicon glyphicon-<?= $list->getDefaultSub() ? 'ok' : 'remove' ?>"></span></td>
                    <td>
                        <a href="<?= $this->url('settings/list-delete', [
                            'name' => $list->getName(),
                        ]) ?>" class="btn btn-xs btn-danger">
                            <span class="glyphicon glyphicon-remove"></span> <?= $this->translate('Delete')?>
                        </a>
                    </td>
                </tr>
            <?php endforeach ?>
            </tbody>
        </table>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <h2><?= $this->translate('Add New Mailing List') ?></h2>
        <?php
        $form->prepare();

        $form->setAttribute('action', $this->url('settings/default', ['action' => 'list']));
        $form->setAttribute('method', 'post');

        $form->setAttribute('role', 'form');
        $form->setAttribute('class', 'form-horizontal');
        ?>
        <?= $this->form()->openTag($form) ?>
        <p>
            <?= $this->translate('Please note that if you create a mailing list here, it must also exist in mailman (with the same name!).') ?>
        </p>

        <div class="form-group">
            <?php
            $element = $form->get('name');
            $element->setAttribute('class', 'form-control');
            $element->setAttribute('placeholder', $element->getLabel());
            $element->setLabelAttributes(['class' => 'col-sm-2 control-label']);
            ?>
            <?= $this->formLabel($element) ?>
            <div class="col-sm-10">
                <?= $this->formInput($element) ?>
                <?= $this->formElementErrors($element) ?>
            </div>
        </div>

        <div class="form-group">
            <?php
            $element = $form->get('nl_description');
            $element->setAttribute('class', 'form-control');
            $element->setAttribute('placeholder', $element->getLabel());
            $element->setLabelAttributes(['class' => 'col-sm-2 control-label']);
            ?>
            <?= $this->formLabel($element) ?>
            <div class="col-sm-10">
                <?= $this->formTextarea($element) ?>
                <?= $this->formElementErrors($element) ?>
            </div>
        </div>

        <div class="form-group">
            <?php
            $element = $form->get('en_description');
            $element->setAttribute('class', 'form-control');
            $element->setAttribute('placeholder', $element->getLabel());
            $element->setLabelAttributes(['class' => 'col-sm-2 control-label']);
            ?>
            <?= $this->formLabel($element) ?>
            <div class="col-sm-10">
                <?= $this->formTextarea($element) ?>
                <?= $this->formElementErrors($element) ?>
            </div>
        </div>

        <div class="form-group">
            <?php
            $element = $form->get('onForm');
            $element->setAttribute('placeholder', $element->getLabel());
            ?>
            <div class="col-sm-offset-2 col-sm-10">
                <div class="checkbox">
                    <label>
                        <?= $this->formCheckbox($element) ?>
                        <?= $element->getLabel() ?>
                    </label>
                    <?= $this->formElementErrors($element) ?>
                </div>
            </div>
        </div>

        <div class="form-group">
            <?php
            $element = $form->get('defaultSub');
            $element->setAttribute('placeholder', $element->getLabel());
            ?>
            <div class="col-sm-offset-2 col-sm-10">
                <div class="checkbox">
                    <label>
                        <?= $this->formCheckbox($element) ?>
                        <?= $element->getLabel() ?>
                    </label>
                    <?= $this->formElementErrors($element) ?>
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <?php
                $submit = $form->get('submit');
                $submit->setLabel($submit->getValue());
                $submit->setAttribute('class', 'btn btn-primary');
                ?>
                <?= $this->formButton($submit) ?>
            </div>
        </div>

        <?= $this->form()->closeTag() ?>
    </div>
</div>
