<?php

declare(strict_types=1);

namespace App\DataFixtures\User;

use App\Entity\User\ApiPrincipal;
use App\Entity\User\Enums\ApiPermissions;
use App\Entity\User\User;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;
use Override;
use Symfony\Component\DependencyInjection\Attribute\Autowire;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;

/**
 * Someone to sign in as, and something to call the API with.
 *
 * The credentials are the ones the development stack advertises everywhere else (`DEMO_CREDENTIALS_*`), so a fresh
 * database can be signed into without looking anything up. Nothing here is loaded outside development and test.
 */
class UserFixture extends Fixture
{
    public const string REF_USER_ADMIN = 'user-admin';
    public const string REF_API_PRINCIPAL = 'api-principal';

    public function __construct(
        private readonly UserPasswordHasherInterface $passwordHasher,
        #[Autowire(env: 'DEMO_CREDENTIALS_USERNAME')]
        private readonly string $login,
        #[Autowire(env: 'DEMO_CREDENTIALS_PASSWORD')]
        private readonly string $password,
    ) {
    }

    #[Override]
    public function load(ObjectManager $manager): void
    {
        $user = new User();
        $user->setLogin('' !== $this->login ? $this->login : 'admin');
        $user->setPassword($this->passwordHasher->hashPassword(
            $user,
            '' !== $this->password ? $this->password : 'admin',
        ));
        $manager->persist($user);
        $this->addReference(
            self::REF_USER_ADMIN,
            $user,
        );

        // Every permission, so the API can be exercised in full. The token is generated by the entity itself — there
        // is no setter, deliberately — and only ever shown in full at the moment of creation, so read it from the
        // database if you need to call the API with it.
        $principal = new ApiPrincipal();
        $principal->setDescription('Development principal (seeded)');
        $principal->setPermissions(ApiPermissions::cases());
        $principal->generateToken();
        $manager->persist($principal);
        $this->addReference(
            self::REF_API_PRINCIPAL,
            $principal,
        );

        $manager->flush();
    }
}
