# security.txt is served centrally from gewis.nl.
location = /.well-known/security.txt {
    proxy_ssl_server_name  on;
    proxy_ssl_name         gewis.nl;
    proxy_set_header       Host gewis.nl;
    proxy_pass             https://gewis.nl/.well-known/security.txt;
}
