<script>
    $(document).ready(function () {
        $('#key-grantee').autocomplete({
            minLength: 2, // at least two chars before request
            delay: 0, // no delay before request
            source: function (rq, response) {
                // make an AJAX request
                $.ajax({
                    dataType: 'json',
                    url: '<?= $this->url('member/searchFiltered') ?>?q=' + rq.term,
                    context: document.body
                }).done(function(data) {
                    var ret = [];
                    $.each(data.json, function (idx, member) {
                        // assemble member name and add to list
                        var name = member.fullName + ' (' + member.lidnr + ')';

                        ret.push({
                            label: name,
                            value: name,
                            id: member.lidnr
                        });
                    });

                    // show data
                    response(ret);
                });
            },
            select: function (event, ui) {
                $(event.target).parent().find("input.member-lidnr").val(ui.item.id);
            }
        });
    });
</script>
<?php
$form = $this->form;
$form->prepare();

$form->setAttribute('action', $this->url('meeting/decision/form', array('form' => 'key_grant')));
$form->setAttribute('method', 'post');

$form->setAttribute('role', 'form');

echo $this->form()->openTag($form);
?>
<?php /* first do hidden elements */ ?>
<?php
$fs = $form->get('meeting')
?>
<?= $this->formHidden($fs->get('type')) ?>
<?= $this->formHidden($fs->get('number')) ?>
<?= $this->formHidden($form->get('point')) ?>
<?= $this->formHidden($form->get('decision')) ?>

<?php
$fs = $form->get('grantee');
?>
<div class="form-group">
    <?php
    $el = $fs->get('name');
    $el->setAttribute('class', 'form-control member-autocomplete');
    $el->setAttribute('id', 'key-grantee');
    $el->setAttribute('placeholder', $el->getLabel());
    ?>
    <?= $this->formLabel($fs) ?>
    <?= $this->formInput($el) ?>
    <?php
    // hidden element for actual membership number
    $el = $fs->get('lidnr');
    $el->setAttribute('class', 'member-lidnr');
    ?>
    <?= $this->formHidden($el) ?>
    <?= $this->formElementErrors($el) ?>
</div>

<div class="form-group">
    <?php
    $element = $form->get('until');
    $element->setAttribute('class', 'form-control');
    $element->setAttribute('placeholder', $this->translate('Date of Expiration'));
    ?>
    <?= $this->formLabel($element) ?>
    <?= $this->formInput($element) ?>
    <?= $this->formElementErrors($element) ?>
</div>

<?php
$submit = $form->get('submit');
$submit->setLabel('Submit');
$submit->setAttribute('class', 'btn btn-primary');
?>
<?= $this->formButton($submit) ?>

<?= $this->form()->closeTag(); ?>
