<?php

declare(strict_types=1);

use Application\View\HelperTrait;
use Database\Model\SubDecision\Key\Granting as KeyGrantingModel;
use Laminas\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer|HelperTrait $this
 * @var KeyGrantingModel[] $grants
 */

$arrGrants = array();

foreach ($grants as $key => $grant) {
    $arrGrants[$key] = array(
        'meeting_type' => $grant->getDecision()->getMeeting()->getType()->value,
        'meeting_number' => $grant->getDecision()->getMeeting()->getNumber(),
        'decision_point' => $grant->getDecision()->getPoint(),
        'decision_number' => $grant->getDecision()->getNumber(),
        'subdecision_sequence' => $grant->getSequence(),
        'granting_until' => $grant->getUntil()->format('Y-m-d'),
        'granting_member_lidnr' => $grant->getMember()->getLidnr(),
    );
}
?>
<script>
    $(document).ready(function() {
        var withdrawals = <?= json_encode($arrGrants); ?>;
        $('.key-withdraw-slot').change(function() {
            var data = withdrawals[$('.key-withdraw-slot:checked').val()];
            $('#withdraw-grant-key-meeting-type').val(data['meeting_type']);
            $('#withdraw-grant-key-meeting-number').val(data['meeting_number']);
            $('#withdraw-grant-key-decision-point').val(data['decision_point']);
            $('#withdraw-grant-key-decision-number').val(data['decision_number']);
            $('#withdraw-grant-key-subdecision-sequence').val(data['subdecision_sequence']);
            $('#withdraw-grant-key-granting-until').val(data['granting_until']);
            $('#withdraw-grant-key-granting-member-lidnr').val(data['granting_member_lidnr']);
            $('#key-withdraw-submit').prop('disabled', false);
        });
    });
</script>
<?php
$form->prepare();

$form->setAttribute('action', $this->url('meeting/decision/form', ['form' => 'key_withdraw']));
$form->setAttribute('method', 'post');

$form->setAttribute('role', 'form');
$form->setAttribute('class', 'form-horizontal');
?>
<?= $this->form()->openTag($form) ?>
<?php
// default hidden elements for the meeting and decision reference
$fs = $form->get('meeting');
$fsg = $form->get('granting');
$fsgm = $fsg->get('member');
?>
<?= $this->formHidden($fs->get('type')) ?>
<?= $this->formHidden($fs->get('number')) ?>
<?= $this->formHidden($fs->get('date')) ?>
<?= $this->formHidden($form->get('point')) ?>
<?= $this->formHidden($form->get('decision')) ?>

<div class="form-group">
    <?php
    $fs = $form->get('subdecision');
    $fs->get('meeting_type')->setAttribute('id', 'withdraw-grant-key-meeting-type');
    $fs->get('meeting_number')->setAttribute('id', 'withdraw-grant-key-meeting-number');
    $fs->get('decision_point')->setAttribute('id', 'withdraw-grant-key-decision-point');
    $fs->get('decision_number')->setAttribute('id', 'withdraw-grant-key-decision-number');
    $fs->get('sequence')->setAttribute('id', 'withdraw-grant-key-subdecision-sequence');
    $fsg->get('until')->setAttribute('id', 'withdraw-grant-key-granting-until');
    $fsgm->get('lidnr')->setAttribute('id', 'withdraw-grant-key-granting-member-lidnr');
    ?>
    <?= $this->formHidden($fs->get('meeting_type')) ?>
    <?= $this->formHidden($fs->get('meeting_number')) ?>
    <?= $this->formHidden($fs->get('decision_point')) ?>
    <?= $this->formHidden($fs->get('decision_number')) ?>
    <?= $this->formHidden($fs->get('sequence')) ?>
    <?= $this->formHidden($fsg->get('until')) ?>
    <?= $this->formHidden($fsgm->get('lidnr')) ?>
    <label class="col-md-2 control-label">
        <?= $this->translate('Key Code(s) to Withdraw') ?>
    </label>
    <div class="col-md-10">
        <?php foreach ($grants as $key => $grant): ?>
            <div class="radio">
                <label>
                    <input type="radio" name="key-withdraw-slot" class="key-withdraw-slot" value="<?= $key ?>">
                    <?= $grant->getMember()->getFullName() ?> (<?= $grant->getUntil()->format('Y-m-d') ?>)<br>
                </label>
            </div>
        <?php endforeach ?>
    </div>
</div>

<div class="form-group">
    <?php
    $element = $form->get('withdrawOn');
    $element->setAttribute('class', 'form-control');
    $element->setAttribute('placeholder', $element->getLabel());
    $element->setLabelAttributes(array(
        'class' => 'col-md-2 control-label'
    ));
    ?>
    <?= $this->formLabel($element) ?>
    <div class="col-md-10">
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php
        $submit = $form->get('submit');
        $submit->setLabel($submit->getValue());
        $submit->setAttribute('class', 'btn btn-primary');
        $submit->setAttribute('id', 'key-withdraw-submit');
        $submit->setAttribute('disabled', 'disabled');
        ?>
        <?= $this->formButton($submit) ?>
    </div>
</div>

<?= $this->form()->closeTag() ?>
