#!/bin/sh
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-PGSQL
    CREATE DATABASE $DOCTRINE_REPORT_DATABASE;
    GRANT ALL PRIVILEGES ON DATABASE $DOCTRINE_REPORT_DATABASE TO $POSTGRES_USER;
PGSQL
