<h1>API Keys</h1>
<table class="table">
  <thead>
    <tr>
      <th>#</th>
      <th>Name</th>
      <th>Secret</th>
      <th>Webhook</th>
      <th>Delete</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach ($keys as $key): ?>
    <tr>
      <td><?= $key->getId() ?></td>
      <td><?= $key->getName() ?></td>
      <td><?= $key->getSecret() ?></td>
      <td><?= $key->getWebhook() ?></td>
      <td>
        <form method="post" action="<?= $this->url('settings/api/delete', ['id' => $key->getId()]) ?>">
          <button class="btn btn-danger btn-xs" type="submit">Delete</button>
        </form>
      </td>
    </tr>
    <?php endforeach ?>
  </tbody>
<table>

<a href="<?= $this->url('settings/api/create') ?>" class="btn btn-success">
     <span class="glyphicon glyphicon-plus"></span>
     Voeg API key toe</a>
