<?php

declare(strict_types=1);

use Application\View\HelperTrait;
use Laminas\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer|HelperTrait $this
 * @var int $members
 * @var int $expired
 * @var int $prospectives
 * @var int $updates
 */

$showPendingUpdates = 0 < $updates;
?>
<div class="row">
    <div class="col-md-12">
        <h1><span class="gewis-red"><strong>GEWIS</strong></span>Database</h1>
        <hr>
    </div>
</div>
<div class="row">
    <div class="<?= $showPendingUpdates ? 'col-md-8' : 'col-md-12'?>">
        <p>
            <?= sprintf(
                $this->translate('GEWIS currently has <a href="%s">%d members</a> (+%d expired) and <a href="%s">%d prospective members</a>. <a href="%s">Click here</a> to create a meeting or <a href="%s">perform a query</a>.'),
                $this->url('member'),
                $members,
                $expired,
                $this->url('prospective-member'),
                $prospectives,
                $this->url('meeting/create'),
                $this->url('query'),
            ) ?>
        </p>
        <p>
            <?= sprintf(
                $this->translate('You are using a build based on commit <a target="_blank" href="https://github.com/GEWIS/gewisdb/commit/%1$s">%1$s</a>. Please include this in all your bug reports.'),
                getenv("GIT_COMMIT", true)
            ) ?>
        </p>
    </div>
    <?php if ($showPendingUpdates): ?>
        <div class="col-md-4">
            <div class="panel panel-info">
                <div class="panel-heading"><?= $this->translate('Pending member updates') ?></div>
                <div class="panel-body">
                    <p>
                        <?= sprintf(
                            $this->translatePlural(
                                'There is currently <a href="%s">%d update</a> pending approval.',
                                'There are currently <a href="%s">%d updates</a> pending approval.',
                                $updates,
                            ),
                            $this->url('member/updates'),
                            $updates,
                        ) ?>
                    </p>
                </div>
            </div>
        </div>
    <?php endif; ?>
</div>
<div class="row">
    <div class="col-md-12">
        <p>
            <a class="btn btn-primary" href="https://github.com/GEWIS/gewisdb" target="_blank">
                <?= $this->translate('Fork GEWISDB on GitHub &raquo;') ?>
            </a>
        </p>
    </div>
</div>
