<?php

declare(strict_types=1);

namespace App\Form\User;

use App\Entity\User\ApiPrincipal;
use App\Entity\User\Enums\ApiPermissions;
use Override;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Event\PreSetDataEvent;
use Symfony\Component\Form\Extension\Core\Type\EnumType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints as Assert;

use function Symfony\Component\Translation\t;

class ApiPrincipalType extends AbstractType
{
    /**
     * @param array<string, mixed> $options
     */
    #[Override]
    public function buildForm(
        FormBuilderInterface $builder,
        array $options,
    ): void {
        $builder->add(
            'description',
            TextType::class,
            [
                'label' => t('Description'),
                'constraints' => [new Assert\NotBlank()],
            ],
        );

        $builder->add(
            'token',
            TextType::class,
            self::tokenOptions(),
        );

        $builder->add(
            'permissions',
            EnumType::class,
            [
                'class' => ApiPermissions::class,
                'label' => t('Select API permissions'),
                'expanded' => true,
                'multiple' => true,
                'constraints' => [new Assert\NotBlank()],
            ],
        );

        $builder->add(
            'submit',
            SubmitType::class,
            ['label' => t('Create API principal')],
        );

        // ApiPrincipal only ever exposes a masked token, and only once it has one.
        $builder->addEventListener(
            FormEvents::PRE_SET_DATA,
            static function (PreSetDataEvent $event): void {
                $principal = $event->getData();

                if (
                    !$principal instanceof ApiPrincipal
                    || null === $principal->getId()
                ) {
                    return;
                }

                $event->getForm()->add(
                    'token',
                    TextType::class,
                    self::tokenOptions($principal->getToken()),
                );
            },
        );
    }

    #[Override]
    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults(['data_class' => ApiPrincipal::class]);
    }

    /**
     * The token is generated by the application and can never be written through this form.
     *
     * @return array<string, mixed>
     */
    private static function tokenOptions(?string $token = null): array
    {
        return [
            'label' => t('Token'),
            'mapped' => false,
            'required' => false,
            'disabled' => true,
            'data' => $token,
            'attr' => ['readonly' => true],
        ];
    }
}
