<?php if (isset($success) && $success): ?>
Success!
<?php else: ?>
<?php
$form = $this->form;
$form->prepare();

$form->setAttribute('action', $this->url('database/default', array('action' => 'create')));
$form->setAttribute('method', 'post');

$form->setAttribute('role', 'form');

echo $this->form()->openTag($form);
?>
<div class="form-group">
<?php
$element = $form->get('number');
$element->setAttribute('class', 'form-control');
$element->setAttribute('placeholder', 'Vergadernummer');
?>
    <?= $this->formLabel($element) ?>
    <?= $this->formInput($element) ?>
    <?= $this->formElementErrors($element) ?>
</div>
<div class="form-group">
<?php
$element = $form->get('type');
$element->setAttribute('class', 'form-control');
?>
    <?= $this->formLabel($element) ?>
    <?= $this->formSelect($element) ?>
    <?= $this->formElementErrors($element) ?>
</div>
<div class="form-group">
<?php
$element = $form->get('date');
$element->setAttribute('class', 'form-control');
$element->setAttribute('placeholder', 'Vergaderdatum');
?>
    <?= $this->formLabel($element) ?>
    <?= $this->formInput($element) ?>
    <?= $this->formElementErrors($element) ?>
</div>

<?php
$submit = $form->get('submit');
$submit->setLabel('Submit');
$submit->setAttribute('class', 'btn btn-default');
?>
<?= $this->formButton($submit) ?>

<?= $this->form()->closeTag(); ?>
<?php endif; ?>
