<?php

declare(strict_types=1);

use Application\View\HelperTrait;
use Laminas\View\Renderer\PhpRenderer;

/** @var PhpRenderer|HelperTrait $this */
?>
<script>
    let urlTemplate = '<?= $this->url('prospective-member/show', array('id' => '__LIDNR__')) ?>';

    $(document).ready(function () {
        const maxResults = 128;
        let searchMember = function (term) {
            const types = ['', 'pending', 'paid'];

            types.forEach((type) => {
                let tableType = (type === '') ? '' : type + '-';
                let footer = $('#members-' + tableType + 'result tfoot');

                // When no term is set, all the member should be shown
                if (term.length >= 0) {
                    $.ajax({
                        dataType: 'json',
                        url: '<?= $this->url('prospective-member/default', array('action' => 'search')) ?>?q=' + term + '&type=' + type,
                        context: document.body
                    }).done(function (data) {
                        let table = '';
                        $.each(data.json, function (idx, member) {
                            let link = '';
                            link += '<a style="display: block; width: 100%; height: 100%;" href="' + urlTemplate.replace('__LIDNR__', member.lidnr) + '">'
                            table += '<tr>';
                            table += '<td>' + link + member.fullName + '</a></td>';
                            table += '<td>' + link + member.email + '</a></td>';
                            table += '</tr>';
                        });

                        $('#members-' + tableType + 'result tbody').html(table);

                        if (data.json.length >= maxResults) {
                            footer.show();
                        } else {
                            footer.hide();
                        }
                    });
                } else {
                    $('#members-result tbody').html('');
                }
            });
        };

        $('#member-search').keyup(function (e) {
            term = $(e.target).val();
            searchMember(term)
        });
        searchMember('');
    });
</script>

<div class="row">
    <div class="col-md-12">
        <form role="form">
            <div class="form-group">
                <label for="member-search">
                    <?= $this->translate('Search Prospective Members') ?>
                </label>
                <input type="text" class="form-control" placeholder="<?= $this->translate('Search') ?>" id="member-search" autofocus>
            </div>
        </form>
    </div>
</div>
<div class="row">
    <div class="col-md-4 col-md-push-8">
        <div class="row">
            <div class="col-md-12">
                <h4><?= $this->translate('Paid') ?></h4>
            </div>
            <div class="col-md-12">
                <table class="table table-hover" id="members-result">
                    <thead>
                    <tr>
                        <th><?= $this->translate('Name') ?></th>
                        <th><?= $this->translate('E-mail Address') ?></th>
                    </tr>
                    </thead>
                    <tbody>
                    </tbody>
                    <tfoot>
                    <tr>
                        <td colspan="2">
                            <?= $this->translate('There are too many results to display. Try filtering to see other results.') ?>
                        </td>
                    </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="row">
            <div class="col-md-12">
                <h4><?= $this->translate('Pending') ?></h4>
            </div>
            <div class="col-md-12">
                <table class="table table-hover" id="members-pending-result">
                    <thead>
                    <tr>
                        <th><?= $this->translate('Name') ?></th>
                        <th><?= $this->translate('E-mail Address') ?></th>
                    </tr>
                    </thead>
                    <tbody>
                    </tbody>
                    <tfoot>
                    <tr>
                        <td colspan="2">
                            <?= $this->translate('There are too many results to display. Try filtering to see other results.') ?>
                        </td>
                    </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
    <div class="col-md-4 col-md-pull-8">
        <div class="row">
            <div class="col-md-12">
                <h4><?= $this->translate('Created / Failed') ?></h4>
            </div>
            <div class="col-md-12">
                <table class="table table-hover" id="members-paid-result">
                    <thead>
                        <tr>
                            <th><?= $this->translate('Name') ?></th>
                            <th><?= $this->translate('E-mail Address') ?></th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                    <tfoot>
                        <tr>
                            <td colspan="2">
                                <?= $this->translate('There are too many results to display. Try filtering to see other results.') ?>
                            </td>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
</div>

<a href="<?= $this->url('member/subscribe') ?>" class="btn btn-success">
    <span class="glyphicon glyphicon-plus"></span> <?= $this->translate('Register Member') ?>
</a>
