<?php

declare(strict_types=1);

use Application\Model\Enums\AddressTypes;
use Application\View\HelperTrait;
use Laminas\Form\Element\Checkbox;
use Laminas\View\Renderer\PhpRenderer;

/** @var PhpRenderer|HelperTrait $this */
?>
<div class="row">
<div class="col-md-6">
    <h1><?= $this->escapeHtml($member->getFullName()) ?></h1>
    <table class="table table-bordered">
        <tr>
            <th></th>
            <th><?= $this->translate('Provided Data') ?></th>
            <th><?= $this->translate('TU/e Data') ?></th>
        </tr>
        <tr class="<?= ($tueData->isValid() && $member->getInitials() === $tueData->getInitials()) ? 'datavalid' : 'datamismatch'?>">
            <th><?= $this->translate('Initial(s)') ?></th>
            <td><?= $member->getInitials() ?></td>
            <?php if (!$tueData->isValid()): ?>
                <td rowspan="9" style="background-color: lightgray;"><?= $this->translate('No data returned.') ?></td>
            <?php else: ?>
                <td><?= $tueData->getInitials() ?></td>
            <?php endif; ?>
        </tr>
        <tr class="<?= ($tueData->isValid() && $member->getFirstName() === $tueData->getFirstName()) ? 'datavalid' : 'datamismatch'?>">
            <th><?= $this->translate('First Name') ?></th>
            <td><?= $member->getFirstName() ?></td>
            <?php if ($tueData->isValid()): ?>
                <td><?= $tueData->getFirstName() ?></td>
            <?php endif; ?>
        </tr>
        <tr class="<?= ($tueData->isValid() && $member->getMiddleName() === $tueData->computedPrefixName()) ? 'datavalid' : 'datamismatch'?>">
            <th><?= $this->translate('Last Name Prepositional Particle') ?></th>
            <td><?= $member->getMiddleName() ?></td>
            <?php if ($tueData->isValid()): ?>
                <td style="vertical-align: middle;"><?= $tueData->computedPrefixName() ?></td>
            <?php endif; ?>
        </tr>
        <tr class="<?= ($tueData->isValid() && $member->getLastName() === $tueData->computedLastName()) ? 'datavalid' : 'datamismatch'?>">
            <th><?= $this->translate('Last Name') ?></th>
            <td><?= $member->getLastName() ?></td>
            <?php if ($tueData->isValid()): ?>
                <td style="vertical-align: middle;"><?= $tueData->computedLastName() ?></td>
            <?php endif; ?>
        </tr>
        <tr>
            <th><?= $this->translate('TU/e-username') ?></th>
            <td>
                <?php if (null === $member->getTueUsername()): ?>
                    <?= $this->translate('Unknown') ?>
                <?php else: ?>
                    <a href="<?= $this->url('member/tuelookup') ?>?u=<?= $member->getTueUsername() ?>">
                        <?= $member->getTueUsername() ?>
                    </a>
                <?php endif; ?>
            </td>
            <?php if ($tueData->isValid()): ?><td><?= $tueData->getUsername() ?></td><?php endif; ?>
        </tr>
        <tr>
            <th><?= $this->translate('E-mail Address') ?></th>
            <td><a href="mailto:<?= $member->getEmail() ?>"><?= $member->getEmail() ?></a></td>
            <?php if ($tueData->isValid()): ?>
                <td><a href="mailto:<?= $tueData->getEmail() ?>"><?= $tueData->getEmail() ?></a></td>
            <?php endif; ?>
        </tr>
        <tr>
            <th><?= $this->translate('Birthdate') ?></th>
            <td><?= $member->getBirth()->format('l j F Y') ?></td>
            <?php if ($tueData->isValid()): ?><td style="background-color: lightgray;"></td><?php endif; ?>
        </tr>
        <tr>
            <th><?= $this->translate('Last Update to Membership') ?></th>
            <td><?= $member->getChangedOn()->format('l j F Y') ?></td>
            <?php if ($tueData->isValid()): ?><td><?= $tueData->getChangedOn()->format('l j F Y') ?></td><?php endif; ?>
        </tr>
        <tr>
            <th><?= $this->translate('Study') ?></th>
            <td><?= $member->getStudy() ?></td>
            <?php if ($tueData->isValid()): ?><td>
                <?php foreach($tueData->getRegistrations() as $registration): ?>
                    <?=
                        sprintf(
                            $this->translate('%s: %s (started in %s)'),
                            $registration['dept'],
                            $registration['study'],
                            $registration['generation'],
                        )
                    ?><br>
                <?php endforeach;  ?>
            </td><?php endif; ?>
        </tr>
    </table>
    <?php foreach ($tueStatus as $alert): ?>
        <div class="alert alert-<?= $alert[0] ?>" role="alert">
            <?= $alert[1] ?>
        </div>
    <?php endforeach; ?>

    <?php
    $form->prepare();

    $form->setAttribute('action', $this->url('prospective-member/show/finalize', array('id' => $member->getLidnr())));
    $form->setAttribute('method', 'post');

    $form->setAttribute('role', 'form');
    ?>
    <?= $this->form()->openTag($form) ?>
    <?php
    $element = $form->get('type');
    $element->setAttribute('placeholder', $element->getLabel());

    //$element->setLabelAttributes(array('class' => 'radio-inline'));
    ?>
    <div class="form-group">
        <label for="<?= $element->getName() ?>" class="control-label col-sm-4 label-required"><?= $element->getLabel() ?></label>
        <br>
        <div class="col-sm-12">
            <?php foreach ($element->getValueOptions() as $option => $text): ?>
                <div class="radio">
                    <label>
                        <input type="radio" name="<?= $element->getName() ?>" id="<?= $element->getName() ?>" value="<?= $option ?>" <?= $element->getValue() == $option ? 'checked' : '' ?>>
                        <?= $text ?>
                    </label>
                </div>
            <?php endforeach ?>
            <?= $this->formElementErrors($element) ?>
        </div>
    </div>

    <?php
    $element = $form->get('updatedata');
    if ($tueData->isValid()) {
        $element->setChecked(true);
    } else {
        $element->setChecked(false);
        $element->setAttributes([
            "disabled" => true,
        ]);
    }
    ?>
    <div class="form-group">
        <div class="col-sm-12">
            <div class="checkbox">
                <label>
                    <?= $this->formCheckbox($element) ?>
                    <?= $element->getLabel() ?>
                </label>
                <?= $this->formElementErrors($element) ?>
            </div>
            <?= $this->formElementErrors($element) ?>
        </div>
    </div>

    <?php
    $submit = $form->get('submit');
    $submit->setLabel($this->translate('Approve Membership'));
    $submit->setAttribute('class', 'btn btn-success');
    ?>
    <?= $this->formButton($submit) ?>
    <a href="<?= $this->url('prospective-member/show/delete', array(
        'id' => $member->getLidnr()
    )) ?>" class="btn btn-danger"><?= $this->translate('Delete Prospective Member') ?></a>
    <?= $this->form()->closeTag($form) ?>
</div>
<div class="col-md-6">
<h3><?= $this->translate('Addresses') ?></h3>
<?php $addresses = array() ?>
<?php foreach ($member->getAddresses() as $address): ?>
<?php $addresses[$address->getType()->value] = $address ?>
<h4><?= $address->getType()->getName($this->plugin('translate')->getTranslator()) ?></h4>
<table class="table table-bordered">
    <tr>
        <th><?= $this->translate('Postal Region') ?></th>
        <td><?= $address->getCountry()->value ?></td>
    </tr>
    <tr>
        <th><?= $this->translate('Street and House Number') ?></th>
        <td><?= $address->getStreet() ?> <?= $address->getNumber() ?></td>
    </tr>
    <tr>
        <th><?= $this->translate('City and Postal Code') ?></th>
        <td><?= $address->getCity() ?> <?= $address->getPostalCode() ?></td>
    </tr>
    <tr>
        <th><?= $this->translate('Phone Number') ?></th>
        <td><?= $address->getPhone() ?></td>
    </tr>
</table>
<?php endforeach ?>
<h3><?= $this->translate('Mailing List Subscriptions') ?></h3>
<ul>
<?php foreach ($member->getLists() as $list): ?>
    <li><?= $list->getName() ?></li>
<?php endforeach ?>
</ul>
</div>
</div>
