<?php

declare(strict_types=1);

use Application\Model\Enums\AddressTypes;
use Application\View\HelperTrait;
use Checker\Model\TueData as TueDataModel;
use Database\Model\ProspectiveMember as ProspectiveMemberModel;
use Laminas\Form\Element\Checkbox;
use Laminas\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer|HelperTrait $this
 * @var ProspectiveMemberModel $member
 * @var bool $canDelete
 * @var TueDataModel $tueData
 * @var array<array-key, string[]> $tueStatus
 */
?>
<div class="row">
    <div class="col-md-12">
        <h1><?= $this->escapeHtml($member->getFullName()) ?></h1>
    </div>
<div class="col-md-6">
    <table class="table table-bordered">
        <tr>
            <th></th>
            <th><?= $this->translate('Provided Data') ?></th>
            <th><?= $this->translate('TU/e Data') ?></th>
        </tr>
        <tr class="<?= ($tueData->isValid() && $member->getInitials() === $tueData->getInitials()) ? 'datavalid' : 'datamismatch'?>">
            <th><?= $this->translate('Initial(s)') ?></th>
            <td><?= $member->getInitials() ?></td>
            <?php if (!$tueData->isValid()): ?>
                <td rowspan="9" style="background-color: lightgray;"><?= $this->translate('No data returned.') ?></td>
            <?php else: ?>
                <td><?= $tueData->getInitials() ?></td>
            <?php endif; ?>
        </tr>
        <tr class="<?= ($tueData->isValid() && $member->getFirstName() === $tueData->getFirstName()) ? 'datavalid' : 'datamismatch'?>">
            <th><?= $this->translate('First Name') ?></th>
            <td><?= $member->getFirstName() ?></td>
            <?php if ($tueData->isValid()): ?>
                <td><?= $tueData->getFirstName() ?></td>
            <?php endif; ?>
        </tr>
        <tr class="<?= ($tueData->isValid() && $member->getMiddleName() === $tueData->computedPrefixName()) ? 'datavalid' : 'datamismatch'?>">
            <th><?= $this->translate('Last Name Prepositional Particle') ?></th>
            <td><?= $member->getMiddleName() ?></td>
            <?php if ($tueData->isValid()): ?>
                <td style="vertical-align: middle;"><?= $tueData->computedPrefixName() ?></td>
            <?php endif; ?>
        </tr>
        <tr class="<?= ($tueData->isValid() && $member->getLastName() === $tueData->computedLastName()) ? 'datavalid' : 'datamismatch'?>">
            <th><?= $this->translate('Last Name') ?></th>
            <td><?= $member->getLastName() ?></td>
            <?php if ($tueData->isValid()): ?>
                <td style="vertical-align: middle;"><?= $tueData->computedLastName() ?></td>
            <?php endif; ?>
        </tr>
        <tr>
            <th><?= $this->translate('TU/e-username') ?></th>
            <td>
                <?php if (null === $member->getTueUsername()): ?>
                    <?= $this->translate('Unknown') ?>
                <?php else: ?>
                    <a href="<?= $this->url('member/tuelookup') ?>?u=<?= $member->getTueUsername() ?>">
                        <?= $member->getTueUsername() ?>
                    </a>
                <?php endif; ?>
            </td>
            <?php if ($tueData->isValid()): ?><td><?= $tueData->getUsername() ?></td><?php endif; ?>
        </tr>
        <tr>
            <th><?= $this->translate('E-mail Address') ?></th>
            <td><a href="mailto:<?= $member->getEmail() ?>"><?= $member->getEmail() ?></a></td>
            <?php if ($tueData->isValid()): ?>
                <td><a href="mailto:<?= $tueData->getEmail() ?>"><?= $tueData->getEmail() ?></a></td>
            <?php endif; ?>
        </tr>
        <tr>
            <th><?= $this->translate('Birthdate') ?></th>
            <td><?= $member->getBirth()->format('l j F Y') ?></td>
            <?php if ($tueData->isValid()): ?><td style="background-color: lightgray;"></td><?php endif; ?>
        </tr>
        <tr>
            <th><?= $this->translate('Last Update to Membership') ?></th>
            <td><?= $member->getChangedOn()->format('l j F Y') ?></td>
            <?php if ($tueData->isValid()): ?><td><?= $tueData->getChangedOn()->format('l j F Y') ?></td><?php endif; ?>
        </tr>
        <tr>
            <th><?= $this->translate('Study') ?></th>
            <td><?= $member->getStudy() ?></td>
            <?php if ($tueData->isValid()): ?><td>
                <?php foreach($tueData->getRegistrations() as $registration): ?>
                    <?=
                        sprintf(
                            $this->translate('%s: %s (started in %s)'),
                            $registration['dept'],
                            $registration['study'],
                            $registration['generation'],
                        )
                    ?><br>
                <?php endforeach;  ?>
            </td><?php endif; ?>
        </tr>
    </table>
</div>
    <div class="col-md-6">
        <div class="row">
            <div class="col-md-12">
                <h3><?= $this->translate('Addresses') ?></h3>
                <?php $addresses = array() ?>
                <?php foreach ($member->getAddresses() as $address): ?>
                    <?php $addresses[$address->getType()->value] = $address ?>
                    <h4><?= $address->getType()->getName($this->plugin('translate')->getTranslator()) ?></h4>
                    <table class="table table-bordered">
                        <tr>
                            <th><?= $this->translate('Postal Region') ?></th>
                            <td><?= $address->getCountry()->value ?></td>
                        </tr>
                        <tr>
                            <th><?= $this->translate('Street and House Number') ?></th>
                            <td><?= $address->getStreet() ?> <?= $address->getNumber() ?></td>
                        </tr>
                        <tr>
                            <th><?= $this->translate('City and Postal Code') ?></th>
                            <td><?= $address->getCity() ?> <?= $address->getPostalCode() ?></td>
                        </tr>
                        <tr>
                            <th><?= $this->translate('Phone Number') ?></th>
                            <td><?= $address->getPhone() ?></td>
                        </tr>
                    </table>
                <?php endforeach; ?>
            </div>
            <div class="col-md-12">
                <h3><?= $this->translate('Mailing List Subscriptions') ?></h3>
                <?php if (0 === $member->getLists()->count()): ?>
                    <p>
                        <?= $this->translate('No mailing list subscriptions.') ?>
                    </p>
                <?php else: ?>
                    <ul>
                        <?php foreach ($member->getLists() as $list): ?>
                            <li><?= $list->getName() ?></li>
                        <?php endforeach ?>
                    </ul>
                <?php endif; ?>
            </div>
            <div class="col-md-12">
                <h3><?= $this->translate('Checkout Status') ?></h3>
                <?php if (0 === $member->getCheckoutSessions()->count()): ?>
                    <p>
                        <?= $this->translate('No Checkout Sessions on record.') ?>
                    </p>
                <?php else: ?>
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th scope="col"><?= $this->translate('Created') ?></th>
                                <th scope="col"><?= $this->translate('Status') ?></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php $translator = $this->plugin('translate')->getTranslator(); ?>
                            <?php foreach ($member->getCheckoutSessions() as $checkoutSession): ?>
                                <tr>
                                    <td><?= $checkoutSession->getCreated()->format(DateTimeInterface::ATOM) ?></td>
                                    <td><?= $checkoutSession->getState()->getName($translator) ?></td>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <h2><?= $this->translate('Approval') ?></h2>
    </div>
    <div class="col-md-12">
        <?php foreach ($tueStatus as $alert): ?>
            <div class="alert alert-<?= $alert[0] ?>" role="alert">
                <?= $alert[1] ?>
            </div>
        <?php endforeach; ?>

        <?php if (isset($form)): ?>
            <?php if (!$member->hasPaid()): ?>
                <div class="panel-group">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title">
                                <a data-toggle="collapse" href="#not-paid-collapse">
                                    <?= $this->translate('Click here for approval if membership fee paid with cash.') ?>
                                </a>
                            </h4>
                        </div>
                        <div id="not-paid-collapse" class="panel-collapse collapse">
                            <div class="panel-body">
            <?php endif; ?>
            <?php
            $form->prepare();

            $form->setAttribute('action', $this->url('prospective-member/show/finalize', ['id' => $member->getLidnr()]));
            $form->setAttribute('method', 'post');

            $form->setAttribute('role', 'form');
            ?>
            <?= $this->form()->openTag($form) ?>
            <?php
            $element = $form->get('type');
            $element->setAttribute('placeholder', $element->getLabel());
            ?>
            <div class="form-group">
                <label for="<?= $element->getName() ?>" class="control-label col-sm-4 label-required">
                    <?= $element->getLabel() ?>
                </label>
                <br>
                <div class="col-sm-12">
                    <?php foreach ($element->getValueOptions() as $option => $text): ?>
                        <div class="radio">
                            <label>
                                <input type="radio" name="<?= $element->getName() ?>" id="<?= $element->getName() ?>" value="<?= $option ?>" <?= $element->getValue() == $option ? 'checked' : '' ?>>
                                <?= $text ?>
                            </label>
                        </div>
                    <?php endforeach ?>
                    <?= $this->formElementErrors($element) ?>
                </div>
            </div>

            <?php
            $element = $form->get('updatedata');
            if ($tueData->isValid()) {
                $element->setChecked(true);
            } else {
                $element->setChecked(false);
                $element->setAttributes([
                    'disabled' => true,
                ]);
            }
            ?>
            <div class="form-group">
                <div class="col-sm-12">
                    <div class="checkbox">
                        <label>
                            <?= $this->formCheckbox($element) ?>
                            <?= $element->getLabel() ?>
                        </label>
                        <?= $this->formElementErrors($element) ?>
                    </div>
                    <?= $this->formElementErrors($element) ?>
                </div>
            </div>

            <?php
            $submit = $form->get('submit');
            $submit->setLabel($this->translate('Approve Membership'));
            $submit->setAttribute('class', 'btn btn-success');
            ?>
            <?= $this->formButton($submit) ?>
            <?php if (!$canDelete): ?>
                <?= $this->form()->closeTag() ?>
            <?php endif; ?>
            <?php if (!$member->hasPaid()): ?>
                            </div>
                        </div>
                    </div>
                </div>
            <?php endif; ?>
        <?php else: ?>
            <p>
                <?= $this->translate('This prospective member cannot be approved.') ?>
            </p>
        <?php endif; ?>
        <?php if ($canDelete): ?>
            <button type="button" class="btn btn-danger remove-modal">
                <?= $this->translate('Delete Prospective Member') ?>
            </button>
            <?php if (isset($form)): ?>
                <?= $this->form()->closeTag() ?>
            <?php endif; ?>
            <div id="prospective-removal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="prospective-removal-label" aria-hidden="true">
                <div class="modal-dialog modal-sm">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                            <h4 class="modal-title" id="prospective-removal-label">
                                <?= $this->translate('Remove Prospective Member') ?>
                            </h4>
                        </div>
                        <div class="modal-body">
                            <?php if ($member->hasPaid()): ?>
                                <?= sprintf(
                                    // phpcs:ignore -- user-visible strings should not be split
                                    $this->translate('Are you sure that you want to remove %s? Because they have already paid a refund will be requested. If this fails, the prospective member will NOT be removed.'),
                                    '<span class="name">' . $this->escapeHtml($member->getFullName()) . '</span>',
                                ) ?>
                            <?php else: ?>
                                <?= sprintf(
                                    $this->translate('Are you sure that you want to remove %s?'),
                                    '<span class="name">' . $this->escapeHtml($member->getFullName()) . '</span>',
                                ) ?>
                            <?php endif; ?>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">
                                <?= $this->translate('No') ?>
                            </button>
                            <a href="<?= $this->url('prospective-member/show/delete', [
                                'id' => $member->getLidnr()
                            ]) ?>" class="btn btn-danger" id="remove-modal-yes">
                                <?= $this->translate('Delete Prospective Member') ?>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <script>
                $('button.remove-modal').click(function() {
                    let modal = $('#prospective-removal');
                    modal.modal();
                });
            </script>
        <?php endif; ?>
    </div>
</div>
