<?php
use Database\Model\Member;
use Database\Model\Address;
?>
<div class="row">
<div class="col-md-6">
    <h1><?= $member->getFullName() ?></h1>
    <table class="table table-bordered">
        <tr>
            <th>Lidnummer</th>
            <td><?= $member->getLidnr() ?></td>
        </tr>
        <tr>
            <th>Voorletters</th>
            <td><?= $member->getInitials() ?></td>
        </tr>
        <tr>
            <th>Voornaam</th>
            <td><?= $member->getFirstName() ?></td>
        </tr>
        <tr>
            <th>Tussenvoegsels</th>
            <td><?= $member->getMiddleName() ?></td>
        </tr>
        <tr>
            <th>Achternaam</th>
            <td><?= $member->getLastName() ?></td>
        </tr>
        <tr>
            <th>Geslacht</th>
            <td><?php
switch ($member->getGender()) {
case Member::GENDER_MALE:
    echo 'Man';
    break;
case Member::GENDER_FEMALE:
    echo 'Vrouw';
    break;
case Member::GENDER_OTHER:
    echo 'Anders';
    break;
}
?></td>
        </tr>
        <tr>
            <th>TU/e-gebruikersnaam</th>
            <td><?= (null === $member->getTueUsername()) ? 'Onbekend' : $member->getTueUsername() ?></td>
        </tr>
        <tr>
            <th>Email</th>
            <td><a href="mailto:<?= $member->getEmail() ?>"><?= $member->getEmail() ?></a></td>
        </tr>
        <tr>
            <th>Geboortedatum</th>
            <td><?= $member->getBirth()->format('l j F Y') ?></td>
        </tr>
        <tr>
            <th>Betaald (hoe veel)</th>
            <td><?= $member->getPaid() ?></td>
        </tr>
        <tr>
            <th>Type lid</th>
            <td><?php
switch ($member->getType()) {
    case Member::TYPE_ORDINARY:
        echo 'Gewoon';
        break;
    case Member::TYPE_EXTERNAL:
        echo 'Extern';
        break;
    case Member::TYPE_GRADUATE:
        echo 'Afgestudeerde';
        break;
    case Member::TYPE_HONORARY:
        echo 'Erelid';
        break;
}
?></td>
        </tr>
        <tr>
            <th>Laatste wijziging lidmaatshap</th>
            <td><?= $member->getChangedOn()->format('l j F Y') ?></td>
        </tr>
    </table>
    <?php
    $form->prepare();

    $form->setAttribute('action', $this->url('prospective-member/show/finalize', array('id' => $member->getLidnr())));
    $form->setAttribute('method', 'post');

    $form->setAttribute('role', 'form');
    ?>
    <?= $this->form()->openTag($form) ?>
    <?php
    $element = $form->get('type');
    $element->setAttribute('placeholder', $element->getLabel());
    //$element->setLabelAttributes(array('class' => 'radio-inline'));
    ?>
    <div class="form-group">
        <label for="<?= $element->getName() ?>" class="control-label col-sm-4 label-required"><?= $element->getLabel() ?></label>
        <br>
        <div class="col-sm-12">
            <?php foreach ($element->getValueOptions() as $option => $text): ?>
                <div class="radio">
                    <label>
                        <input type="radio" name="<?= $element->getName() ?>" id="<?= $element->getName() ?>" value="<?= $option ?>" <?= $element->getValue() == $option ? 'checked' : '' ?>>
                        <?= $text ?>
                    </label>
                </div>
            <?php endforeach ?>
            <?= $this->formElementErrors($element) ?>
        </div>
    </div>

    <?php
    $submit = $form->get('submit');
    $submit->setLabel('Keur lidmaatschap goed');
    $submit->setAttribute('class', 'btn btn-primary');
    ?>
    <?= $this->formButton($submit) ?>
    <a href="<?= $this->url('prospective-member/show/delete', array(
        'id' => $member->getLidnr()
    )) ?>" class="btn btn-danger">Verwijder lid</a>
    <?= $this->form()->closeTag($form) ?>
</div>
<div class="col-md-6">
<h3>Adressen</h3>
<?php $addresses = array() ?>
<?php foreach ($member->getAddresses() as $address): ?>
<?php $addresses[$address->getType()] = $address ?>
<h4><?php
switch ($address->getType()) {
case Address::TYPE_HOME:
    echo 'Thuisadres (ouders)';
    break;
case Address::TYPE_STUDENT:
    echo 'Kameradres';
    break;
case Address::TYPE_MAIL:
    echo 'Postadres';
    break;
}
?>
<table class="table table-bordered">
    <tr>
        <th>Land</th>
        <td><?= $address->getCountry() ?></td>
    </tr>
    <tr>
        <th>Straat en huisnummer</th>
        <td><?= $address->getStreet() ?> <?= $address->getNumber() ?></td>
    </tr>
    <tr>
        <th>Woonplaats en Postcode</th>
        <td><?= $address->getCity() ?> <?= $address->getPostalCode() ?></td>
    </tr>
    <tr>
        <th>Telefoonnummer</th>
        <td><?= $address->getPhone() ?></td>
    </tr>
</table>
<?php endforeach ?>
<h3>Aangemelde mailing lists</h3>
<ul>
<?php foreach ($member->getLists() as $list): ?>
    <li><?= $list->getName() ?></li>
<?php endforeach ?>
</ul>
<h3>Handtekening SEPA incasso</h3>
<img src="<?= $this->fileUrl($member->getSignature()) ?>" height="150" width="300" />
</div>
</div>
