<?php if (isset($success) && $success): ?>
Wijzigingen van <a href="<?= $this->url('member/show', array(
    'id' => $member->getLidnr()
)) ?>"><?= $member->getFullName() ?></a> opgeslagen!
<?php else: ?>
<h1>Wijzigen gegevens <?= $member->getFullName() ?></h1>
<div class="row">
<div class="col-md-6">
<?php
$form->prepare();

$form->setAttribute('action', $this->url('member/show/edit', array('id' => $member->getLidnr())));
$form->setAttribute('method', 'post');

$form->setAttribute('role', 'form');
$form->setAttribute('class', 'form-horizontal');
?>
    <?= $this->form()->openTag($form) ?>

<?php
$element = $form->get('lastName');
$element->setAttribute('class', 'form-control');
$element->setAttribute('placeholder', $element->getLabel());
?>
    <div class="form-group">
        <label for="<?= $element->getName() ?>" class="control-label col-sm-4"><?= $element->getLabel() ?></label>
        <div class="col-sm-8">
            <?= $this->formInput($element) ?>
            <?= $this->formElementErrors($element) ?>
            <?php
            if (
                null !== $tueData
                && $tueData->computedLastName() !== $member->getLastName()
            ):
            ?>
                <div class="text-warning">
                    <?= 'TU/e data: ' . $tueData->computedLastName() ?>
                </div>
            <?php
            endif;
            ?>
        </div>
    </div>

<?php
$element = $form->get('middleName');
$element->setAttribute('class', 'form-control');
$element->setAttribute('placeholder', $element->getLabel());
?>
    <div class="form-group">
        <label for="<?= $element->getName() ?>" class="control-label col-sm-4"><?= $element->getLabel() ?></label>
        <div class="col-sm-8">
            <?= $this->formInput($element) ?>
            <?= $this->formElementErrors($element) ?>
            <?php
            if (
                null !== $tueData
                && $tueData->computedPrefixName() !== $member->getMiddleName()
            ):
                ?>
                <div class="text-warning">
                    <?= 'TU/e data: ' . $tueData->computedPrefixName() ?>
                </div>
            <?php
            endif;
            ?>
        </div>
    </div>

<?php
$element = $form->get('initials');
$element->setAttribute('class', 'form-control');
$element->setAttribute('placeholder', $element->getLabel());
?>
    <div class="form-group">
        <label for="<?= $element->getName() ?>" class="control-label col-sm-4"><?= $element->getLabel() ?></label>
        <div class="col-sm-8">
            <?= $this->formInput($element) ?>
            <?= $this->formElementErrors($element) ?>
            <?php
            if (
                null !== $tueData
                && $tueData->getInitials() !== $member->getInitials()
            ):
                ?>
                <div class="text-warning">
                    <?= 'TU/e data: ' . $tueData->getInitials() ?>
                </div>
            <?php
            endif;
            ?>
        </div>
    </div>

<?php
$element = $form->get('firstName');
$element->setAttribute('class', 'form-control');
$element->setAttribute('placeholder', $element->getLabel());
?>
    <div class="form-group">
        <label for="<?= $element->getName() ?>" class="control-label col-sm-4"><?= $element->getLabel() ?></label>
        <div class="col-sm-8">
            <?= $this->formInput($element) ?>
            <?= $this->formElementErrors($element) ?>
            <?php
            if (
                null !== $tueData
                && $tueData->getFirstName() !== $member->getFirstName()
            ):
                ?>
                <div class="text-warning">
                    <?= 'TU/e data: ' . $tueData->getFirstName() ?>
                </div>
            <?php
            endif;
            ?>
        </div>
    </div>

<?php
$element = $form->get('tueUsername');
$element->setAttribute('class', 'form-control');
$element->setAttribute('placeholder', $element->getLabel());
?>
    <div class="form-group">
        <label for="<?= $element->getName() ?>" class="control-label col-sm-4"><?= $element->getLabel() ?></label>
        <div class="col-sm-8">
            <?= $this->formInput($element) ?>
            <?= $this->formElementErrors($element) ?>
        </div>
    </div>

<?php
$element = $form->get('email');
$element->setAttribute('class', 'form-control');
$element->setAttribute('placeholder', $element->getLabel());
?>
    <div class="form-group">
        <label for="<?= $element->getName() ?>" class="control-label col-sm-4"><?= $element->getLabel() ?></label>
        <div class="col-sm-8">
            <?= $this->formInput($element) ?>
            <?= $this->formElementErrors($element) ?>
        </div>
    </div>

<?php
$element = $form->get('birth');
$element->setAttribute('class', 'form-control');
$element->setAttribute('placeholder', $element->getLabel());
?>
    <div class="form-group">
        <label for="<?= $element->getName() ?>" class="control-label col-sm-4"><?= $element->getLabel() ?></label>
        <div class="col-sm-8">
            <?= $this->formInput($element) ?>
            <?= $this->formElementErrors($element) ?>
        </div>
    </div>

<?php
$element = $form->get('paid');
$element->setAttribute('class', 'form-control');
$element->setAttribute('placeholder', $element->getLabel());
?>
    <div class="form-group">
        <label for="<?= $element->getName() ?>" class="control-label col-sm-4"><?= $element->getLabel() ?></label>
        <div class="col-sm-8">
            <?= $this->formInput($element) ?>
            <?= $this->formElementErrors($element) ?>
        </div>
    </div>

<?php
$element = $form->get('hidden');
$element->setAttribute('class', 'checkbox form-control-checkbox');
?>
    <div class="form-group">
        <label for="<?= $element->getName() ?>" class="control-label col-sm-4">
            <?= $element->getLabel() ?>
        </label>
        <div class="col-sm-8">
            <?= $this->formCheckbox($element) ?>
            <?= $this->formElementErrors($element) ?>
        </div>
    </div>

<?php
$submit = $form->get('submit');
$submit->setLabel($submit->getValue());
$submit->setAttribute('class', 'btn btn-primary');
?>
<?= $this->formButton($submit) ?>

    <?= $this->form()->closeTag() ?>
</div>
<div class="col-md-6">
</div>
</div>
<?php endif ?>
