<?php
use Database\Model\Address;
$type = '';
switch ($address->getType()) {
case Address::TYPE_HOME:
    $type = 'thuisadres';
    break;
case Address::TYPE_STUDENT:
    $type = 'kameradres';
    break;
case Address::TYPE_MAIL:
    $type = 'postadres';
    break;
}
?>
<?php if (isset($success) && $success): ?>
<?php if (isset($add) && $add): ?>
Adres van <a href="<?= $this->url('member/show', array(
    'id' => $address->getMember()->getLidnr()
)) ?>"><?= $address->getMember()->getFullName() ?></a> opgeslagen.</h2>
<?php else: ?>
Adres van <a href="<?= $this->url('member/show', array(
    'id' => $address->getMember()->getLidnr()
)) ?>"><?= $address->getMember()->getFullName() ?></a> gewijzigd.</h2>
<?php endif ?>
<?php else: ?>
<?php if (isset($add) && $add): ?>
<h2>Voeg <?= $type ?> van <?= $address->getMember()->getFullName() ?> toe</h2>
<?php else: ?>
<h2>Wijzig <?= $type ?> van <?= $address->getMember()->getFullName() ?></h2>
<?php endif ?>
<br>
<?php
$form->prepare();

if (isset($add) && $add) {
    $form->setAttribute('action', $this->url('member/show/add-address', array(
        'id' => $address->getMember()->getLidnr(),
        'type' => $address->getType()
    )));
} else {
    $form->setAttribute('action', $this->url('member/show/edit/address', array(
        'id' => $address->getMember()->getLidnr(),
        'type' => $address->getType()
    )));
}
$form->setAttribute('method', 'post');

$form->setAttribute('role', 'form');
$form->setAttribute('class', 'form-horizontal');
?>
<?= $this->form()->openTag($form) ?>

<div class="form-group">
<?php
$element = $form->get('country');
$element->setAttribute('class', 'form-control');
$element->setAttribute('placeholder', $element->getLabel());
$element->setLabelAttributes(array(
    'class' => 'col-md-2 control-label'
));
?>
    <?= $this->formLabel($element) ?>
    <div class="col-md-10">
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>

<div class="form-group">
<?php
$element = $form->get('street');
$element->setAttribute('class', 'form-control');
$element->setAttribute('placeholder', $element->getLabel());
$element->setLabelAttributes(array(
    'class' => 'col-md-2 control-label'
));
?>
    <?= $this->formLabel($element) ?>
    <div class="col-md-10">
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>

<div class="form-group">
<?php
$element = $form->get('number');
$element->setAttribute('class', 'form-control');
$element->setAttribute('placeholder', $element->getLabel());
$element->setLabelAttributes(array(
    'class' => 'col-md-2 control-label'
));
?>
    <?= $this->formLabel($element) ?>
    <div class="col-md-10">
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>

<div class="form-group">
<?php
$element = $form->get('postalCode');
$element->setAttribute('class', 'form-control');
$element->setAttribute('placeholder', $element->getLabel());
$element->setLabelAttributes(array(
    'class' => 'col-md-2 control-label'
));
?>
    <?= $this->formLabel($element) ?>
    <div class="col-md-10">
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>

<div class="form-group">
<?php
$element = $form->get('city');
$element->setAttribute('class', 'form-control');
$element->setAttribute('placeholder', $element->getLabel());
$element->setLabelAttributes(array(
    'class' => 'col-md-2 control-label'
));
?>
    <?= $this->formLabel($element) ?>
    <div class="col-md-10">
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>

<div class="form-group">
<?php
$element = $form->get('phone');
$element->setAttribute('class', 'form-control');
$element->setAttribute('placeholder', $element->getLabel());
$element->setLabelAttributes(array(
    'class' => 'col-sm-2 control-label'
));
?>
    <?= $this->formLabel($element) ?>
    <div class="col-sm-10">
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php
        $submit = $form->get('submit');
        $submit->setLabel($submit->getValue());
        $submit->setAttribute('class', 'btn btn-primary');
        ?>
        <?= $this->formButton($submit) ?>
    </div>
</div>

<?= $this->form()->closeTag() ?>
<?php endif ?>
