<?php

declare(strict_types=1);

use Application\View\HelperTrait;
use Database\Model\Address as AddressModel;
use Laminas\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer|HelperTrait $this
 * @var AddressModel $address
 */
$type = $address->getType()->getName($this->plugin('translate')->getTranslator());
?>
<?php if (isset($add) && $add): ?>
    <h2>
        <?=
            sprintf(
                $this->translate('Add %s of %s'),
                $type,
                $this->escapeHtml($address->getMember()->getFullName()),
            )
        ?>
    </h2>
<?php else: ?>
    <h2>
        <?=
        sprintf(
            $this->translate('Update %s of %s'),
            $type,
            $this->escapeHtml($address->getMember()->getFullName()),
        )
        ?>
    </h2>
<?php endif ?>
<br>
<?php
$form->prepare();

if (isset($add) && $add) {
    $form->setAttribute('action', $this->url('member/show/add-address', array(
        'id' => $address->getMember()->getLidnr(),
        'type' => $address->getType()->value
    )));
} else {
    $form->setAttribute('action', $this->url('member/show/edit/address', array(
        'id' => $address->getMember()->getLidnr(),
        'type' => $address->getType()->value
    )));
}
$form->setAttribute('method', 'post');

$form->setAttribute('role', 'form');
$form->setAttribute('class', 'form-horizontal');
?>
<?= $this->form()->openTag($form) ?>

<div class="form-group">
<?php
$element = $form->get('country');
$element->setAttribute('class', 'form-control');
$element->setAttribute('placeholder', $element->getLabel());
$element->setValue($element->getValue());
$element->setLabelAttributes(array(
    'class' => 'col-md-2 control-label'
));
?>
    <?= $this->formLabel($element) ?>
    <div class="col-md-10">
        <?= $this->formSelect($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>

<div class="form-group">
<?php
$element = $form->get('street');
$element->setAttribute('class', 'form-control');
$element->setAttribute('placeholder', $element->getLabel());
$element->setLabelAttributes(array(
    'class' => 'col-md-2 control-label'
));
?>
    <?= $this->formLabel($element) ?>
    <div class="col-md-10">
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>

<div class="form-group">
<?php
$element = $form->get('number');
$element->setAttribute('class', 'form-control');
$element->setAttribute('placeholder', $element->getLabel());
$element->setLabelAttributes(array(
    'class' => 'col-md-2 control-label'
));
?>
    <?= $this->formLabel($element) ?>
    <div class="col-md-10">
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>

<div class="form-group">
<?php
$element = $form->get('postalCode');
$element->setAttribute('class', 'form-control');
$element->setAttribute('placeholder', $element->getLabel());
$element->setLabelAttributes(array(
    'class' => 'col-md-2 control-label'
));
?>
    <?= $this->formLabel($element) ?>
    <div class="col-md-10">
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>

<div class="form-group">
<?php
$element = $form->get('city');
$element->setAttribute('class', 'form-control');
$element->setAttribute('placeholder', $element->getLabel());
$element->setLabelAttributes(array(
    'class' => 'col-md-2 control-label'
));
?>
    <?= $this->formLabel($element) ?>
    <div class="col-md-10">
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>

<div class="form-group">
<?php
$element = $form->get('phone');
$element->setAttribute('class', 'form-control');
$element->setAttribute('placeholder', $element->getLabel());
$element->setLabelAttributes(array(
    'class' => 'col-sm-2 control-label'
));
?>
    <?= $this->formLabel($element) ?>
    <div class="col-sm-10">
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php
        $submit = $form->get('submit');
        $submit->setLabel($submit->getValue());
        $submit->setAttribute('class', 'btn btn-primary');
        ?>
        <?= $this->formButton($submit) ?>
    </div>
</div>

<?= $this->form()->closeTag() ?>
