<?php
use Database\Model\Member as MemberModel;

/** @var MemberModel $member */
?>
<h1 class="hidden-print">You have been confirmed as a member of GEWIS*
    <br/>
    <small>*If you are paying through SEPA Direct Debit, this approval is pending payment.</small></h1>
<p>
    Hi <?= $member->getFirstName() ?>,
</p>
<p>
    First of all, welcome, and thank you for your registration at GEWIS. From tomorrow on, your membership number will be <?= $member->getLidnr() ?>.
    You can use this membership number to log in to the website, where you can, among other things, subscribe to activities and look at photos from all the fun activities that you, together with the other members, have experienced.
    Below more information on all the functions of the website can be found, but first of all, you can register to the website using the following link: <a href="https://gewis.nl/user/register">gewis.nl/user/register</a>.
    Besides getting access to the website, you can also create a SudoSOS account, our system with which you will be able to buy drinks from the refrigerators and sweets you can find on the bar.
    You will need this account if you want to get a drink at the weekly social drink (usually called the “borrel”). To do this, first, log in to the GEWIS website using the account created above. After this, go to <a href="https://sudosos.gewis.nl">sudosos.gewis.nl</a>.
    When you log-in for the first time, you will have to read and accept the terms and conditions. After that, you can also set a pincode to use the point of sales on your own. 
</p>
<p>
    This rest of this email includes a bunch of very useful information about the following subjects:
</p>
<ul>
    <li>The GEWIS Website</li>
    <li>First Year Committees</li>
    <li>Ordering Books</li>
    <li>GEWIS on Social Media</li>
</ul>

<p>
    <b>The GEWIS website</b><br/>
    You might have noticed that GEWIS has its own website, but that it might not be as easy to access as you had hoped. Fear not, as this instruction mail should help you in no time! There are several different tabs in which you can find the following information:
</p>

<p>
    <b>Association</b><br/>
    If you have ever wondered who is actively helping the association by means of organizing activities, maintaining the servers, taking pictures, or publishing the association magazine: take a look at this page! All our committees, fraternities, sororities are listed here. Besides that, you can take a look if you forgot what your board looks like, or how you should sing the GEWIS song ;)
</p>

<p>
    <b>Companies</b><br/>
    At some point in the future, you could be looking for an internship or a graduation project from a company. At this header, you find a list of numerous companies offering vacancies for members of GEWIS.
</p>

<p>
    <b>Education</b><br/>
    Especially important when the exam weeks are coming near, here you can find all the old exams and summaries that GEWIS has available for the courses of Mathematics and Computer Science. You can also order your books from here, or submit a complaint about a teacher or a course.
</p>

<p>
    <b>Activities</b><br/>
    Besides studying, it is of course important to relax and enjoy your student life every once in a while. Here, you find an overview of all the activities GEWIS organizes: from weekends to lunch lectures, from external activities such as a conference to internal activities such as a bridge course. Don’t forget that most activities require you to subscribe in advance and that some activities are full quite fast!
</p>

<p>
    <b>Photos</b><br/>
    This kind of speaks for itself: at nearly every activity, members of GEFLITST (the photo committee of GEWIS) are busy taking pictures of our members. If you’re scrolling through the photos, don’t forget to tag the members you know in the picture! This week photos will be on the website already so check for them regularly :)
</p>

<p>
    <b>Members</b><br/>
    In this section, you can find plenty of different important shortcuts to other parts of the website. For example; you can look at an overview of your profile, look up another member if you can’t remember his name, see when the next General Members Meeting (GMM) is, access your SudoSOS account with which you can buy drinks and food (you have to agree to the terms of use before you can buy stuff), and many other shortcuts.
    Be sure to check it out!
    And of course, on our homepage, you can find numerous of these sections in short. A few of the upcoming events, the birthdays of today, the photo of the week, a poll, and of course random infima. So as you can see, there’s a lot to see and do at our website, so be sure to check it out every once in a while!
</p>

<p>
    <b>First Year Committees</b><br/>
    GEWIS has many committees and fraternities, we even set-up committees dedicated to first year students every year. As a first year committee you will be experiencing first hand what being an active GEWIS member is like! Together with your fellow first year students you will be fleshing out your own identity by creating your very own logo and custom clothing.
    You will also get the opportunity to organize some very fun activities for GEWIS and you can even be a part of workgroups with other first year committee members with whom you will be organizing parties, parent days or even a cantus!
    Furthermore, each semester a scoring competition is held to see which first year committee is the very best of them all.
    Collect points with your committee by passing courses, attending activities and much more!
</p>

<p>
    <b>Joining a first year committee</b></br/>
    In the first quartile, an information meeting will be held.  Here, first year committees from previous years will tell you about their fun experiences.
    A second meeting, the formation meeting, will be held to form the first year committees. Not to worry though, it's also possible to join an FYC later in the year.
    We hope to see you at these meetings!
</p>

<p>
    <b>Ordering books</b><br/>
    By becoming a GEWIS member you have the right to specialized discount! By navigating to <a href="https://gewis.nl/books">gewis.nl/books</a> you can find your study and see which books will be used for your courses.
</p>

<p>
    <b>GEWIS on Social Media</b><br/>
    Next to our own photo section on the website, you can also find us on social media. We have Instagram, Facebook & LinkedIn. Additionally, we have a weekly newsletter, for which you are automatically subscribed. You will get your first newsletter soon! 
</p>

<p>
    With kind regards,<br/>
    The board of GEWIS
</p>
