<?php

declare(strict_types=1);

use Application\View\HelperTrait;
use Laminas\View\Renderer\PhpRenderer;

/** @var PhpRenderer|HelperTrait $this */
?>
<h1>
    <?=
        sprintf(
            $this->translate('Extend Membership of %s'),
            $this->escapeHtml($member->getFullName()),
        )
    ?>
</h1>
<?php
$newExpiration = clone $member->getExpiration();
$year = (int) $newExpiration->format('Y') + 1;
$newExpiration->setDate($year, 7, 1);
?>
<p>
    <?=
        sprintf(
            $this->translate('Are you sure that you want to extend the membership of %s to %s (from %s)?'),
            $this->escapeHtml($member->getFullName()),
            $newExpiration->format('l j F Y'),
            $member->getExpiration()->format('l j F Y'),
        )
    ?>
</p>
<?php
$form->prepare();

$form->setAttribute('action', $this->url('member/show/edit/expiration', array('id' => $member->getLidnr())));
$form->setAttribute('method', 'post');

$form->setAttribute('role', 'form');
$form->setAttribute('class', 'form-horizontal');
?>
<?= $this->form()->openTag($form) ?>
    <div class="form-group">
        <?php
        $submit = $form->get('submit_yes');
        $submit->setLabel($this->translate('Yes'))
            ->setAttribute('class', 'btn btn-primary');
        ?>
        <?= $this->formButton($submit) ?>
        <?php
        $submit = $form->get('submit_no');
        $submit->setLabel($this->translate('No'))
            ->setAttribute('class', 'btn btn-default');
        ?>
        <?= $this->formButton($submit) ?>
    </div>
<?= $this->form()->closeTag() ?>
