<?php

declare(strict_types=1);

use Application\View\HelperTrait;
use Database\Form\MailingList as MailingListForm;
use Database\Model\{
    MailingList as MailingListModel,
    Member as MemberModel,
};
use Laminas\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer|HelperTrait $this
 * @var MailingListModel[] $lists
 * @var MemberModel $member
 * @var MailingListForm $form
 */
?>
<h1>
    <?=
        sprintf(
            $this->translate('Change Mailing List Subscriptions of %s'),
            $this->escapeHtml($member->getFullName()),
        )
    ?>
</h1>
<?php
$form->prepare();

$form->setAttribute('action', $this->url('member/show/edit/lists', array(
    'id' => $member->getLidnr()
)));
$form->setAttribute('method', 'post');

$form->setAttribute('role', 'form');
$form->setAttribute('class', 'form-horizontal');
?>
<?= $this->form()->openTag($form) ?>

<div class="form-group" style="margin-left: 0px; margin-right: 0px;">
<?php
$element = $form->get('lists');

// formMultiCheckbox($element) outputs all options on a single line
?>
<?php foreach ($element->getValueOptions() as $key => $value): ?>
    <div class="col-sm-12">
        <div class="checkbox">
            <label>
                <input type="checkbox" name="<?= $element->getName() ?>[]" value="<?= $value['value'] ?>" <?= $value['selected'] ? 'checked ' : '' ?> <?= $value['disabled'] ? 'disabled ' : '' ?>>
                <?= $value['label'] ?>
            </label>
            <?= $value['disabled'] ? '<input type="hidden" name="' . $element->getName() . '[]" value="' . $value['value'] . '" />' : '' ?>
            <?= $this->formElementErrors($element) ?>
        </div>
    </div>
<?php endforeach ?>
</div>

<div class="form-group">
    <div class="col-sm-12">
        <?php
        $submit = $form->get('submit');
        $submit->setLabel($submit->getValue());
        $submit->setAttribute('class', 'btn btn-primary');
        ?>
        <?= $this->formButton($submit) ?>
    </div>
</div>
<?= $this->form()->closeTag() ?>
