<?php

declare(strict_types=1);

use Application\Model\Enums\PostalRegions;
use Application\View\HelperTrait;
use Database\Model\Member as MemberModel;
use Laminas\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer|HelperTrait $this
 * @var MemberModel $member
 */
?>
<?php if (isset($form)): ?>
<?php
$this->headTitle()->prepend("GEWIS Renew Membership");

$form->prepare();

$form->setAttribute('method', 'post');

$form->setAttribute('role', 'form');
$form->setAttribute('id', 'form-subscribe');
?>
<?= $this->form()->openTag($form) ?>

<div class="row">
<div class="col-md-12">
        <section class="content-section">
            <h1><?= $this->translate('Graduate renewal') ?></h1>
            <p class="lead">
                According to our data it is time to renew your status as a graduate of GEWIS.
                To make sure we have up-to-date information on how to contact you, please review your details below.<br/>
                If you do not want to become or remain a graduate, you do not have to do anything. It will simply expire on the indicated date.
            </p>
            <p>
                If you are currently studying at TU/e, please do <u>not</u> fill in this form, but instead inform the secretary of this. 
                If you want GEWIS to automatically renew your membership, please send your TU/e username.<br/>
            </p>
        </section>
    </div>
</div>

<div class="row">

<?php if (count($form->getMessages()) > 0): ?>
<div class="alert alert-danger" role="alert">
<?= $this->translate('Er zijn velden fout of niet ingevuld. Los dit op en stuur opnieuw in!') ?>
</div>
<?php endif ?>

<div class="col-md-12">
    <div class="row">
        <div class="col-md-12">
            <h3><?= $this->translate('Personal details') ?></h3>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
            <?php
            $element = $form->get('initials');
            $element->setAttribute('class', 'form-control validate-initials');
            $element->setLabelAttributes(array(
                'class' => 'control-label'
            ));
            ?>
            <div class="form-group<?= $this->bootstrapElementError($element) ?>">
                <?= $this->formLabel($element) ?>
                <?= $this->formInput($element) ?>
                <?= $this->formElementErrors($element) ?>
            </div>
        </div>
        <div class="col-md-4">
            <?php
            $element = $form->get('firstName');
            $element->setAttribute('class', 'form-control');
            $element->setLabelAttributes(array(
                'class' => 'control-label'
            ));
            ?>
            <div class="form-group<?= $this->bootstrapElementError($element) ?>">
                <?= $this->formLabel($element) ?>
                <?= $this->formInput($element) ?>
                <?= $this->formElementErrors($element) ?>
            </div>
        </div>
        <div class="col-md-2">
            <?php
            $element = $form->get('middleName');
            $element->setAttribute('class', 'form-control');
            $element->setLabelAttributes(array(
                'class' => 'control-label'
            ));
            ?>
            <div class="form-group<?= $this->bootstrapElementError($element) ?>">
                <?= $this->formLabel($element) ?>
                <?= $this->formInput($element) ?>
                <?= $this->formElementErrors($element) ?>
            </div>
        </div>
        <div class="col-md-4">
            <?php
            $element = $form->get('lastName');
            $element->setAttribute('class', 'form-control');
            $element->setLabelAttributes(array(
                'class' => 'control-label'
            ));
            ?>
            <div class="form-group<?= $this->bootstrapElementError($element) ?>">
                <?= $this->formLabel($element) ?>
                <?= $this->formInput($element) ?>
                <?= $this->formElementErrors($element) ?>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <?php
            $element = $form->get('email');
            $element->setAttribute('class', 'form-control');
            $element->setAttribute('placeholder', $element->getLabel());
            $element->setLabelAttributes(array(
                'class' => 'control-label label-required'
            ));
            ?>
            <div class="form-group<?= $this->bootstrapElementError($element) ?>">
                <?= $this->formLabel($element) ?>
                <?= $this->formInput($element) ?>
                <?= $this->formElementErrors($element) ?>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <hr>
            <h3><?= $this->translate('Supremum') ?></h3>
            <p>
                <?= $this->translate('As a graduate, you can choose to receive the physical Supremum magazine.') ?>
                <?= sprintf(
                    $this->translate('You can always read the online Supremum on %s.'),
                    '<a target="_blank" href="https://supremum.gewis.nl">supremum.gewis.nl</a>'
                    ) ?>
            </p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <?php
                $element = $form->get('supremum');
                ?>
                <div class="checkbox">
                    <label>
                        <?= $this->formCheckbox($element) ?>
                        <?= $element->getLabel() ?>
                    </label>
                    <?= $this->formElementErrors($element) ?>
                </div>
            </div>
        </div>
    </div>
    
    <div class="row">
        <div class="col-md-12">
            <hr>
            <h3><?= $this->translate('Agreement') ?></h3>
            <a target="_blank" href="https://gewis.nl/vereniging/statuten/">
                <?= $this->translate('Articles of Association, Internal Regulations and privacy statement') ?>
            </a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <?php
            $element = $form->get('privacy');
            ?>
            <div class="form-group<?= $this->bootstrapElementError($element) ?>">
                <div class="checkbox">
                    <label>
                        <?= $this->formCheckbox($element) ?>
                        <?= $element->getLabel() ?>
                    </label>
                    <?= $this->formElementErrors($element) ?>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <?php
            $element = $form->get('agreed');
            ?>
            <div class="form-group<?= $this->bootstrapElementError($element) ?>">
                <div class="checkbox">
                    <label>
                        <?= $this->formCheckbox($element) ?>
                        <?= $element->getLabel() ?>
                    </label>
                    <?= $this->formElementErrors($element) ?>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <?php
            $element = $form->get('newExpiration');
            $element->setAttribute('class', 'form-control');
            $element->setAttribute('placeholder', $element->getLabel());
            $element->setLabelAttributes(array(
                'class' => 'control-label'
            ));
            ?>
            <div class="form-group<?= $this->bootstrapElementError($element) ?>">
                <?= $this->formLabel($element) ?>
                <?= $this->formInput($element) ?>
                <?= $this->formElementErrors($element) ?>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
            <?php
            $submit = $form->get('submit');
            $submit->setLabel($submit->getValue());
            $submit->setAttribute('class', 'btn btn-primary');
            $submit->setAttribute('id', 'subscription-submit');
            ?>
            <div class="form-group">
                <?= $this->formButton($submit) ?>
            </div>
        </div>
    </div>
</div>
<?= $this->form()->closeTag() ?>
</div>

<script>
    window.addEventListener('load', (event) => {
        validator = new InputValidator(document.getElementById("<?= $form->getAttribute('id'); ?>"));
    });
</script>

<?php else: ?>
    <h1 class="hidden-print"><?= $this->translate('Gefeliciteerd! Je bent geregistreed als lid van Studievereniging GEWIS') ?>
        <br>
        <small><?= $this->translate('Na betaling van je lidmaatschapsgeld ben je GEWIS-lid!') ?></small></h1>
<!--Use the code below to add some nice pop-up or promotion to the subscription email.-->
<!--    <div class="alert alert-info">-->
<!--        Liked the introduction week? GEWIS also organizes a follow-up day after the introduction week: the FLUP!-->
<!--        During the FLUP you get to know even more fellow students and GEWIS as an association through fun activities and a BBQ.-->
<!--        This event will take place on Saturday, September 12. Tickets can be bought on <a href="https://gewis.nl/FLUP">https://gewis.nl/FLUP</a> for &euro;3,-.-->
<!--    </div>-->
    <h2 class="hidden-print">Hier nogmaals je gegevens ter controle</h2>
<div class="row">
<div class="col-md-6">
    <h1><?= $member->getFullName() ?></h1>
    <table class="table table-bordered">
        <tr>
            <th><?= $this->translate('Voorletters') ?></th>
            <td><?= $member->getInitials() ?></td>
        </tr>
        <tr>
            <th><?= $this->translate('Voornaam') ?></th>
            <td><?= $member->getFirstName() ?></td>
        </tr>
        <tr>
            <th><?= $this->translate('Tussenvoegsels') ?></th>
            <td><?= $member->getMiddleName() ?></td>
        </tr>
        <tr>
            <th><?= $this->translate('Achternaam') ?></th>
            <td><?= $member->getLastName() ?></td>
        </tr>
        <tr>
            <th><?= $this->translate('TU/e-gebruikersnaam') ?></th>
            <td>
                <?= (null === $member->getTueUsername()) ? $this->translate('Onbekend') : $member->getTueUsername() ?>
            </td>
        </tr>
        <tr>
            <th><?= $this->translate('Study') ?></th>
            <td><?= $member->getStudy() ?></td>
        </tr>
        <tr>
            <th><?= $this->translate('E-mail Address') ?></th>
            <td><a href="mailto:<?= $member->getEmail() ?>"><?= $member->getEmail() ?></a></td>
        </tr>
        <tr>
            <th><?= $this->translate('Birthdate') ?></th>
            <td><?= $member->getBirth()->format('l j F Y') ?></td>
        </tr>
        <tr>
            <th><?= $this->translate('IBAN') ?></th>
            <td><?= $member->getIban(true) ?? $this->translate('Onbekend') ?></td>
        </tr>
    </table>
</div>
<div class="col-md-6">
<h3><?= $this->translate('Addresses') ?></h3>
<?php foreach ($member->getAddresses() as $address): ?>
    <h4><?= $address->getType()->getName($this->plugin('translate')->getTranslator()) ?></h4>
    <table class="table table-bordered">
        <tr>
            <th><?= $this->translate('Postal Region') ?></th>
            <td><?= $address->getCountry()->value ?></td>
        </tr>
        <tr>
            <th><?= $this->translate('Straat en huisnummer') ?></th>
            <td><?= $address->getStreet() ?> <?= $address->getNumber() ?></td>
        </tr>
        <tr>
            <th><?= $this->translate('Woonplaats en Postcode') ?></th>
            <td><?= $address->getCity() ?> <?= $address->getPostalCode() ?></td>
        </tr>
        <tr>
            <th><?= $this->translate('Telefoonnummer') ?></th>
            <td><?= $address->getPhone() ?></td>
        </tr>
    </table>
<?php endforeach ?>
<h3><?= $this->translate('Aangemelde mailing lists') ?></h3>
<ul>
<?php foreach ($member->getLists() as $list): ?>
    <li><?= $list->getName() ?></li>
<?php endforeach ?>
</ul>

<?php if (null !== $member->getIban()): ?>
<p>
    <?= $this->translate('Incassant-ID') ?>: NL44ZZZ402377870000
</p>

<p>
    <?= $this->translate('Kenmerk van de machtiging') ?>: <?= $member->getMandateCharacteristic() ?>
</p>
<div class="visible-print">
<table class="table table-bordered">
    <tr>
        <td>
            <?php if($address->getCountry() === PostalRegions::Netherlands): ?>
                Door ondertekening van dit formulier geeft u (A) Gemeenschap van Wiskunde en Informatica Studenten (GEWIS)
                toestemming om eenmalig een incasso-opdracht te sturen naar uw bank om een bedrag van &euro;15,-,
                geheten vijftien euro, van uw rekening af te schrijven en (B) aan uw bank om eenmalig een bedrag van
                uw rekening af te schrijven overeenkomstig de opdracht van GEWIS.
                <br/>
                Als u het niet eens bent met deze afschrijving kunt u deze laten terugboeken. Neem hiervoor binnen <b>acht
                weken</b> na afschrijving contact op met uw bank. Vraag uw bank naar de voorwaarden.
            <?php else: ?>
                By signing this mandate form, you (A) authorise Gemeenschap van Wiskunde en Informatica Studenten (GEWIS)
                to send instructions to your bank to debit your account with &euro;15,-, fifteen euros, and (B) your bank
                to debit your account in accordance with the instructions from Gemeenschap van Wiskunde en Informatica Studenten (GEWIS).
                <br/>
                As part of your rights, you are entitled to a refund from your bank under the terms and conditions of
                your agreement with your bank. A refund must be claimed within <b>8 weeks</b> starting from the date on
                which your account was debited.
            <?php endif ?>
        </td>
    </tr>
    <tr>
        <th><?= $this->translate('Plaats en datum van ondertekening') ?><br><?= $member->getSignatureLocation() ?><br><?= $member->getChangedOn()->format('F j, Y') ?><br><br><br><br></th>
        <th><?= $this->translate('Handtekening') ?><br><img src="<?= $this->fileUrl($member->getSignature()) ?>" height="100" width="300" /><br><br><br><br><br></th>
    </tr>
</table>
</div>
<?php endif; ?>
</div>
</div>
<?php endif ?>
