<?php

declare(strict_types=1);

use Application\View\HelperTrait;
use Application\Model\Enums\{
    AddressTypes,
    MembershipTypes,
};
use Database\Model\Member as MemberModel;
use Laminas\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer|HelperTrait $this
 * @var MemberModel $member
 * @var bool $hasCorrectInstallations
 */

?>
<div class="row">
    <div class="col-md-12">
        <h1><?= $member->getFullName() ?></h1>
    </div>
<div class="col-md-6">
    <table class="table table-bordered">
        <tr>
            <th><?= $this->translate('Member Number') ?></th>
            <td><?= $member->getLidnr() ?></td>
        </tr>
        <tr>
            <th><?= $this->translate('Initial(s)') ?></th>
            <td><?= $member->getInitials() ?></td>
        </tr>
        <tr>
            <th><?= $this->translate('First Name') ?></th>
            <td><?= $member->getFirstName() ?></td>
        </tr>
        <tr>
            <th><?= $this->translate('Last Name Prepositional Particle') ?></th>
            <td><?= $member->getMiddleName() ?></td>
        </tr>
        <tr>
            <th><?= $this->translate('Last Name') ?></th>
            <td><?= $member->getLastName() ?></td>
        </tr>
        <tr>
            <th><?= $this->translate('TU/e-username') ?></th>
            <td>
                <?php if (null === $member->getTueUsername()): ?>
                    <?= $this->translate('Unknown') ?>
                <?php else: ?>
                    <a href="<?= $this->url('member/tuelookup') ?>?u=<?= $member->getTueUsername() ?>">
                        <?= $member->getTueUsername() ?>
                    </a>
                <?php
                endif;
                ?>
            </td>
        </tr>
        <tr>
            <th><?= $this->translate('E-mail Address') ?></th>
            <?php if (null !== ($emailAddress = $member->getEmail())): ?>
                <td><a href="mailto:<?= $emailAddress ?>"><?= $emailAddress ?></a></td>
            <?php else: ?>
                <td><?= $this->translate('Unknown') ?></td>
            <?php endif; ?>
        </tr>
        <tr>
            <th><?= $this->translate('Birthdate') ?></th>
            <td><?= $member->getBirth()->format('l j F Y') ?></td>
        </tr>
        <tr>
            <th><?= $this->translate('Generation') ?></th>
            <td><?= $member->getGeneration() ?></td>
        </tr>
        <tr>
            <th><?= $this->translate('Paid (Amount)') ?></th>
            <td><?= $member->getPaid() ?></td>
        </tr>
        <tr>
            <th><?= $this->translate('Membership Type') ?></th>
            <td>
                <?= $member->getType()->getName($this->plugin('translate')->getTranslator()) ?>
                <a href="<?= $this->url('member/show/edit/membership', array(
                    'id' => $member->getLidnr()
                )) ?>" class="btn btn-primary btn-xs">
                    <?= $this->translate('Update / Renew') ?>
                </a>
            </td>
        </tr>
        <tr>
            <th><?= $this->translate('Study') ?></th>
            <td><?= $member->getStudy() ?></td>
        </tr>
        <tr>
            <th><?= $this->translate('Last Update to Membership') ?></th>
            <td><?= $member->getChangedOn()->format('l j F Y') ?></td>
        </tr>
        <tr>
            <th><?= $this->translate('Membership Ends On (Expires On)') ?></th>
            <td>
                <?= sprintf('%s (%s)',
                    (null !== $member->getMembershipEndsOn()) ? $member->getMembershipEndsOn()->format('l j F Y') : $this->translate('N/A'),
                    $member->getExpiration()->format('l j F Y')
                )?>
                <?php if (MembershipTypes::External === $member->getType() || MembershipTypes::Graduate === $member->getType()): ?>
                    <a href="<?= $this->url('member/show/edit/expiration', ['id' => $member->getLidnr()]) ?>" class="btn btn-primary btn-xs"><?= $this->translate('Extend') ?></a>
                <?php endif; ?>
            </td>
        </tr>
        <tr>
            <th><?= $this->translate('Wants to Receive Supremum') ?></th>
            <td>
                <?= $member->getSupremum() ?>
                <a href="<?= $this->url('member/show/supremum/optin', ['id' => $member->getLidnr()]) ?>" class="btn btn-primary btn-xs">Optin</a>
                <a href="<?= $this->url('member/show/supremum/optout', ['id' => $member->getLidnr()]) ?>" class="btn btn-primary btn-xs">Optout</a>
                <a href="<?= $this->url('member/show/supremum', ['id' => $member->getLidnr()]) ?>" class="btn btn-primary btn-xs">Reset</a>
            </td>
            </tr>
        </table>
        <a href="<?= $this->url('member/show/edit', array(
            'id' => $member->getLidnr()
        )) ?>" class="btn btn-primary"><?= $this->translate('Change Data') ?></a>
        <a href="<?= $this->url('member/show/delete', array(
            'id' => $member->getLidnr()
        )) ?>" class="btn btn-danger"><?= $this->translate('Delete Member') ?></a>
    <h3><?= $this->translate('Membership of Committees and Fraternities') ?></h3>
    <?php if ($hasCorrectInstallations): ?>
        <ul>
            <?php foreach ($member->getInstallations() as $install): ?>
                <li>
                    <a href="<?= $this->url('organ/view', array(
                        'type' => $install->getFoundation()->getDecision()->getMeeting()->getType()->value,
                        'number' => $install->getFoundation()->getDecision()->getMeeting()->getNumber(),
                        'point' => $install->getFoundation()->getDecision()->getPoint(),
                        'decision' => $install->getFoundation()->getDecision()->getNumber(),
                        'sequence' => $install->getFoundation()->getSequence(),
                    )) ?>">
                        <?= $install->getFoundation()->getAbbr() ?>
                    </a>
                </li>
            <?php endforeach; ?>
        </ul>
    <?php else: ?>
        <p><?= $this->translate('This member is not installed in an organ.') ?></p>
    <?php endif; ?>
</div>
<div class="col-md-6">
<h3><?= $this->translate('Addresses') ?></h3>
<?php $addresses = array() ?>
<?php foreach ($member->getAddresses() as $address): ?>
<?php $addresses[$address->getType()->value] = $address ?>
<h4><?= $address->getType()->getName($this->plugin('translate')->getTranslator()) ?> <a href="<?= $this->url('member/show/edit/address', array(
    'id' => $member->getLidnr(),
    'type' => $address->getType()->value
)) ?>" class="btn btn-primary btn-sm"><?= $this->translate('Change') ?></a> <a href="<?= $this->url('member/show/remove-address', array(
    'id' => $member->getLidnr(),
    'type' => $address->getType()->value
)) ?>" class="btn btn-danger btn-sm"><span class="glyphicon glyphicon-remove"></span> <?= $this->translate('Delete') ?></a></h4>
<table class="table table-bordered">
    <tr>
        <th><?= $this->translate('Postal Region') ?></th>
        <td><?= $address->getCountry()->value ?></td>
    </tr>
    <tr>
        <th><?= $this->translate('Street and House Number') ?></th>
        <td><?= $address->getStreet() ?> <?= $address->getNumber() ?></td>
    </tr>
    <tr>
        <th><?= $this->translate('City and Postal Code') ?></th>
        <td><?= $address->getCity() ?> <?= $address->getPostalCode() ?></td>
    </tr>
    <tr>
        <th><?= $this->translate('Phone Number') ?></th>
        <td><?= $address->getPhone() ?></td>
    </tr>
</table>
<?php endforeach ?>
<?php if (!isset($addresses[AddressTypes::Home->value])): ?>
    <a href="<?= $this->url('member/show/add-address', array(
        'id' => $member->getLidnr(),
        'type' => AddressTypes::Home->value
    )) ?>" class="btn btn-success">
        <span class="glyphicon glyphicon-plus"></span> <?= $this->translate('Add Home Address') ?>
    </a>
<?php endif ?>
<?php if (!isset($addresses[AddressTypes::Student->value])): ?>
    <a href="<?= $this->url('member/show/add-address', array(
        'id' => $member->getLidnr(),
        'type' => AddressTypes::Student->value
    )) ?>" class="btn btn-success">
        <span class="glyphicon glyphicon-plus"></span> <?= $this->translate('Add Student Address') ?>
    </a>
<?php endif ?>
<?php if (!isset($addresses[AddressTypes::Mail->value])): ?>
    <a href="<?= $this->url('member/show/add-address', array(
        'id' => $member->getLidnr(),
        'type' => AddressTypes::Mail->value
    )) ?>" class="btn btn-success">
        <span class="glyphicon glyphicon-plus"></span> <?= $this->translate('Add Mail Address') ?>
    </a>
<?php endif ?>
</div>

<div class="col-md-6">
<h3><?= $this->translate('Mailing List Subscriptions') ?></h3>
<ul>
<?php foreach ($member->getMailingListMemberships() as $list): ?>
    <li><?= $list->getName() ?></li>
<?php endforeach ?>
</ul>
<a href="<?= $this->url('member/show/edit/lists', array(
    'id' => $member->getLidnr()
)) ?>" class="btn btn-primary"><?= $this->translate('Change Mailing List Subscriptions') ?></a>
</div>

<div class="col-md-6">
<h3><?= $this->translate('Notes') ?></h3>
<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th scope="col" style="width: 20%;">Date</th>
            <th scope="col" style="width: 65%;">Entry</th>
            <th scope="col" style="width: 15%;">User</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($member->getAuditEntries() as $entry): ?>
            <tr>
                <td><?= $entry->getUpdatedAt()->format('j M Y H:i') ?></td>
                <td><?= sprintf($this->translate($entry->getStringPlain()['bodyFormatted']), ... $entry->getStringPlain()['arguments']) ?></td>
                <td><?= $entry->getUserName() ?></td>
            </tr>
        <?php endforeach;
        if (0 === count($member->getAuditEntries())): ?>
            <tr><td colspan="3"><?= $this->translate('There are no notes for this member.') ?></td></tr>
        <?php endif; ?>
        <tr>
            <?php
                $noteForm->prepare();
                $noteForm->setAttribute('method', 'post');
                $noteForm->setAttribute('role', 'form');
                $noteForm->setAttribute('class', 'form-vertical');

                $submit = $noteForm->get('submit');
                $submit->setAttribute('class', 'btn btn-success');
                $submit->setAttribute('value', 'new-auditentry');

                $noteElement = $noteForm->get('note');
                $noteElement->setAttribute('class', 'form-control');
                $noteElement->setAttribute('placeholder', $noteElement->getLabel());
            ?>
            <?= $this->form()->openTag($noteForm) ?>
            <td colspan="2">
                <?= $this->formInput($noteElement) ?>
                <?= $this->formElementErrors($noteElement) ?>
            </td>
            <td>
                <?= $this->formButton($submit) ?>
            </td>
            <?= $this->form()->closeTag() ?>
        </tr>
    </tbody>
</table>
</div>
</div>
