<?php

use Application\Model\Enums\{
    AddressTypes,
    MembershipTypes,
};
use Database\Model\Member as MemberModel;

/** @var MemberModel $member */
/** @var bool $hasCorrectInstallations */

?>
<div class="row">
<div class="col-md-6">
    <h1><?= $member->getFullName() ?></h1>
    <table class="table table-bordered">
        <tr>
            <th>Lidnummer</th>
            <td><?= $member->getLidnr() ?></td>
        </tr>
        <tr>
            <th>Voorletters</th>
            <td><?= $member->getInitials() ?></td>
        </tr>
        <tr>
            <th>Voornaam</th>
            <td><?= $member->getFirstName() ?></td>
        </tr>
        <tr>
            <th>Tussenvoegsels</th>
            <td><?= $member->getMiddleName() ?></td>
        </tr>
        <tr>
            <th>Achternaam</th>
            <td><?= $member->getLastName() ?></td>
        </tr>
        <tr>
            <th>TU/e-gebruikersnaam</th>
            <td>
                <?php
                if (null === $member->getTueUsername()):
                ?>
                    Onbekend
                <?php
                else:
                ?>
                    <a href="<?= $this->url(
                        'member/tuelookup',
                        ['tueUsername' => $member->getTueUsername()],
                    ) ?> ">
                        <?= $member->getTueUsername() ?>
                    </a>
                <?php
                endif;
                ?>
            </td>
        </tr>
        <tr>
            <th>Email</th>
            <?php if (null !== ($emailAddress = $member->getEmail())): ?>
                <td><a href="mailto:<?= $emailAddress ?>"><?= $emailAddress ?></a></td>
            <?php else: ?>
                <td>Onbekend</td>
            <?php endif; ?>
        </tr>
        <tr>
            <th>Geboortedatum</th>
            <td><?= $member->getBirth()->format('l j F Y') ?></td>
        </tr>
        <tr>
            <th>Generatie</th>
            <td><?= $member->getGeneration() ?></td>
        </tr>
        <tr>
            <th>Betaald (hoe veel)</th>
            <td><?= $member->getPaid() ?></td>
        </tr>
        <tr>
            <th>Type lid</th>
            <td><?php
switch ($member->getType()) {
    case MembershipTypes::Ordinary:
        echo 'Gewoon';
        break;
    case MembershipTypes::External:
        echo 'Extern';
        break;
    case MembershipTypes::Graduate:
        echo 'Afgestudeerde';
        break;
    case MembershipTypes::Honorary:
        echo 'Erelid';
        break;
}
?> <a href="<?= $this->url('member/show/edit/membership', array(
    'id' => $member->getLidnr()
)) ?>" class="btn btn-primary btn-xs">Wijzig / vernieuw</a></td>
        </tr>
        <tr>
            <th>Laatste wijziging lidmaatshap</th>
            <td><?= $member->getChangedOn()->format('l j F Y') ?></td>
        </tr>
        <tr>
            <th>Verloopdatum lidmaatschap (hernieuwt op)</th>
            <td>
                <?= sprintf('%s (%s)',
                    (null !== $member->getMembershipEndsOn()) ? $member->getMembershipEndsOn()->format('l j F Y') : 'N.v.t.',
                    $member->getExpiration()->format('l j F Y')
                )?>
                <?php if (MembershipTypes::External === $member->getType() || MembershipTypes::Graduate === $member->getType()): ?>
                    <a href="<?= $this->url('member/show/edit/expiration', ['id' => $member->getLidnr()]) ?>" class="btn btn-primary btn-xs">Verleng</a>
                <?php endif; ?>
            </td>
        </tr>
        <tr>
            <th>Wil supremum ontvangen</th>
            <td>
                <?= $member->getSupremum() ?>
                <a href="<?= $this->url('member/show/supremum/optin', ['id' => $member->getLidnr()]) ?>" class="btn btn-primary btn-xs">Optin</a>
                <a href="<?= $this->url('member/show/supremum/optout', ['id' => $member->getLidnr()]) ?>" class="btn btn-primary btn-xs">Optout</a>
                <a href="<?= $this->url('member/show/supremum', ['id' => $member->getLidnr()]) ?>" class="btn btn-primary btn-xs">Reset</a>
            </td>
            </tr>
        </table>
        <a href="<?= $this->url('member/show/edit', array(
            'id' => $member->getLidnr()
        )) ?>" class="btn btn-primary">Wijzig gegevens</a>
        <a href="<?= $this->url('member/show/delete', array(
            'id' => $member->getLidnr()
        )) ?>" class="btn btn-danger">Verwijder lid</a>
    <h3>Lidmaatschap commissies en disputen</h3>
    <?php if ($hasCorrectInstallations): ?>
        <ul>
            <?php foreach ($member->getInstallations() as $install): ?>
                <li>
                    <a href="<?= $this->url('organ/view', array(
                        'type' => $install->getFoundation()->getDecision()->getMeeting()->getType()->value,
                        'number' => $install->getFoundation()->getDecision()->getMeeting()->getNumber(),
                        'point' => $install->getFoundation()->getDecision()->getPoint(),
                        'decision' => $install->getFoundation()->getDecision()->getNumber(),
                        'subdecision' => $install->getFoundation()->getNumber()
                    )) ?>">
                        <?= $install->getFoundation()->getAbbr() ?>
                    </a>
                </li>
            <?php endforeach; ?>
        </ul>
    <?php else: ?>
        <p><?= $this->translate('This member is not installed in an organ.') ?></p>
    <?php endif; ?>
</div>
<div class="col-md-6">
<h3>Adressen</h3>
<?php $addresses = array() ?>
<?php foreach ($member->getAddresses() as $address): ?>
<?php $addresses[$address->getType()->value] = $address ?>
<h4><?php
switch ($address->getType()) {
    case AddressTypes::Home:
        echo 'Thuisadres (ouders)';
        break;
    case AddressTypes::Student:
        echo 'Kameradres';
        break;
    case AddressTypes::Mail:
        echo 'Postadres';
        break;
}
?> <a href="<?= $this->url('member/show/edit/address', array(
    'id' => $member->getLidnr(),
    'type' => $address->getType()->value
)) ?>" class="btn btn-primary btn-sm">Wijzig</a> <a href="<?= $this->url('member/show/remove-address', array(
    'id' => $member->getLidnr(),
    'type' => $address->getType()->value
)) ?>" class="btn btn-danger btn-sm"><span class="glyphicon glyphicon-remove"></span> Verwijder</a></h4>
<table class="table table-bordered">
    <tr>
        <th>Land</th>
        <td><?= $address->getCountry() ?></td>
    </tr>
    <tr>
        <th>Straat en huisnummer</th>
        <td><?= $address->getStreet() ?> <?= $address->getNumber() ?></td>
    </tr>
    <tr>
        <th>Woonplaats en Postcode</th>
        <td><?= $address->getCity() ?> <?= $address->getPostalCode() ?></td>
    </tr>
    <tr>
        <th>Telefoonnummer</th>
        <td><?= $address->getPhone() ?></td>
    </tr>
</table>
<?php endforeach ?>
<?php if (!isset($addresses[AddressTypes::Home->value])): ?>
<a href="<?= $this->url('member/show/add-address', array(
    'id' => $member->getLidnr(),
    'type' => AddressTypes::Home->value
)) ?>" class="btn btn-success"><span class="glyphicon glyphicon-plus"></span> Voeg thuisadres toe</a>
<?php endif ?>
<?php if (!isset($addresses[AddressTypes::Student->value])): ?>
<a href="<?= $this->url('member/show/add-address', array(
    'id' => $member->getLidnr(),
    'type' => AddressTypes::Student->value
)) ?>" class="btn btn-success"><span class="glyphicon glyphicon-plus"></span> Voeg kameradres toe</a>
<?php endif ?>
<?php if (!isset($addresses[AddressTypes::Mail->value])): ?>
<a href="<?= $this->url('member/show/add-address', array(
    'id' => $member->getLidnr(),
    'type' => AddressTypes::Mail->value
)) ?>" class="btn btn-success"><span class="glyphicon glyphicon-plus"></span> Voeg postadres toe</a>
<?php endif ?>
<h3>Aangemelde mailing lists</h3>
<ul>
<?php foreach ($member->getLists() as $list): ?>
    <li><?= $list->getName() ?></li>
<?php endforeach ?>
</ul>
<a href="<?= $this->url('member/show/edit/lists', array(
    'id' => $member->getLidnr()
)) ?>" class="btn btn-primary">Wijzig aanmeldingen mailing lists</a>
</div>
</div>
