<?php

declare(strict_types=1);

use Application\Model\Enums\PostalRegions;
use Application\View\HelperTrait;
use Database\Model\Member as MemberModel;
use Laminas\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer|HelperTrait $this
 * @var MemberModel $member
 */
?>
<?php
$this->headTitle()->prepend("GEWIS Enrollment");

$this->inlineScript()->appendFile($this->basePath() . '/js/inputvalidator.min.js');

$form->prepare();

$form->setAttribute('action', $this->url('member/subscribe'));
$form->setAttribute('method', 'post');

$form->setAttribute('role', 'form');
$form->setAttribute('id', 'form-subscribe');
?>
<?= $this->form()->openTag($form) ?>

<div class="jumbotron">
    <div class="row">
        <div class="col-md-3">
            <img src="<?= $this->basePath() ?>/img/gewis.png" />
        </div>
        <div class="col-md-9">
            <h1>
                <span class="gewis-red">GEWIS</span> <?= $this->translate('Inschrijving') ?>
            </h1>
            <p>
                <?= $this->translate('Welkom! Met dit formulier kun je je inschrijven voor een
lidmaatschap van GEWIS. Het lidmaatschap is geldig zo lang je studeert en kost
eenmalig 15 euro.') ?>
            </p>
            <p>
                <?= $this->translate('If you have any questions feel free to contact') ?> <a href="mailto:board@gewis.nl">board@gewis.nl</a>.
            </p>
        </div>
    </div>
</div>

<div class="row">

<?php if (count($form->getMessages()) > 0): ?>
<div class="alert alert-danger" role="alert">
<?= $this->translate('Some of the entered information appears to be missing or incorrect. Please check your data and submit again.') ?>
</div>
<?php endif ?>

<div class="col-md-12">
    <div class="row">
        <div class="col-md-12">
            <h3><?= $this->translate('Personal details') ?></h3>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
            <?php
            $element = $form->get('initials');
            $element->setAttribute('class', 'form-control validate-initials');
            $element->setAttribute('placeholder', $element->getLabel());
            $element->setLabelAttributes(array(
                'class' => 'control-label label-required'
            ));
            ?>
            <div class="form-group<?= $this->bootstrapElementError($element) ?>">
                <?= $this->formLabel($element) ?>
                <?= $this->formInput($element) ?>
                <?= $this->formElementErrors($element) ?>
            </div>
        </div>
        <div class="col-md-4">
            <?php
            $element = $form->get('firstName');
            $element->setAttribute('class', 'form-control');
            $element->setAttribute('placeholder', $element->getLabel());
            $element->setLabelAttributes(array(
                'class' => 'control-label label-required'
            ));
            ?>
            <div class="form-group<?= $this->bootstrapElementError($element) ?>">
                <?= $this->formLabel($element) ?>
                <?= $this->formInput($element) ?>
                <?= $this->formElementErrors($element) ?>
            </div>
        </div>
        <div class="col-md-2">
            <?php
            $element = $form->get('middleName');
            $element->setAttribute('class', 'form-control');
            $element->setAttribute('placeholder', $element->getLabel());
            $element->setLabelAttributes(array(
                'class' => 'control-label'
            ));
            ?>
            <div class="form-group<?= $this->bootstrapElementError($element) ?>">
                <?= $this->formLabel($element) ?>
                <?= $this->formInput($element) ?>
                <?= $this->formElementErrors($element) ?>
            </div>
        </div>
        <div class="col-md-4">
            <?php
            $element = $form->get('lastName');
            $element->setAttribute('class', 'form-control');
            $element->setAttribute('placeholder', $element->getLabel());
            $element->setLabelAttributes(array(
                'class' => 'control-label label-required'
            ));
            ?>
            <div class="form-group<?= $this->bootstrapElementError($element) ?>">
                <?= $this->formLabel($element) ?>
                <?= $this->formInput($element) ?>
                <?= $this->formElementErrors($element) ?>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8">
            <?php
            $element = $form->get('email');
            $element->setAttribute('class', 'form-control');
            $element->setAttribute('placeholder', $element->getLabel());
            $element->setLabelAttributes(array(
                'class' => 'control-label label-required'
            ));
            ?>
            <div class="form-group<?= $this->bootstrapElementError($element) ?>">
                <?= $this->formLabel($element) ?>
                <?= $this->formInput($element) ?>
                <?= $this->formElementErrors($element) ?>
            </div>
        </div>
        <div class="col-md-4">
            <?php
            $element = $form->get('birth');
            $element->setAttribute('class', 'form-control');
            $element->setAttribute('placeholder', $element->getLabel());
            $element->setLabelAttributes(array(
                'class' => 'control-label label-required'
            ));
            ?>
            <div class="form-group<?= $this->bootstrapElementError($element) ?>">
                <?= $this->formLabel($element) ?>
                <?= $this->formInput($element) ?>
                <?= $this->formElementErrors($element) ?>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <hr>
            <h3><?= $this->translate('Studie') ?></h3>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <?php
            $element = $form->get('tueUsername');
            $element->setAttribute('class', 'form-control');
            $element->setAttribute('placeholder', $element->getLabel());
            $element->setLabelAttributes(array(
                'class' => 'control-label label-required'
            ));
            ?>
            <div class="form-group<?= $this->bootstrapElementError($element) ?>">
                <?= $this->formLabel($element) ?>
                <?= $this->formInput($element) ?>
                <?= $this->formElementErrors($element) ?>
                <p><?= sprintf($this->translate('If you started after 2016, your username is an 8-digit number starting with the year you started at the TU/e, for example %s0001. You have received this in an email when you enrolled. Go to <a href="%s">this</a> page if you need help finding it. Your username will be used to verify you are studying at the department of M&CS.'), date('Y'), "https://wiki.gewis.nl/link/495") ?></p>
            </div>
        </div>
        <div class="col-md-6">
            <?php
            $element = $form->get('study');
            $element->setAttribute('class', 'form-control');
            $element->setLabelAttributes(array(
                'class' => 'control-label label-required'
            ));
            ?>
            <div class="form-group<?= $this->bootstrapElementError($element) ?>">
                <?= $this->formLabel($element) ?>
                <?= $this->formSelect($element) ?>
                <?= $this->formElementErrors($element) ?>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <hr>
            <h3><?= $this->translate('Adres') ?></h3>
        </div>
    </div>
    <fieldset class="study-address in">
        <?php
        $fs = $form->getFieldsets()['address'];
        ?>
        <?= $this->formHidden($fs->get('type')) ?>
        <div class="row">
            <div class="col-md-8">
                <?php
                $element = $fs->get('street');
                $element->setAttribute('class', 'form-control');
                $element->setAttribute('placeholder', $element->getLabel());
                $element->setLabelAttributes(array(
                    'class' => 'control-label label-required'
                ));
                ?>
                <div class="form-group<?= $this->bootstrapElementError($element) ?>">
                    <?= $this->formLabel($element) ?>
                    <?= $this->formInput($element) ?>
                    <?= $this->formElementErrors($element) ?>
                </div>
            </div>
            <div class="col-md-4">
                <?php
                $element = $fs->get('number');
                $element->setAttribute('class', 'form-control');
                $element->setAttribute('placeholder', $element->getLabel());
                $element->setLabelAttributes(array(
                    'class' => 'control-label label-required'
                ));
                ?>
                <div class="form-group<?= $this->bootstrapElementError($element) ?>">
                    <?= $this->formLabel($element) ?>
                    <?= $this->formInput($element) ?>
                    <?= $this->formElementErrors($element) ?>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <?php
                $element = $fs->get('postalCode');
                $element->setAttribute('class', 'form-control');
                $element->setAttribute('placeholder', $element->getLabel());
                $element->setLabelAttributes(array(
                    'class' => 'control-label label-required'
                ));
                ?>
                <div class="form-group<?= $this->bootstrapElementError($element) ?>">
                    <?= $this->formLabel($element) ?>
                    <?= $this->formInput($element) ?>
                    <?= $this->formElementErrors($element) ?>
                </div>
            </div>
            <div class="col-md-8">
                <?php
                $element = $fs->get('city');
                $element->setAttribute('class', 'form-control');
                $element->setAttribute('placeholder', $element->getLabel());
                $element->setLabelAttributes(array(
                    'class' => 'control-label label-required'
                ));
                ?>
                <div class="form-group<?= $this->bootstrapElementError($element) ?>">
                    <?= $this->formLabel($element) ?>
                    <?= $this->formInput($element) ?>
                    <?= $this->formElementErrors($element) ?>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <?php
                $element = $fs->get('country');
                $element->setAttribute('class', 'form-control');
                $element->setAttribute('placeholder', $element->getLabel());
                $element->setLabelAttributes(array(
                    'class' => 'control-label label-required'
                ));
                ?>
                <div class="form-group<?= $this->bootstrapElementError($element) ?>">
                    <?= $this->formLabel($element) ?>
                    <?= $this->formSelect($element) ?>
                    <?= $this->formElementErrors($element) ?>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <?php
                $element = $fs->get('phone');
                $element->setAttribute('class', 'form-control');
                $element->setAttribute('placeholder', $element->getLabel());
                $element->setLabelAttributes(array(
                    'class' => 'control-label'
                ));
                ?>
                <div class="form-group<?= $this->bootstrapElementError($element) ?>">
                    <?= $this->formLabel($element) ?>
                    <?= $this->formInput($element) ?>
                    <?= $this->formElementErrors($element) ?>
                </div>
            </div>
        </div>
    </fieldset>
    <div class="row">
        <div class="col-md-12">
            <hr>
            <h3><?= $this->translate('Mailinglijsten') ?></h3>
            <p>
                <?= $this->translate('Als GEWIS-lid word je ingeschreven op de GEWIS-lijst. Deze is voor mededelingen
en activiteiten van de studievereniging. Daarnaast zijn er verschillende
optionele mailinglijsten.
Voor de volgende mailinglijsten kun je je eventueel aanmelden. Deze
inschrijvingen kunnen op een later tijdstip veranderd worden.') ?>
            </p>
        </div>
    </div>
    <div class="row">
        <?php foreach ($form->getLists() as $list): ?>
            <div class="col-md-12">
                <div class="form-group">
                    <?php
                    $element = $form->get('list-' . $list->getName());
                    $element->setAttribute('placeholder', $element->getLabel());
                    ?>
                    <div class="checkbox">
                        <label><?= $this->formCheckbox($element) ?> <?= $element->getLabel() ?></label>
                        <?= $this->formElementErrors($element) ?>
                    </div>
                </div>
            </div>
        <?php endforeach ?>
    </div>
    <div class="row">
    <div class="col-md-12">
            <hr>
            <h3><?= $this->translate('Agreement') ?></h3>
            <a target="_blank" href="https://gewis.nl/vereniging/statuten/">
                <?= $this->translate('Articles of Association, Internal Regulations and privacy statement') ?>
            </a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <?php
            $element = $form->get('agreed');
            $element->setAttribute('placeholder', $element->getLabel());
            ?>
            <div class="form-group<?= $this->bootstrapElementError($element) ?>">
                <div class="checkbox">
                    <label>
                        <?= $this->formCheckbox($element) ?>
                        <?= $this->translate('Ik verklaar hierbij het formulier geheel naar waarheid te hebben ingevuld, en
ga akkoord met lidmaatschap van Studievereniging GEWIS. Ik ben bekend met de inhoud van de statuten
en het HR.
<br/>
Ik geef hierbij Gemeenschap van Wiskunde en Informatica Studenten (GEWIS) toestemming tot het
verwerken van mijn persoonsgegevens volgens haar privacybeleid.') ?>
                        <?= $element->getLabel() ?>
                    </label>
                    <?= $this->formElementErrors($element) ?>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
            <?php
            $submit = $form->get('submit');
            $submit->setLabel($submit->getValue());
            $submit->setAttribute('class', 'btn btn-primary');
            $submit->setAttribute('id', 'subscription-submit');
            ?>
            <div class="form-group">
                <?= $this->formButton($submit) ?>
            </div>
        </div>
    </div>
</div>
<?= $this->form()->closeTag() ?>
</div>

<script>
    window.addEventListener('load', (event) => {
        validator = new InputValidator(document.getElementById("<?= $form->getAttribute('id'); ?>"));
    });
</script>
