<?php
use Database\Model\Member as MemberModel;

/** @var MemberModel $member */
?>
<?php if (isset($form)): ?>
<?php
$this->headTitle()->prepend("GEWIS Enrollment");

$this->inlineScript()->appendFile($this->basePath() . '/js/signature_pad.min.js');
$this->inlineScript()->appendFile($this->basePath() . '/js/subscribe.app.js');
$this->inlineScript()->appendFile($this->basePath() . '/js/inputvalidator.min.js');

$form->prepare();

$form->setAttribute('action', $this->url('member/default', array('action' => 'subscribe')));
$form->setAttribute('method', 'post');

$form->setAttribute('role', 'form');
$form->setAttribute('class', 'form-horizontal');
$form->setAttribute('id', 'form-subscribe');
?>
<?= $this->form()->openTag($form) ?>

<div class="jumbotron">
<div class="row">
<div class="col-md-3">
<img src="<?= $this->basePath() ?>/img/gewis.png" />
</div>
<div class="col-md-9">
<h1><?= implode(' ',
        array('<span class="gewis-red">GEWIS</span>',
        $this->translate('Inschrijving'),
        $this->translate('SEPA-machtiging'))) ?></h1>
<p>
<?= $this->translate('Welkom! Met dit formulier kun je je inschrijven voor een
lidmaatschap van GEWIS. Het lidmaatschap is geldig zo lang je studeert en kost
eenmalig 15 euro. Deze betaling zal middels een eenmalige SEPA-machtiging
verlopen aan GEWIS. De adresgegevens van GEWIS zijn als volgt:') ?>
</p>
<p>
    <?= $this->translate('Incassant-ID') ?>: NL44ZZZ402377870000
</p>
<p>
<?= $this->translate('Naam') ?>: Gemeenschap van Wiskunde en Informatica Studenten<br>
<?= $this->translate('Adres') ?>: Den Dolech 2<br>
<?= $this->translate('Postcode') ?>: 5600 MB<br>
<?= $this->translate('Plaats') ?>: Eindhoven<br>
<?= $this->translate('Land') ?>: Nederland<br>
<?= $this->translate('If you have any questions feel free to contact') ?> <a href="mailto:board@gewis.nl">board@gewis.nl</a>
</p>
</div>
</div>
</div>

<div class="row">

<?php if (count($form->getMessages()) > 0): ?>
<div class="alert alert-danger" role="alert">
<?= $this->translate('Er zijn velden fout of niet ingevuld. Los dit op en stuur opnieuw in!') ?>
</div>
<?php endif ?>

<?php
$element = $form->get('lastName');
$element->setAttribute('class', 'form-control');
$element->setAttribute('placeholder', $element->getLabel());
$element->setLabelAttributes(array(
    'class' => 'col-sm-2 control-label'
));
?>
<div class="form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>">
    <?= $this->formLabel($element) ?>
    <div class="col-sm-10">
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>

<?php
$element = $form->get('middleName');
$element->setAttribute('class', 'form-control');
$element->setAttribute('placeholder', $element->getLabel());
$element->setLabelAttributes(array(
    'class' => 'col-sm-2 control-label'
));
?>
<div class="form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>">
    <?= $this->formLabel($element) ?>
    <div class="col-sm-10">
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>

<?php
$element = $form->get('initials');
$element->setAttribute('class', 'form-control validate-initials');
$element->setAttribute('placeholder', $element->getLabel());
$element->setLabelAttributes(array(
    'class' => 'col-sm-2 control-label'
));
?>
<div class="form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>">
    <?= $this->formLabel($element) ?>
    <div class="col-sm-10">
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>

<?php
$element = $form->get('firstName');
$element->setAttribute('class', 'form-control');
$element->setAttribute('placeholder', $element->getLabel());
$element->setLabelAttributes(array(
    'class' => 'col-sm-2 control-label'
));
?>
<div class="form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>">
    <?= $this->formLabel($element) ?>
    <div class="col-sm-10">
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>

<?php
$element = $form->get('tueUsername');
$element->setAttribute('class', 'form-control');
$element->setAttribute('placeholder', $element->getLabel());
$element->setLabelAttributes(array(
    'class' => 'col-sm-2 control-label'
));
?>
<div class="form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>">
    <?= $this->formLabel($element) ?>
    <div class="col-sm-10">
        <?= $this->formInput($element) ?>
        <p><?= sprintf($this->translate('If you started after 2016, your username is an 8-digit number starting with the year you started at the TU/e, for example %s0001. You have received this in an email when you enrolled. Go to <a href="%s">this</a> page if you need help finding it. Your username will be used to verify you are studying at the department of M&CS.'), date('Y'), "https://wiki.gewis.nl/link/495") ?></p>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>

<?php
$element = $form->get('study');
$element->setAttribute('class', 'form-control');
$element->setLabelAttributes(array(
    'class' => 'col-sm-2 control-label'
));
?>
<div class="form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>">
    <?= $this->formLabel($element) ?>
    <div class="col-sm-10">
        <?= $this->formSelect($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>

<?php
$element = $form->get('email');
$element->setAttribute('class', 'form-control');
$element->setAttribute('placeholder', $element->getLabel());
$element->setLabelAttributes(array(
    'class' => 'col-sm-2 control-label'
));
?>
<div class="form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>">
    <?= $this->formLabel($element) ?>
    <div class="col-sm-10">
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>

<?php
$element = $form->get('birth');
$element->setAttribute('class', 'form-control');
$element->setAttribute('placeholder', $element->getLabel());
$element->setLabelAttributes(array(
    'class' => 'col-sm-2 control-label'
));
?>
<div class="form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>">
    <?= $this->formLabel($element) ?>
    <div class="col-sm-10">
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>

<fieldset class="study-address in">
<h3><?= $this->translate('Adres') ?></h3>
<?php
$fs = $form->get('address');
?>
<?= $this->formHidden($fs->get('type')) ?>

<?php
$element = $fs->get('country');
$element->setAttribute('class', 'form-control');
$element->setAttribute('placeholder', $element->getLabel());
$element->setLabelAttributes(array(
    'class' => 'col-sm-2 control-label'
));
?>
<div class="form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>">
    <?= $this->formLabel($element) ?>
    <div class="col-sm-10">
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>

<?php
$element = $fs->get('street');
$element->setAttribute('class', 'form-control');
$element->setAttribute('placeholder', $element->getLabel());
$element->setLabelAttributes(array(
    'class' => 'col-sm-2 control-label'
));
?>
<div class="form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>">
    <?= $this->formLabel($element) ?>
    <div class="col-sm-10">
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>

<?php
$element = $fs->get('number');
$element->setAttribute('class', 'form-control');
$element->setAttribute('placeholder', $element->getLabel());
$element->setLabelAttributes(array(
    'class' => 'col-sm-2 control-label'
));
?>
<div class="form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>">
    <?= $this->formLabel($element) ?>
    <div class="col-sm-10">
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>

<?php
$element = $fs->get('postalCode');
$element->setAttribute('class', 'form-control');
$element->setAttribute('placeholder', $element->getLabel());
$element->setLabelAttributes(array(
    'class' => 'col-sm-2 control-label'
));
?>
<div class="form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>">
    <?= $this->formLabel($element) ?>
    <div class="col-sm-10">
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>

<?php
$element = $fs->get('city');
$element->setAttribute('class', 'form-control');
$element->setAttribute('placeholder', $element->getLabel());
$element->setLabelAttributes(array(
    'class' => 'col-sm-2 control-label'
));
?>
<div class="form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>">
    <?= $this->formLabel($element) ?>
    <div class="col-sm-10">
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>

<?php
$element = $fs->get('phone');
$element->setAttribute('class', 'form-control');
$element->setAttribute('placeholder', $element->getLabel());
$element->setLabelAttributes(array(
    'class' => 'col-sm-2 control-label'
));
?>
<div class="form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>">
    <?= $this->formLabel($element) ?>
    <div class="col-sm-10">
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>
</fieldset>

<h3><?= $this->translate('Mailinglijsten') ?></h3>
<p>
<?= $this->translate('Als GEWIS-lid word je ingeschreven op de GEWIS-lijst. Deze is voor mededelingen
en activiteiten van de studievereniging. Daarnaast zijn er verschillende
optionele mailinglijsten.
Voor de volgende mailinglijsten kun je je eventueel aanmelden. Deze
inschrijvingen kunnen op een later tijdstip veranderd worden.') ?>
</p>

<?php foreach ($form->getLists() as $list): ?>
<div class="form-group">
    <?php
    $element = $form->get('list-' . $list->getName());
    $element->setAttribute('placeholder', $element->getLabel());
    ?>
    <div class="col-sm-offset-1 col-sm-8">
        <div class="checkbox">
            <label>
                <?= $this->formCheckbox($element) ?>
                <?= $element->getLabel() ?>
            </label>
            <?= $this->formElementErrors($element) ?>
        </div>
    </div>
</div>
<?php endforeach ?>

<h3><?= $this->translate('Akkoordverklaring') ?></h3>

<a target="_blank" href="https://gewis.nl/vereniging/statuten/"><?= $this->translate('Statuten, HR en privacybeleid') ?></a>

<?php
$element = $form->get('agreed');
$element->setAttribute('placeholder', $element->getLabel());
?>
<div class="form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>">
    <div class="col-sm-offset-1 col-sm-8">
        <div class="checkbox">
            <label>
                <?= $this->formCheckbox($element) ?>
<?= $this->translate('Ik verklaar hierbij het formulier geheel naar waarheid te hebben ingevuld, en
ga akkoord met lidmaatschap van Studievereniging GEWIS. Ik ben bekend met de inhoud van de statuten
en het HR.
<br/>
Ik geef hierbij Gemeenschap van Wiskunde en Informatica Studenten (GEWIS) toestemming tot het
verwerken van mijn persoonsgegevens volgens haar privacybeleid.') ?>
                <?= $element->getLabel() ?>
            </label>
            <?= $this->formElementErrors($element) ?>
        </div>
    </div>
</div>

<h3><?= $this->translate('SEPA Direct Debit') ?></h3>
<?php
$element = $form->get('iban');
$element->setAttribute('class', 'form-control');
$element->setAttribute('placeholder', $element->getLabel());
$element->setAttribute('id', 'iban-input');
$element->setLabelAttributes(array(
    'class' => 'col-sm-2 control-label'
));
?>
<div class="form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>">
    <?= $this->formLabel($element) ?>
    <div class="col-sm-10">
        <?= $this->formInput($element) ?>
        <p><?= sprintf($this->translate('You can pay for your GEWIS membership using a SEPA direct debit.
This means that GEWIS will debit &euro;15,- from your bank account. You only have to pay once for
the entire duration of your studies. Only bank accounts in euros are supported for this payment method.
Contact %s for any questions about your payment.'), "<a href='mailto:board@gewis.nl'>board@gewis.nl</a>") ?></p>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>

<?php
$element = $form->get('agreediban');
$element->setAttribute('placeholder', $element->getLabel());
$element->setAttribute('id', 'iban-agreement');
?>
<div class="form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>">
    <div class="col-sm-offset-1 col-sm-8">
        <div class="checkbox">
            <label>
                <?= $this->formCheckbox($element) ?>
<?= $this->translate('Door ondertekening van dit formulier geef ik (A) Gemeenschap van Wiskunde en Informatica Studenten (GEWIS)
                toestemming om eenmalig een incasso-opdracht te sturen naar mijn bank om een bedrag van &euro;15,-, 
                geheten vijftien euro, van mijn rekening af te schrijven en (B) aan mijn bank om eenmalig een bedrag van 
                mijn rekening af te schrijven overeenkomstig de opdracht van GEWIS.
                <br/>
                Als u het niet eens bent met deze afschrijving kunt u deze laten terugboeken. Neem hiervoor binnen <b>acht
                weken</b> na afschrijving contact op met uw bank. Vraag uw bank naar de voorwaarden.') ?>
                <?= $element->getLabel() ?>
            </label>
            <?= $this->formElementErrors($element) ?>
        </div>
    </div>
</div>

<?php
$element = $form->get('signatureLocation');
$element->setAttribute('class', 'form-control');
$element->setAttribute('placeholder', $element->getLabel());
$element->setLabelAttributes(array(
    'class' => 'col-sm-2 control-label'
));
?>
<div class="form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>">
    <?= $this->formLabel($element) ?>
    <div class="col-sm-10">
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>

<p>
<?= $this->translate('Voor de automatische eenmalige SEPA-machtiging hebben we je handtekening nodig. Deze kan je hieronder in het vakje tekenen.') ?>
</p>
<div class="form-group" id="signature-form-group">
    <div class="col-sm-12">
        <canvas id="signature-canvas"><?= $this->translate('Je internetbrowser ondersteunt geen digitale handtekeningen. Gebruik een moderne browser, zoals Firefox.') ?></canvas>
        <br>
        <button class="btn" type="button" id="signature-canvas-clear"><?= $this->translate('Verwijder handtekening') ?></button>
        <?= $this->formHidden($form->get('signature')->setAttribute('id', 'signature-canvas-data')); ?>
    </div>
</div>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php
        $submit = $form->get('submit');
        $submit->setLabel($submit->getValue());
        $submit->setAttribute('class', 'btn btn-primary');
        $submit->setAttribute('id', 'subscription-submit');
        ?>
        <?= $this->formButton($submit) ?>
    </div>
</div>

<?= $this->form()->closeTag() ?>
</div>

<script>
    window.addEventListener('load', (event) => {
        validator = new InputValidator(document.getElementById("<?= $form->getAttribute('id'); ?>"));
    });
</script>

<?php else: ?>
    <h1 class="hidden-print"><?= $this->translate('Gefeliciteerd! Je bent geregistreed als lid van Studievereniging GEWIS') ?>
        <br>
        <small><?= $this->translate('Na betaling van je lidmaatschapsgeld ben je GEWIS-lid!') ?></small></h1>
<!--Use the code below to add some nice pop-up or promotion to the subscription email.-->
<!--    <div class="alert alert-info">-->
<!--        Liked the introduction week? GEWIS also organizes a follow-up day after the introduction week: the FLUP!-->
<!--        During the FLUP you get to know even more fellow students and GEWIS as an association through fun activities and a BBQ.-->
<!--        This event will take place on Saturday, September 12. Tickets can be bought on <a href="https://gewis.nl/FLUP">https://gewis.nl/FLUP</a> for &euro;3,-.-->
<!--    </div>-->
    <h2 class="hidden-print">Hier nogmaals je gegevens ter controle</h2>
<div class="row">
<div class="col-md-6">
    <h1><?= $member->getFullName() ?></h1>
    <table class="table table-bordered">
        <tr>
            <th><?= $this->translate('Voorletters') ?></th>
            <td><?= $member->getInitials() ?></td>
        </tr>
        <tr>
            <th><?= $this->translate('Voornaam') ?></th>
            <td><?= $member->getFirstName() ?></td>
        </tr>
        <tr>
            <th><?= $this->translate('Tussenvoegsels') ?></th>
            <td><?= $member->getMiddleName() ?></td>
        </tr>
        <tr>
            <th><?= $this->translate('Achternaam') ?></th>
            <td><?= $member->getLastName() ?></td>
        </tr>
        <tr>
            <th><?= $this->translate('TU/e-gebruikersnaam') ?></th>
            <td>
                <?= (null === $member->getTueUsername()) ? $this->translate('Onbekend') : $member->getTueUsername() ?>
            </td>
        </tr>
        <tr>
            <th><?= $this->translate('Studie') ?></th>
            <td><?= $member->getStudy() ?></td>
        </tr>
        <tr>
            <th><?= $this->translate('Email') ?></th>
            <td><a href="mailto:<?= $member->getEmail() ?>"><?= $member->getEmail() ?></a></td>
        </tr>
        <tr>
            <th><?= $this->translate('Geboortedatum') ?></th>
            <td><?= $member->getBirth()->format('l j F Y') ?></td>
        </tr>
        <tr>
            <th><?= $this->translate('IBAN') ?></th>
            <td><?= $member->getIban() ?? $this->translate('Onbekend') ?></td>
        </tr>
        <tr>
            <th><?= $this->translate('Betaald (hoe veel)') ?></th>
            <td><?= $member->getPaid() ?></td>
        </tr>
        <tr>
            <th><?= $this->translate('Laatste wijziging lidmaatshap') ?></th>
            <td><?= $member->getChangedOn()->format('l j F Y') ?></td>
        </tr>
    </table>
</div>
<div class="col-md-6">
<h3><?= $this->translate('Adressen') ?></h3>
<?php foreach ($member->getAddresses() as $address): ?>
    <h4><?= $address->getType()->getName($this->plugin('translate')->getTranslator()) ?></h4>
    <table class="table table-bordered">
        <tr>
            <th><?= $this->translate('Land') ?></th>
            <td><?= $address->getCountry() ?></td>
        </tr>
        <tr>
            <th><?= $this->translate('Straat en huisnummer') ?></th>
            <td><?= $address->getStreet() ?> <?= $address->getNumber() ?></td>
        </tr>
        <tr>
            <th><?= $this->translate('Woonplaats en Postcode') ?></th>
            <td><?= $address->getCity() ?> <?= $address->getPostalCode() ?></td>
        </tr>
        <tr>
            <th><?= $this->translate('Telefoonnummer') ?></th>
            <td><?= $address->getPhone() ?></td>
        </tr>
    </table>
<?php endforeach ?>
<h3><?= $this->translate('Aangemelde mailing lists') ?></h3>
<ul>
<?php foreach ($member->getLists() as $list): ?>
    <li><?= $list->getName() ?></li>
<?php endforeach ?>
</ul>

<?php if (null !== $member->getIban()): ?>
<p>
    <?= $this->translate('Incassant-ID') ?>: NL44ZZZ402377870000
</p>

<p>
    <?= $this->translate('Kenmerk van de machtiging') ?>: <?= $member->getMandateCharacteristic() ?>
</p>
<div class="visible-print">
<table class="table table-bordered">
    <tr>
        <td>
            <?php if($address->getCountry() === 'netherlands'): ?>
                Door ondertekening van dit formulier geeft u (A) Gemeenschap van Wiskunde en Informatica Studenten (GEWIS)
                toestemming om eenmalig een incasso-opdracht te sturen naar uw bank om een bedrag van &euro;15,-, 
                geheten vijftien euro, van uw rekening af te schrijven en (B) aan uw bank om eenmalig een bedrag van 
                uw rekening af te schrijven overeenkomstig de opdracht van GEWIS.
                <br/>
                Als u het niet eens bent met deze afschrijving kunt u deze laten terugboeken. Neem hiervoor binnen <b>acht
                weken</b> na afschrijving contact op met uw bank. Vraag uw bank naar de voorwaarden.
            <?php else: ?>
                By signing this mandate form, you (A) authorise Gemeenschap van Wiskunde en Informatica Studenten (GEWIS) 
                to send instructions to your bank to debit your account with &euro;15,-, fifteen euros, and (B) your bank
                to debit your account in accordance with the instructions from Gemeenschap van Wiskunde en Informatica Studenten (GEWIS).
                <br/>
                As part of your rights, you are entitled to a refund from your bank under the terms and conditions of
                your agreement with your bank. A refund must be claimed within <b>8 weeks</b> starting from the date on
                which your account was debited.
            <?php endif ?>
        </td>
    </tr>
    <tr>
        <th><?= $this->translate('Plaats en datum van ondertekening') ?><br><?= $member->getSignatureLocation() ?><br><?= $member->getChangedOn()->format('F j, Y') ?><br><br><br><br></th>
        <th><?= $this->translate('Handtekening') ?><br><img src="<?= $this->fileUrl($member->getSignature()) ?>" height="100" width="300" /><br><br><br><br><br></th>
    </tr>
</table>
</div>
<?php endif; ?>
</div>
</div>
<?php endif ?>
