<?php

declare(strict_types=1);

use Application\Model\Enums\PostalRegions;
use Application\View\HelperTrait;
use Database\Model\Member as MemberModel;
use Laminas\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer|HelperTrait $this
 * @var MemberModel $member
 */
?>
<?php if (isset($form)): ?>
<?php
$this->headTitle()->prepend("GEWIS Enrollment");

$this->inlineScript()->appendFile($this->basePath() . '/js/inputvalidator.min.js');

$form->prepare();

$form->setAttribute('action', $this->url('member/subscribe'));
$form->setAttribute('method', 'post');

$form->setAttribute('role', 'form');
$form->setAttribute('id', 'form-subscribe');
?>
<?= $this->form()->openTag($form) ?>

<div class="jumbotron">
    <div class="row">
        <div class="col-md-3">
            <img src="<?= $this->basePath() ?>/img/gewis.png" />
        </div>
        <div class="col-md-9">
            <h1>
                <span class="gewis-red">GEWIS</span> <?= $this->translate('Inschrijving') ?>
            </h1>
            <p>
                <?= $this->translate('Welkom! Met dit formulier kun je je inschrijven voor een
lidmaatschap van GEWIS. Het lidmaatschap is geldig zo lang je studeert en kost
eenmalig 15 euro.') ?>
            </p>
            <p>
                <?= $this->translate('If you have any questions feel free to contact') ?> <a href="mailto:board@gewis.nl">board@gewis.nl</a>.
            </p>
        </div>
    </div>
</div>

<div class="row">

<?php if (count($form->getMessages()) > 0): ?>
<div class="alert alert-danger" role="alert">
<?= $this->translate('Some of the entered information appears to be missing or incorrect. Please check your data and submit again.') ?>
</div>
<?php endif ?>

<div class="col-md-12">
    <div class="row">
        <div class="col-md-12">
            <h3><?= $this->translate('Personal details') ?></h3>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
            <?php
            $element = $form->get('initials');
            $element->setAttribute('class', 'form-control validate-initials');
            $element->setAttribute('placeholder', $element->getLabel());
            $element->setLabelAttributes(array(
                'class' => 'control-label label-required'
            ));
            ?>
            <div class="form-group<?= $this->bootstrapElementError($element) ?>">
                <?= $this->formLabel($element) ?>
                <?= $this->formInput($element) ?>
                <?= $this->formElementErrors($element) ?>
            </div>
        </div>
        <div class="col-md-4">
            <?php
            $element = $form->get('firstName');
            $element->setAttribute('class', 'form-control');
            $element->setAttribute('placeholder', $element->getLabel());
            $element->setLabelAttributes(array(
                'class' => 'control-label label-required'
            ));
            ?>
            <div class="form-group<?= $this->bootstrapElementError($element) ?>">
                <?= $this->formLabel($element) ?>
                <?= $this->formInput($element) ?>
                <?= $this->formElementErrors($element) ?>
            </div>
        </div>
        <div class="col-md-2">
            <?php
            $element = $form->get('middleName');
            $element->setAttribute('class', 'form-control');
            $element->setAttribute('placeholder', $element->getLabel());
            $element->setLabelAttributes(array(
                'class' => 'control-label'
            ));
            ?>
            <div class="form-group<?= $this->bootstrapElementError($element) ?>">
                <?= $this->formLabel($element) ?>
                <?= $this->formInput($element) ?>
                <?= $this->formElementErrors($element) ?>
            </div>
        </div>
        <div class="col-md-4">
            <?php
            $element = $form->get('lastName');
            $element->setAttribute('class', 'form-control');
            $element->setAttribute('placeholder', $element->getLabel());
            $element->setLabelAttributes(array(
                'class' => 'control-label label-required'
            ));
            ?>
            <div class="form-group<?= $this->bootstrapElementError($element) ?>">
                <?= $this->formLabel($element) ?>
                <?= $this->formInput($element) ?>
                <?= $this->formElementErrors($element) ?>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8">
            <?php
            $element = $form->get('email');
            $element->setAttribute('class', 'form-control');
            $element->setAttribute('placeholder', $element->getLabel());
            $element->setLabelAttributes(array(
                'class' => 'control-label label-required'
            ));
            ?>
            <div class="form-group<?= $this->bootstrapElementError($element) ?>">
                <?= $this->formLabel($element) ?>
                <?= $this->formInput($element) ?>
                <?= $this->formElementErrors($element) ?>
            </div>
        </div>
        <div class="col-md-4">
            <?php
            $element = $form->get('birth');
            $element->setAttribute('class', 'form-control');
            $element->setAttribute('placeholder', $element->getLabel());
            $element->setLabelAttributes(array(
                'class' => 'control-label label-required'
            ));
            ?>
            <div class="form-group<?= $this->bootstrapElementError($element) ?>">
                <?= $this->formLabel($element) ?>
                <?= $this->formInput($element) ?>
                <?= $this->formElementErrors($element) ?>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <hr>
            <h3><?= $this->translate('Studie') ?></h3>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <?php
            $element = $form->get('tueUsername');
            $element->setAttribute('class', 'form-control');
            $element->setAttribute('placeholder', $element->getLabel());
            $element->setLabelAttributes(array(
                'class' => 'control-label label-required'
            ));
            ?>
            <div class="form-group<?= $this->bootstrapElementError($element) ?>">
                <?= $this->formLabel($element) ?>
                <?= $this->formInput($element) ?>
                <?= $this->formElementErrors($element) ?>
                <p><?= sprintf($this->translate('If you started after 2016, your username is an 8-digit number starting with the year you started at the TU/e, for example %s0001. You have received this in an email when you enrolled. Go to <a href="%s">this</a> page if you need help finding it. Your username will be used to verify you are studying at the department of M&CS.'), date('Y'), "https://wiki.gewis.nl/link/495") ?></p>
            </div>
        </div>
        <div class="col-md-6">
            <?php
            $element = $form->get('study');
            $element->setAttribute('class', 'form-control');
            $element->setLabelAttributes(array(
                'class' => 'control-label label-required'
            ));
            ?>
            <div class="form-group<?= $this->bootstrapElementError($element) ?>">
                <?= $this->formLabel($element) ?>
                <?= $this->formSelect($element) ?>
                <?= $this->formElementErrors($element) ?>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <hr>
            <h3><?= $this->translate('Adres') ?></h3>
        </div>
    </div>
    <fieldset class="study-address in">
        <?php
        $fs = $form->getFieldsets()['address'];
        ?>
        <?= $this->formHidden($fs->get('type')) ?>
        <div class="row">
            <div class="col-md-8">
                <?php
                $element = $fs->get('street');
                $element->setAttribute('class', 'form-control');
                $element->setAttribute('placeholder', $element->getLabel());
                $element->setLabelAttributes(array(
                    'class' => 'control-label label-required'
                ));
                ?>
                <div class="form-group<?= $this->bootstrapElementError($element) ?>">
                    <?= $this->formLabel($element) ?>
                    <?= $this->formInput($element) ?>
                    <?= $this->formElementErrors($element) ?>
                </div>
            </div>
            <div class="col-md-4">
                <?php
                $element = $fs->get('number');
                $element->setAttribute('class', 'form-control');
                $element->setAttribute('placeholder', $element->getLabel());
                $element->setLabelAttributes(array(
                    'class' => 'control-label label-required'
                ));
                ?>
                <div class="form-group<?= $this->bootstrapElementError($element) ?>">
                    <?= $this->formLabel($element) ?>
                    <?= $this->formInput($element) ?>
                    <?= $this->formElementErrors($element) ?>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <?php
                $element = $fs->get('postalCode');
                $element->setAttribute('class', 'form-control');
                $element->setAttribute('placeholder', $element->getLabel());
                $element->setLabelAttributes(array(
                    'class' => 'control-label label-required'
                ));
                ?>
                <div class="form-group<?= $this->bootstrapElementError($element) ?>">
                    <?= $this->formLabel($element) ?>
                    <?= $this->formInput($element) ?>
                    <?= $this->formElementErrors($element) ?>
                </div>
            </div>
            <div class="col-md-8">
                <?php
                $element = $fs->get('city');
                $element->setAttribute('class', 'form-control');
                $element->setAttribute('placeholder', $element->getLabel());
                $element->setLabelAttributes(array(
                    'class' => 'control-label label-required'
                ));
                ?>
                <div class="form-group<?= $this->bootstrapElementError($element) ?>">
                    <?= $this->formLabel($element) ?>
                    <?= $this->formInput($element) ?>
                    <?= $this->formElementErrors($element) ?>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <?php
                $element = $fs->get('country');
                $element->setAttribute('class', 'form-control');
                $element->setAttribute('placeholder', $element->getLabel());
                $element->setLabelAttributes(array(
                    'class' => 'control-label label-required'
                ));
                ?>
                <div class="form-group<?= $this->bootstrapElementError($element) ?>">
                    <?= $this->formLabel($element) ?>
                    <?= $this->formSelect($element) ?>
                    <?= $this->formElementErrors($element) ?>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <?php
                $element = $fs->get('phone');
                $element->setAttribute('class', 'form-control');
                $element->setAttribute('placeholder', $element->getLabel());
                $element->setLabelAttributes(array(
                    'class' => 'control-label'
                ));
                ?>
                <div class="form-group<?= $this->bootstrapElementError($element) ?>">
                    <?= $this->formLabel($element) ?>
                    <?= $this->formInput($element) ?>
                    <?= $this->formElementErrors($element) ?>
                </div>
            </div>
        </div>
    </fieldset>
    <div class="row">
        <div class="col-md-12">
            <hr>
            <h3><?= $this->translate('Mailinglijsten') ?></h3>
            <p>
                <?= $this->translate('Als GEWIS-lid word je ingeschreven op de GEWIS-lijst. Deze is voor mededelingen
en activiteiten van de studievereniging. Daarnaast zijn er verschillende
optionele mailinglijsten.
Voor de volgende mailinglijsten kun je je eventueel aanmelden. Deze
inschrijvingen kunnen op een later tijdstip veranderd worden.') ?>
            </p>
        </div>
    </div>
    <div class="row">
        <?php foreach ($form->getLists() as $list): ?>
            <div class="col-md-12">
                <div class="form-group">
                    <?php
                    $element = $form->get('list-' . $list->getName());
                    $element->setAttribute('placeholder', $element->getLabel());
                    ?>
                    <div class="checkbox">
                        <label><?= $this->formCheckbox($element) ?> <?= $element->getLabel() ?></label>
                        <?= $this->formElementErrors($element) ?>
                    </div>
                </div>
            </div>
        <?php endforeach ?>
    </div>
    <div class="row">
    <div class="col-md-12">
            <hr>
            <h3><?= $this->translate('Agreement') ?></h3>
            <a target="_blank" href="https://gewis.nl/vereniging/statuten/">
                <?= $this->translate('Articles of Association, Internal Regulations and privacy statement') ?>
            </a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <?php
            $element = $form->get('agreed');
            $element->setAttribute('placeholder', $element->getLabel());
            ?>
            <div class="form-group<?= $this->bootstrapElementError($element) ?>">
                <div class="checkbox">
                    <label>
                        <?= $this->formCheckbox($element) ?>
                        <?= $this->translate('Ik verklaar hierbij het formulier geheel naar waarheid te hebben ingevuld, en
ga akkoord met lidmaatschap van Studievereniging GEWIS. Ik ben bekend met de inhoud van de statuten
en het HR.
<br/>
Ik geef hierbij Gemeenschap van Wiskunde en Informatica Studenten (GEWIS) toestemming tot het
verwerken van mijn persoonsgegevens volgens haar privacybeleid.') ?>
                        <?= $element->getLabel() ?>
                    </label>
                    <?= $this->formElementErrors($element) ?>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
            <?php
            $submit = $form->get('submit');
            $submit->setLabel($submit->getValue());
            $submit->setAttribute('class', 'btn btn-primary');
            $submit->setAttribute('id', 'subscription-submit');
            ?>
            <div class="form-group">
                <?= $this->formButton($submit) ?>
            </div>
        </div>
    </div>
</div>
<?= $this->form()->closeTag() ?>
</div>

<script>
    window.addEventListener('load', (event) => {
        validator = new InputValidator(document.getElementById("<?= $form->getAttribute('id'); ?>"));
    });
</script>

<?php else: ?>
    <h1 class="hidden-print"><?= $this->translate('Gefeliciteerd! Je bent geregistreed als lid van Studievereniging GEWIS') ?>
        <br>
        <small><?= $this->translate('Na betaling van je lidmaatschapsgeld ben je GEWIS-lid!') ?></small></h1>
<!--Use the code below to add some nice pop-up or promotion to the subscription email.-->
<!--    <div class="alert alert-info">-->
<!--        Liked the introduction week? GEWIS also organizes a follow-up day after the introduction week: the FLUP!-->
<!--        During the FLUP you get to know even more fellow students and GEWIS as an association through fun activities and a BBQ.-->
<!--        This event will take place on Saturday, September 12. Tickets can be bought on <a href="https://gewis.nl/FLUP">https://gewis.nl/FLUP</a> for &euro;3,-.-->
<!--    </div>-->
    <h2 class="hidden-print">Hier nogmaals je gegevens ter controle</h2>
<div class="row">
<div class="col-md-6">
    <h1><?= $member->getFullName() ?></h1>
    <table class="table table-bordered">
        <tr>
            <th><?= $this->translate('Voorletters') ?></th>
            <td><?= $member->getInitials() ?></td>
        </tr>
        <tr>
            <th><?= $this->translate('Voornaam') ?></th>
            <td><?= $member->getFirstName() ?></td>
        </tr>
        <tr>
            <th><?= $this->translate('Tussenvoegsels') ?></th>
            <td><?= $member->getMiddleName() ?></td>
        </tr>
        <tr>
            <th><?= $this->translate('Achternaam') ?></th>
            <td><?= $member->getLastName() ?></td>
        </tr>
        <tr>
            <th><?= $this->translate('TU/e-gebruikersnaam') ?></th>
            <td>
                <?= (null === $member->getTueUsername()) ? $this->translate('Onbekend') : $member->getTueUsername() ?>
            </td>
        </tr>
        <tr>
            <th><?= $this->translate('Study') ?></th>
            <td><?= $member->getStudy() ?></td>
        </tr>
        <tr>
            <th><?= $this->translate('E-mail Address') ?></th>
            <td><a href="mailto:<?= $member->getEmail() ?>"><?= $member->getEmail() ?></a></td>
        </tr>
        <tr>
            <th><?= $this->translate('Birthdate') ?></th>
            <td><?= $member->getBirth()->format('l j F Y') ?></td>
        </tr>
    </table>
</div>
<div class="col-md-6">
<h3><?= $this->translate('Addresses') ?></h3>
<?php foreach ($member->getAddresses() as $address): ?>
    <h4><?= $address->getType()->getName($this->plugin('translate')->getTranslator()) ?></h4>
    <table class="table table-bordered">
        <tr>
            <th><?= $this->translate('Postal Region') ?></th>
            <td><?= $address->getCountry()->value ?></td>
        </tr>
        <tr>
            <th><?= $this->translate('Straat en huisnummer') ?></th>
            <td><?= $address->getStreet() ?> <?= $address->getNumber() ?></td>
        </tr>
        <tr>
            <th><?= $this->translate('Woonplaats en Postcode') ?></th>
            <td><?= $address->getCity() ?> <?= $address->getPostalCode() ?></td>
        </tr>
        <tr>
            <th><?= $this->translate('Telefoonnummer') ?></th>
            <td><?= $address->getPhone() ?></td>
        </tr>
    </table>
<?php endforeach ?>
<h3><?= $this->translate('Aangemelde mailing lists') ?></h3>
<ul>
<?php foreach ($member->getLists() as $list): ?>
    <li><?= $list->getName() ?></li>
<?php endforeach ?>
</ul>
</div>
</div>
<?php endif ?>
