<h1>TU/e lookup</h1>

<?php if($_ENV['APP_ENV'] === "development"):?>
<p>Valid student IDs for testing:</p>
<ul>
    <li>20170001: too many requests</li>
    <li>20180001: student MCS (Timo de Teststudent)</li>
    <li>20190001: student MCS + something else (Tara van Testdata)</li>
    <li>20200001: student not MCS (Marco van Mechanical Engineering)</li>
    <li>20210001: not student (Nico Nietstudent)</li>
    <li>Everything else: invalid number</li>
</ul>

<?php endif; ?>
    
<script>
$(document).ready(function () {
    var tbody = $('#reponsetable tbody');
    var currentrequest;
    var lookup = function (username) {
        tbody.html('');
        if (username.length >= 6) {
            currentrequest = $.ajax({
                dataType: 'json',
                url: '<?= $this->url('member/default', array('action' => 'tuerequest')) ?>?u=' + username,
                context: document.body,
                beforeSend: () => {
                    if (currentrequest != undefined) { currentrequest.abort(); }
                },
            }).done(function (data) {
                tbody.html('');
                $.each(data, function(key,val){
                    tbody.append('<tr><td>' + key + '</td><td>' + JSON.stringify(val) + '</td></tr>');
                });
            });
        }
    };

    $('#lookup-username').keyup(function (e) {
        username = $(e.target).val();
        lookup(username);
    });
    lookup("<?= $username ?>");
});
</script>
<form role="form">
    <div class="form-group">
        <label for="">TU/e-gebruiker zoeken</label>
        <input type="text" class="form-control" placeholder="Zoek" id="lookup-username" value="<?= $username ?>" autofocus>
    </div>
</form>

<table id="reponsetable">
    <thead>
        <tr>
            <th>Key</th>
            <th>Value</th>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>