<h1>TU/e lookup</h1>

<?php if($_ENV['environment'] === "development"):?>
<p>Valid student IDs for testing:</p>
<ul>
    <li>20170001: too many requests</li>
    <li>20180001: student MCS (Timo de Teststudent)</li>
    <li>20190001: student MCS + something else (Tara van Testdata)</li>
    <li>20200001: student not MCS (Marco van Mechanical Engineering)</li>
    <li>20210001: not student (Nico Nietstudent)</li>
    <li>Everything else: invalid number</li>
</ul>

<?php endif; ?>
    
<?= $data ?>
