<h1><?= $this->translate('TU/e Raw Data Lookup') ?></h1>

<?php if('development' === APP_ENV):?>
    <p>Valid student IDs for testing:</p>
    <ul>
        <li>20170001: too many requests</li>
        <li>20180001: student MCS (Timo de Teststudent)</li>
        <li>20190001: student MCS + something else (Tara van Testdata)</li>
        <li>20200001: student not MCS (Marco van Mechanical Engineering)</li>
        <li>20210001: not student (Nico Nietstudent)</li>
        <li>Everything else: invalid number</li>
    </ul>
<?php endif; ?>

<script>
$(document).ready(function () {
    var tbody = $('#reponsetable tbody');
    var currentrequest;
    var lookup = function (username) {
        tbody.html('');
        if (username.length >= 6) {
            currentrequest = $.ajax({
                dataType: 'json',
                url: '<?= $this->url('member/default', array('action' => 'tuerequest')) ?>?u=' + username,
                context: document.body,
                beforeSend: () => {
                    if (currentrequest != undefined) { currentrequest.abort(); }
                },
            }).done(function (data) {
                tbody.html('');
                $.each(data, function(key,val){
                    tbody.append('<tr><td>' + key + '</td><td>' + JSON.stringify(val) + '</td></tr>');
                });
            });
        }
    };

    $('#lookup-username').keyup(function (e) {
        username = $(e.target).val();
        lookup(username);
    });
    lookup("<?= $username ?>");
});
</script>
<form role="form">
    <div class="form-group">
        <label for=""><?= $this->translate('Search TU/e Students') ?></label>
        <input type="text" class="form-control" placeholder="<?= $this->translate('Search') ?>" id="lookup-username" value="<?= $username ?>" autofocus>
    </div>
</form>

<table id="reponsetable">
    <thead>
        <tr>
            <th><?= $this->translate('Key') ?></th>
            <th><?= $this->translate('Value') ?></th>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>
