<h1>Update verzoeken</h1>
<?php foreach ($updates as $update): ?>
    <table class="table table-bordered  ">
        <thead>
        <tr>
            <th>Lid <a rel="_blank" href="<?= $this->url('member/show', array('id' => $update->getLidnr())) ?>"><?=$update->getLidnr() ?></a></th>
            <th><div class="btn-group" role="group">
                    <form style="display: inline-block" method="POST" action="<?= $this->url('member/updates/reject', array('lidnr' => $update->getLidnr())) ?>">
                        <button type="submit" class="btn btn-danger"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></button>
                    </form>
                    <form style="display: inline-block" method="POST" action="<?= $this->url('member/updates/approve', array('lidnr' => $update->getLidnr())) ?>">
                        <button type="submit"  class="btn btn-success"><span class="glyphicon glyphicon-ok aria-hidden="true"></span></button>
                    </form>
                </div></th>
        </tr>
        </thead>
        <tbody>
        <?php if ($update->getFirstName() !== null): ?>
            <tr><td>Voornaam</td><td><?= $update->getFirstName() ?></td></tr>
        <?php endif; ?>
        <?php if ($update->getMiddleName() !== null): ?>
            <tr><td>Tussenvoegsel</td><td><?= $update->getMiddleName() ?></td></tr>
        <?php endif; ?>
        <?php if ($update->getLastName() !== null): ?>
            <tr><td>Achternaam</td><td><?= $update->getLastName() ?></td></tr>
        <?php endif; ?>
        <?php if ($update->getInitials() !== null): ?>
            <tr><td>Initialen</td><td><?= $update->getInitials() ?></td></tr>
        <?php endif; ?>
        <?php if ($update->getBirth() !== null): ?>
            <tr><td>Geboortedatum</td><td><?= $update->getBirth() ?></td></tr>
        <?php endif; ?>
        <?php if ($update->getEmail() !== null): ?>
            <tr><td>Email</td><td><?= $update->getEmail() ?></td></tr>
        <?php endif; ?>
        <?php if ($update->getGeneration() !== null): ?>
            <tr><td>Generatie</td><td><?= $update->getGeneration() ?></td></tr>
        <?php endif; ?>
        <?php if ($update->getTuenumber() !== null): ?>
            <tr><td>Student nummer</td><td><?= $update->getTuenumber() ?></td></tr>
        <?php endif; ?>
        <?php if ($update->getStudy() !== null): ?>
            <tr><td>Studie</td><td><?= $update->getStudy() ?></td></tr>
        <?php endif; ?>
        </tbody>
    </table>
<?php endforeach; ?>
<?php if (empty($updates)): ?>
Er zijn geen update verzoeken.
<?php endif ?>
