<?php

declare(strict_types=1);

use Application\View\HelperTrait;
use Laminas\Form\View\Helper\FormMultiCheckbox;
use Laminas\View\Renderer\PhpRenderer;

/** @var PhpRenderer|HelperTrait $this */

$form->prepare();
$form->setAttribute('action', $this->url('settings/api-principals/edit', ['id' => $principal->getId()]));
$form->setAttribute('method', 'post');

$form->setAttribute('role', 'form');
$form->setAttribute('class', 'form-horizontal');
?>
<div class="row">
    <h1><?= $this->translate('Update API principal') ?></h1>
    <?= $this->form()->openTag($form) ?>

    <?php
    $element = $form->get('description');
    $element->setAttribute('class', 'form-control');
    $element->setAttribute('placeholder', $element->getLabel());
    ?>
    <div class="form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>">
        <label for="<?= $element->getName() ?>" class="control-label col-sm-2">
            <?= $element->getLabel() ?>
        </label>
        <div class="col-sm-10">
            <?= $this->formInput($element) ?>
            <?= $this->formElementErrors($element) ?>
        </div>
    </div>

    <?php
    $element = $form->get('token');
    $element->setAttribute('class', 'form-control');
    $element->setAttribute('placeholder', $element->getLabel());
    ?>
    <div class="form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>">
        <label for="<?= $element->getName() ?>" class="control-label col-sm-2">
            <?= $element->getLabel() ?>
        </label>
        <div class="col-sm-10">
            <?= $this->formInput($element) ?>
            <?= $this->formElementErrors($element) ?>
        </div>
    </div>

    <?php
    $element = $form->get('permissions');
    $element->setAttribute('placeholder', $element->getLabel());
    ?>
    <div class="form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>">
        <label for="<?= $element->getName() ?>" class="control-label col-sm-2">
            <?= $element->getLabel() ?>
        </label>
        <div class="col-sm-10">
            <div class="checkbox">
            <?= $this->formMultiCheckbox()->setSeparator('<br/>')->render($element, 'prepend') ?>
            </div>
            <?= $this->formElementErrors($element) ?>
        </div>
    </div>

    <?php
    $submit = $form->get('submit');
    $submit->setAttribute('class', 'btn btn-primary');
    $submit->setLabel($this->translate('Save'));
    ?>
    <div class="col-sm-offset-2 col-sm-10">
        <?= $this->formButton($submit) ?>
    </div>

    <?= $this->form()->closeTag() ?>
</div>
