name: "✨ Feature Request"
description: Suggest a feature or enhancement to improve the GEWIS database.
labels: ["Type: Idea"]
type: "Feature"
body:
    -   type: textarea
        id: feature
        attributes:
            label: What would you like?
            description: A clear description of the feature or enhancement wanted in the database.
            placeholder: I'd like to be able to...
        validations:
            required: true
    -   type: textarea
        id: reason
        attributes:
            label: Why is this needed?
            description: A clear description of why this would be useful to have in the database. 
            placeholder: I want this because...
    -   type: textarea
        id: other
        attributes:
            label: Other information
            placeholder: Any other details?

