<?php
$form->prepare();
$form->setAttribute('action', $this->url('user'));
$form->setAttribute('method', 'post');

$form->setAttribute('role', 'form');
$form->setAttribute('class', 'form-horizontal');
?>
<div class="row">
    <h1>Login</h1>
    <?= $this->form()->openTag($form) ?>

    <div class="alert alert-info" role="alert">
        <?= $usesldap ? 'This system uses GEWIS m-accounts. Learn more about m-accounts <a target="_blank" href="https://support.gewis.nl/kb/faq.php?id=36">here</a>.'
        : 'Please use your database credentials' ?>
    </div>

    <?php
    $element = $form->get('login');
    $element->setAttribute('class', 'form-control');
    $element->setAttribute('placeholder', $element->getLabel());
    ?>
    <div class="form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>">
        <label for="<?= $element->getName() ?>" class="control-label col-sm-2">
            <?= $element->getLabel() ?>
        </label>
        <div class="col-sm-10">
            <?= $this->formInput($element) ?>
            <?= $this->formElementErrors($element) ?>
        </div>
    </div>

    <?php
    $element = $form->get('password');
    $element->setAttribute('class', 'form-control');
    $element->setAttribute('placeholder', $element->getLabel());
    ?>
    <div class="form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>">
        <label for="<?= $element->getName() ?>" class="control-label col-sm-2">
            <?= $element->getLabel() ?>
        </label>
        <div class="col-sm-10">
            <?= $this->formInput($element) ?>
            <?= $this->formElementErrors($element) ?>
        </div>
    </div>

    <?php
    $submit = $form->get('submit');
    $submit->setLabel($submit->getValue());
    $submit->setAttribute('class', 'btn btn-primary');
    ?>
    <div class="col-sm-offset-2 col-sm-10">
        <?= $this->formButton($submit) ?>
    </div>

    <?= $this->form()->closeTag() ?>
</div>
