<?php

declare(strict_types=1);

use Application\View\HelperTrait;
use Laminas\View\Renderer\PhpRenderer;

/** @var PhpRenderer|HelperTrait $this */
?>
<script>
var urlTemplate = '<?= $this->url('organ/view', array(
    'type' => '__type__',
    'number' => '__number__',
    'point' => '__point__',
    'decision' => '__decision__',
    'sequence' => '__sequence__'
)) ?>';
var last = 0;
$(document).ready(function () {
    var maxResults = 32;
    var footer = $("#organ-result tfoot");
    var searchOrgan = function (term) {
        if (term.length >= 0) {
            $.ajax({
                dataType: 'json',
                url: '<?= $this->url('organ/default', array('action' => 'search')) ?>?q=' + term,
                context: document.body
            }).done(function (data) {
                var table = '';
                $.each(data.json, function (idx, organ) {
                    // create URL
                    var url = urlTemplate.replace('__type__', organ.meeting_type);
                    url = url.replace('__number__', organ.meeting_number);
                    url = url.replace('__point__', organ.decision_point);
                    url = url.replace('__decision__', organ.decision_number);
                    url = url.replace('__sequence__', organ.subdecision_sequence);

                    var link = '<a href="' + url + '" ';
                    link += 'style="display:block;height:100%;width:100%;">';

                    var decision = organ.meeting_type + ' '
                        + organ.meeting_number + '.'
                        + organ.decision_point + '.'
                        + organ.decision_number;
                    table += '<tr>';
                    table += '<td>' + link + organ.abbr + '</a></td>';
                    table += '<td>' + link + organ.name + '</a></td>';
                    table += '<td>' + link + decision + '</a></td>';
                    table += '</tr>';
                });
                $('#organ-result tbody').html(table);

                if (data.json.length >= maxResults) {
                    footer.show();
                } else {
                    footer.hide();
                }
            });
        } else {
            $('#organ-result tbody').html('');
        }
    };

    $('#organ-search').keyup(function (e) {
        term = $(e.target).val();
        searchOrgan(term);
    });
    searchOrgan('');
    footer.hide();
});
</script>
<form role="form">
    <div class="form-group">
        <label for=""><?= $this->translate('Search Organs') ?></label>
        <input type="text" class="form-control" placeholder="<?= $this->translate('Search') ?>" id="organ-search" autofocus>
    </div>
</form>

<table class="table table-hover" id="organ-result">
    <thead>
        <tr>
            <th><?= $this->translate('Abbreviation') ?></th>
            <th><?= $this->translate('Name') ?></th>
            <th><?= $this->translate('Decision') ?></th>
        </tr>
    </thead>
    <tbody>
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3">
                <?= $this->translate('There are too many results to display. Try filtering to see other results.') ?>
            </td>
        </tr>
    </tfoot>
</table>
