<?php

declare(strict_types=1);

use Application\View\HelperTrait;
use Laminas\View\Renderer\PhpRenderer;

/** @var PhpRenderer|HelperTrait $this */
?>
<h1><?= $foundation->getAbbr() ?> <small><?= $foundation->getName() ?></small></h1>

<h2><?= $this->translate('Members') ?></h2>
<ul>
<?php foreach ($foundation->getReferences() as $ref): ?>
    <?php if (!($ref instanceof \Database\Model\SubDecision\Installation)) continue; ?>
    <li>
        <a href="<?= $this->url('member/show', ['id' => $ref->getMember()->getLidnr()]) ?>">
            <?= $ref->getMember()->getFullName() ?>
        </a> <?= $this->translate('as') ?> <?= $ref->getFunction()->getName($this->plugin('translate')->getTranslator()) ?>
    </li>
<?php endforeach; ?>
</ul>
