<?php
$form->prepare();

$form->setAttribute('action', $this->url('address'));
$form->setAttribute('method', 'post');

$form->getAttribute('role', 'form');
$form->getAttribute('class', 'form-horizontal');
?>

<div class="row">

<h2>Export van adressen</h2>

<?= $this->form()->openTag($form) ?>

<?php
$element = $form->get('supremum');
$element->setAttribute('placeholder', $element->getLabel());
?>
<div class="form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>">
    <div class="col-sm-offset-2 col-sm-10">
        <div class="checkbox">
            <label>
                <?= $this->formCheckbox($element) ?>
                    Supremumfilter
            </label>
            <?= $this->formElementErrors($element) ?>
        </div>
    </div>
</div>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php
        $submit = $form->get('submit');
        $submit->setLabel($submit->getValue());
        $submit->setAttribute('class', 'btn btn-primary');
        ?>
        <?= $this->formButton($submit) ?>
    </div>
</div>

<?= $this->form()->closeTag() ?>

</div>
