<?php

declare(strict_types=1);

use Application\View\HelperTrait;
use Laminas\View\Renderer\PhpRenderer;
use User\Model\User;

/** @var PhpRenderer|HelperTrait $this */

$lang = $this->plugin('translate')->getTranslator()->getLocale();

echo $this->doctype();
?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('GEWIS Database')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/jquery-ui.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css', 'screen,print') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/modernizr.js')
            ->prependFile($this->basePath() . '/js/jquery-ui.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

<!-- check for date picker -->
<script>
$(document).ready(function() {
    if (!Modernizr.inputtypes.date) {
        $('input[type=date]').datepicker({
            dateFormat: 'yy-mm-dd'
        });
    }
});
</script>

    </head>
    <body>
<?php if (!$this->isModuleActive(['database', 'member', 'subscribe'])): ?>
        <nav class="navbar navbar-inverse navbar-static-top" role="navigation">
            <div class="container">
                <div class="navbar-header navbar-left pull-left">
                    <a href="/" class="navbar-brand">
                        <div class="gi gewis-base"></div>
                    </a>
                </div>
                <div class="navbar-header navbar-right pull-right">
                    <ul class="nav navbar-nav pull-left no-collapse">
                        <li class="dropdown pull-right">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                               aria-expanded="false">
                                <span class="glyphicon glyphicon-globe"></span>
                                <span class="sr-only"><?= $this->translate('Language Settings') ?></span>
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu language <?= ($lang == 'en') ? 'reverse' : '' ?> ">
                                <li>
                                    <a class="<?= ('en' === $lang) ? 'disabled' : '' ?>" href="<?= $this->url(
                                        'lang',
                                        ['lang' => 'en'],
                                    ) ?>">
                                        <span class="flag-icon flag-icon-en"
                                              style="background-image: url('<?= $this->basePath() ?>/img/en.svg');">
                                        </span>English
                                    </a>
                                </li>
                                <li>
                                    <a class="<?= ('nl' === $lang) ? 'disabled' : '' ?>" href="<?= $this->url(
                                        'lang',
                                        ['lang' => 'nl'],
                                    ) ?>">
                                        <span class="flag-icon flag-icon-nl"
                                              style="background-image: url('<?= $this->basePath() ?>/img/nl.svg');">
                                        </span>Nederlands
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <?php if (null !== ($identity = $this->identity())): ?>
                            <?php
                            if ($identity instanceof User) {
                                $name = $identity->getLogin();
                            } else {
                                if (1 === preg_match('/^((?:a|m)(?:[0-9]{4,5}))@GEWISWG\.GEWIS\.NL$/', $identity, $matches)) {
                                    $name = $matches[1];
                                } else {
                                    $name = $this->translate('User');
                                }
                            }
                            ?>
                            <li class="dropdown pull-right">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                                   aria-expanded="false">
                                    <?= $this->escapeHtml($name) ?>
                                    <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="<?= $this->url('passwordlogin/default', ['action' => 'logout']) ?>">
                                            <?= $this->translate('Log out') ?>
                                        </a>
                                    </li>
                                </ul>
                            </li>
                        <?php else: ?>
                            <li class="pull-right">
                                <a href="<?= $this->url('passwordlogin') ?>">
                                    <?= $this->translate('Log in') ?>
                                </a>
                            </li>
                        <?php endif; ?>
                    </ul>
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only"><?= $this->translate('Toggle Navigation') ?></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="collapse navbar-collapse">
                    <?php if (null !== $this->identity()): ?>
                        <ul class="nav navbar-nav navbar-left">
                            <li class="<?= $this->isModuleActive(['database', 'meeting']) ? 'active' : '' ?>">
                                <a href="<?= $this->url('meeting') ?>">
                                    <?= $this->translate('Meetings and Decisions') ?>
                                </a>
                            </li>
                            <li class="<?= $this->isModuleActive(['database', 'organ']) ? 'active' : '' ?>">
                                <a href="<?= $this->url('organ') ?>">
                                    <?= $this->translate('Organ') ?>
                                </a>
                            </li>
                            <li class="<?= $this->isModuleActive(['database', 'prospectivemember']) ? 'active' : '' ?>">
                                <a href="<?= $this->url('prospective-member') ?>">
                                    <?= $this->translate('Prospective Members') ?>
                                </a>
                            </li>
                            <li class="<?= $this->isModuleActive(['database', 'member']) ? 'active' : '' ?>">
                                <a href="<?= $this->url('member') ?>">
                                    <?= $this->translate('Members') ?>
                                </a>
                            </li>
                            <li class="<?= $this->isModuleActive(['database', 'export']) ? 'active' : '' ?>">
                                <a href="<?= $this->url('export') ?>">
                                    <?= $this->translate('Decision List') ?>
                                </a>
                            </li>
                            <li class="<?= $this->isModuleActive(['database', 'query']) ? 'active' : '' ?>">
                                <a href="<?= $this->url('query') ?>">
                                    <?= $this->translate('Query') ?>
                                </a>
                            </li>
                            <li class="<?= $this->isModuleActive(['database', 'settings']) ? 'active' : '' ?>">
                                <a href="<?= $this->url('settings') ?>">
                                    <?= $this->translate('Settings') ?>
                                </a>
                            </li>
                        </ul>
                    <?php endif; ?>
                </div>
            </div>
        </nav>
<?php else: ?>
        <nav role="navigation" class="navbar navbar-gewis navbar-static-top">
            <div class="container">
                <div class="navbar-header navbar-left pull-left">
                    <a href="/" class="navbar-brand">
                        <span class="gi gewis-base"></span>
                    </a>
                </div>
                <div class="navbar-header navbar-right pull-right">
                    <ul class="nav navbar-nav pull-left no-collapse">
                        <li class="dropdown pull-right">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                               aria-expanded="false">
                                <span class="glyphicon glyphicon-globe"></span>
                                <span class="sr-only"><?= $this->translate('Language Settings') ?></span>
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu language <?= ($lang == 'en') ? 'reverse' : '' ?> ">
                                <li>
                                    <a class="<?= ('en' === $lang) ? 'disabled' : '' ?>" href="<?= $this->url(
                                        'lang',
                                        ['lang' => 'en'],
                                    ) ?>">
                                        <span class="flag-icon flag-icon-en"
                                              style="background-image: url('<?= $this->basePath() ?>/img/en.svg');">
                                        </span>English
                                    </a>
                                </li>
                                <li>
                                    <a class="<?= ('nl' === $lang) ? 'disabled' : '' ?>" href="<?= $this->url(
                                        'lang',
                                        ['lang' => 'nl'],
                                    ) ?>">
                                        <span class="flag-icon flag-icon-nl"
                                              style="background-image: url('<?= $this->basePath() ?>/img/nl.svg');">
                                        </span>Nederlands
                                    </a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-left">
                        <li class="active">
                            <a href="#" role="button" class="hidden-sm hidden-xs">
                                <?= $this->translate('Subscribe') ?>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
<?php endif ?>
        <div class="container">
            <?= $this->flashMessenger()->render('default', ['alert', 'alert-dismissible', 'alert-info']) ?>
            <?= $this->flashMessenger()->render('error', ['alert', 'alert-dismissible', 'alert-danger']) ?>
            <?= $this->flashMessenger()->render('info', ['alert', 'alert-dismissible', 'alert-info']) ?>
            <?= $this->flashMessenger()->render('success', ['alert', 'alert-dismissible', 'alert-success']) ?>
            <?= $this->flashMessenger()->render('warning', ['alert', 'alert-dismissible', 'alert-warning']) ?>
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2013 - <?php echo date('Y') ?> by Studievereniging GEWIS</p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
