<?php
$lang = $this->plugin('translate')->getTranslator()->getLocale();

echo $this->doctype();
?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('GEWIS Database')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/jquery-ui.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css', 'screen,print') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/modernizr.js')
            ->prependFile($this->basePath() . '/js/jquery-ui.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

<!-- check for date picker -->
<script>
$(document).ready(function() {
    if (!Modernizr.inputtypes.date) {
        $('input[type=date]').datepicker({
            dateFormat: 'yy-mm-dd'
        });
    }
});
</script>

    </head>
    <body>
<?php if (!$this->isModuleActive(['database', 'member', 'subscribe'])): ?>
        <nav class="navbar navbar-inverse navbar-static-top" role="navigation">
            <div class="container">
                <div class="navbar-header navbar-left pull-left">
                    <a href="/" class="navbar-brand">
                        <div class="gi gewis-base"></div>
                    </a>
                </div>
                <div class="collapse navbar-collapse">
                    <?php if (null !== $this->identity()): ?>
                        <ul class="nav navbar-nav navbar-left">
                            <li class="<?= $this->isModuleActive(['database', 'meeting']) ? 'active' : '' ?>">
                                <a href="<?= $this->url('meeting') ?>">Vergaderingen en Besluiten</a>
                            </li>
                            <li class="<?= $this->isModuleActive(['database', 'organ']) ? 'active' : '' ?>">
                                <a href="<?= $this->url('organ') ?>">Organen</a>
                            </li>
                            <li class="<?= $this->isModuleActive(['database', 'prospectivemember']) ? 'active' : '' ?>">
                                <a href="<?= $this->url('prospective-member') ?>">Aankomende Leden</a>
                            </li>
                            <li class="<?= $this->isModuleActive(['database', 'member']) ? 'active' : '' ?>">
                                <a href="<?= $this->url('member') ?>">Leden</a>
                            </li>
                            <li class="<?= $this->isModuleActive(['database', 'export']) ? 'active' : '' ?>">
                                <a href="<?= $this->url('export') ?>">Besluitenlijst</a>
                            </li>
                            <li class="<?= $this->isModuleActive(['database', 'address']) ? 'active' : '' ?>">
                                <a href="<?= $this->url('address') ?>">Adressenlijst</a>
                            </li>
                            <li class="<?= $this->isModuleActive(['database', 'query']) ? 'active' : '' ?>">
                                <a href="<?= $this->url('query') ?>">Query</a>
                            </li>
                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                            <li class="<?= $this->isModuleActive(['database', 'settings']) ? 'active' : '' ?>">
                                <a href="<?= $this->url('settings') ?>">Settings</a>
                            </li>
                            <li class="<?= $this->isModuleActive(['user', 'user']) ? 'active' : '' ?>">
                                <a href="<?= $this->url('user/default', ['action' => 'logout']) ?>">Uitloggen</a>
                            </li>
                        </ul>
                    <?php else: ?>
                        <ul class="nav navbar-nav navbar-right">
                            <li>
                                <a href="<?= $this->url('user') ?>">Login</a>
                            </li>
                        </ul>
                    <?php endif; ?>
                </div>
            </div>
        </nav>
<?php else: ?>
        <nav role="navigation" class="navbar navbar-gewis navbar-static-top">
            <div class="container">
                <div class="navbar-header navbar-left pull-left">
                    <a href="/" class="navbar-brand">
                        <span class="gi gewis-base"></span>
                    </a>
                </div>
                <div class="navbar-header navbar-right pull-right">
                    <ul class="nav navbar-nav pull-left no-collapse">
                        <li class="dropdown pull-right">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                               aria-expanded="false">
                                <span class="glyphicon glyphicon-globe"></span>
                                <span class="sr-only"><?= $this->translate('Taalinstellingen') ?></span>
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu language <?= ($lang == 'en') ? 'reverse' : '' ?> ">
                                <li>
                                    <a class="<?= ('en' === $lang) ? 'disabled' : '' ?>" href="<?= $this->url(
                                        'lang',
                                        ['lang' => 'en'],
                                    ) ?>">
                                        <span class="flag-icon flag-icon-en"
                                              style="background-image: url('<?= $this->basePath() ?>/img/en.svg');">
                                        </span>English
                                    </a>
                                </li>
                                <li>
                                    <a class="<?= ('nl' === $lang) ? 'disabled' : '' ?>" href="<?= $this->url(
                                        'lang',
                                        ['lang' => 'nl'],
                                    ) ?>">
                                        <span class="flag-icon flag-icon-nl"
                                              style="background-image: url('<?= $this->basePath() ?>/img/nl.svg');">
                                        </span>Nederlands
                                    </a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-left">
                        <li class="active">
                            <a href="#" role="button" class="hidden-sm hidden-xs">
                                <?= $this->translate('Inschrijven') ?>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
<?php endif ?>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2013 - <?php echo date('Y') ?> by Studievereniging GEWIS</p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
