<?php

declare(strict_types=1);

use Application\View\HelperTrait;
use Laminas\View\Renderer\PhpRenderer;

/** @var PhpRenderer|HelperTrait $this */

$new = array();
// preprocessing, render the DateTime objects
foreach ($result as $row) {
    $row = array_map(
        function ($el) {
            if ($el instanceof \DateTime) {
                return $el->format('Y-m-d');
            } else {
                return $el;
            }
        },
        $row,
    );
    $new[] = $row;
}

// temporarily write csv to memory
$mem = fopen('php://memory', 'w');

fwrite($mem, "sep=;\n");

$first = true;
foreach ($new as $line) {
    if ($first) {
        $first = false;
        fputcsv($mem, array_keys($line), ';');
    }
    fputcsv($mem, $line, ';');
}

rewind($mem);

// send correct download headers
header('Content-Type: application/csv');
header('Content-Disposition: attachement; filename="query.csv"');

fpassthru($mem);
