<?php
$form->prepare();

$form->setAttribute('action', $this->url('query'));
$form->setAttribute('method', 'post');

$form->setAttribute('role', 'form');

echo $this->form()->openTag($form);
?>
<div class="form-group">
<?php
$element = $form->get('query');
$element->setAttribute('class', 'form-control');
?>
<?= $this->formLabel($element); ?>
<?= $this->formElementErrors($element) ?>
<?= $this->formTextarea($element) ?>
</div>

<?php
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');
?>
<?= $this->formButton($submit) ?>
<?= $this->form()->closeTag() ?>

<?php if (isset($result)): ?>
<hr />
<h2>Query result</h2>
<?php if (count($result) > 0): ?>
<table class="table table-hover table-condensed">
    <thead>
        <tr>
    <?php foreach (array_keys($result[0]) as $key): ?>
        <th><?= $key ?></th>
    <?php endforeach; ?>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($result as $row): ?>
        <tr>
        <?php foreach ($row as $col): ?>
            <?php if ($col instanceof \DateTime): ?>
            <td><?= $col->format('Y-m-d H:i:s') ?></td>
            <?php else: ?>
            <td><?= $col ?></td>
            <?php endif; ?>
        <?php endforeach; ?>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<?php else: ?>
    De query gaf geen resultaten.
<?php endif; ?>
<?php endif; ?>
