<?php

declare(strict_types=1);

use Application\View\HelperTrait;
use Laminas\View\Renderer\PhpRenderer;

/** @var PhpRenderer|HelperTrait $this */

// add codemirror
$this->headLink()->appendStylesheet($this->basePath() . '/css/codemirror.css');
$this->headScript()->appendFile($this->basePath() . '/js/codemirror-compressed.js');
?>
<script>
    $(document).ready(function () {
        var editor = CodeMirror.fromTextArea($('#query-editor')[0], {
            mode: 'text/x-sql',
            lineNumbers: true
        });
    });
</script>
<div class="row">
    <?php
    $form->prepare();

    $form->setAttribute('action', $this->url('query'));
    $form->setAttribute('method', 'post');

    $form->setAttribute('role', 'form');

    echo $this->form()->openTag($form);
    ?>
    <div class="col-md-9">
        <div class="form-group">
            <?php
            $element = $form->get('query');
            $element->setAttribute('class', 'form-control');
            $element->setAttribute('id', 'query-editor');
            ?>
            <?= $this->formLabel($element); ?>
            <?= $this->formElementErrors($element) ?>
            <?= $this->formTextarea($element) ?>
        </div>

        <?php
        $submit = $form->get('submit');
        $submit->setAttribute('class', 'btn btn-primary');
        ?>
        <?= $this->formButton($submit) ?>


        <div class="pull-right form-inline">
            <?php
            /* These are part of the QuerySave form */ ?>
            <div class="form-group">
                <input type="text" class="form-control input-small" name="category" placeholder="<?= $this->translate('Category') ?> (<?= $this->translate('optional') ?>)" value="<?= $query?->getCategory();?>">
                <input type="text" class="form-control input-small" name="name" placeholder="<?= $this->translate('Name') ?>" value="<?= $query?->getName();?>">
            </div>
            <button class="btn btn-success" name="submit_save" type="submit">
                <span class="glyphicon glyphicon-plus"></span> <?= $this->translate('Save') ?>
            </button>
        </div>
    </div>
    <div class="col-md-3">
        <h3><?= $this->translate('Stored Queries') ?></h3>
        <?php if (count($saved)): ?>
            <ul>
                <li>
                    <ul>
                        <?php
                        $prefix = null;
                        foreach ($saved as $savedquery):
                            if ($prefix !== $savedquery->getCategory()):
                                $prefix = $savedquery->getCategory();
                        ?>
                    </ul>
                </li>
                <li><b><?= $prefix ? $prefix : $this->translate('No category') ?></b>
                    <ul>
                        <?php endif; ?>
                        <li>
                            <a href="<?= $this->url('query/show', ['query' => $savedquery->getId()]) ?>">
                                <?= $savedquery->getName() ?>
                            </a>
                        </li>
                        <?php endforeach; ?>
                    </ul>
                </li>
            </ul>
        <?php else: ?>
            <em><?= $this->translate('There are no saved queries.') ?></em>
            <br/><br/>
        <?php endif; ?>

        <p>
            <?= $this->translate('Saving a query with a previously used name will overwrite the previously saved query and update its category.') ?>
        </p>

        <p>
            <?=
            sprintf(
            $this->translate('For an overview of how you can use the Doctrine Query Language (DQL) please refer to %sits documentation%s.'),
                '<a href="https://www.doctrine-project.org/projects/doctrine-orm/en/current/reference/dql-doctrine-query-language.html">',
                '</a>',
            )
            ?>
        </p>

        <p>
        <?= $this->translate('The entities that you can use:') ?>
        </p>
        <ul>
            <?php
            sort($entities);
            foreach ($entities as $entity): ?>
                <li><?= $entity; ?></li>
            <?php endforeach; ?>
        </ul>
    </div>
    <?= $this->form()->closeTag() ?>
</div>
<?php  if (isset($result)): ?>
    <hr/>
    <div class="row">
        <div class="col-md-6">
            <h2><?= $this->translate('Query Result') ?></h2>
        </div>
        <div class="col-md-6">
            <br/>
            <?php
            $exportform->prepare();

            $exportform->setAttribute('action', $this->url('query/export'));
            $exportform->setAttribute('method', 'post');

            $exportform->setAttribute('role', 'form');
            $exportform->setAttribute('class', 'form-inline');

            $exportform->get('query')->setValue($form->get('query')->getValue());

            echo $this->form()->openTag($exportform);
            ?>
            <?= $this->formHidden($exportform->get('query')) ?>
            <?php
                $element = $exportform->get('name');
                if (null !== $query) {
                    $element->setValue($query->getCategory() . ' - ' . $query->getName());
                }
            ?>
            <?= $this->formElement($element) ?>
            <div class="form-group">
                <?php
                $element = $exportform->get('type');
                $element->setAttribute('class', 'form-control')
                ?>
                <?= $this->formElement($element) ?>
            </div>
            <?php
            $submit = $exportform->get('submit');
            $submit->setAttribute('class', 'btn btn-primary');
            ?>
            <?= $this->formButton($submit) ?>
            <?= $this->form()->closeTag() ?>
        </div>
    </div>
    <?php
    if (count($result) > 0): ?>
        <table class="table table-hover table-condensed">
            <thead>
            <tr>
                <?php foreach (array_keys($result[0]) as $key): ?>
                    <th><?= $key ?></th>
                <?php endforeach; ?>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($result as $row): ?>
                <tr>
                    <?php foreach ($row as $col): ?>
                        <?php if ($col instanceof \DateTime): ?>
                            <td><?= $col->format('Y-m-d') ?></td>
                        <?php else: ?>
                            <td><?= $col ?></td>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    <?php else: ?>
        <?= $this->translate('The query did not return any results.') ?>
    <?php endif; ?>
<?php endif; ?>
