<?php

declare(strict_types=1);

use Application\View\HelperTrait;
use Database\Model\SubDecision\Board\Installation as BoardInstallationModel;
use Laminas\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer|HelperTrait $this
 * @var BoardInstallationModel[] $installs
 */

$translator = $this->plugin('translate')->getTranslator();

$arrInstalls = array();

foreach ($installs as $key => $install) {
    $arrInstalls[$key] = array(
        'meeting_type' => $install->getDecision()->getMeeting()->getType()->value,
        'meeting_number' => $install->getDecision()->getMeeting()->getNumber(),
        'decision_point' => $install->getDecision()->getPoint(),
        'decision_number' => $install->getDecision()->getNumber(),
        'subdecision_sequence' => $install->getSequence(),
    );
}
?>
<script>
$(document).ready(function() {
    var discharges = <?= json_encode($arrInstalls); ?>;
    $('.board-discharge-slot').change(function() {
        var data = discharges[$('.board-discharge-slot:checked').val()];
        $('#install-board-meeting-type').val(data['meeting_type']);
        $('#install-board-meeting-number').val(data['meeting_number']);
        $('#install-board-decision-point').val(data['decision_point']);
        $('#install-board-decision-number').val(data['decision_number']);
        $('#install-board-subdecision-sequence').val(data['subdecision_sequence']);
        $('#board-discharge-submit').prop('disabled', false);
    });
});
</script>
<?php
$form->prepare();

$form->setAttribute('action', $this->url('meeting/decision/form', array('form' => 'board_discharge')));
$form->setAttribute('method', 'post');

$form->setAttribute('role', 'form');
$form->setAttribute('class', 'form-horizontal');
?>
<?= $this->form()->openTag($form) ?>
<?php
// default hidden elements for the meeting and decision reference
$fs = $form->get('meeting')
?>
<?= $this->formHidden($fs->get('type')) ?>
<?= $this->formHidden($fs->get('number')) ?>
<?= $this->formHidden($form->get('point')) ?>
<?= $this->formHidden($form->get('decision')) ?>

<div class="form-group">
<?php
$fs = $form->get('subdecision');
$fs->get('meeting_type')->setAttribute('id', 'install-board-meeting-type');
$fs->get('meeting_number')->setAttribute('id', 'install-board-meeting-number');
$fs->get('decision_point')->setAttribute('id', 'install-board-decision-point');
$fs->get('decision_number')->setAttribute('id', 'install-board-decision-number');
$fs->get('sequence')->setAttribute('id', 'install-board-subdecision-sequence');
?>
<?= $this->formHidden($fs->get('meeting_type')) ?>
<?= $this->formHidden($fs->get('meeting_number')) ?>
<?= $this->formHidden($fs->get('decision_point')) ?>
<?= $this->formHidden($fs->get('decision_number')) ?>
<?= $this->formHidden($fs->get('sequence')) ?>
    <label class="col-md-2 control-label">
        <?= $this->translate('Board Member(s) to Discharge') ?>
    </label>
    <div class="col-md-10">
<?php foreach ($installs as $key => $install): ?>
    <div class="radio">
        <label>
            <input type="radio" name="board-discharge-slot" class="board-discharge-slot" value="<?= $key ?>">
            <?= $install->getMember()->getFullName() ?> <?= $this->translate('as') ?>
            <?= $install->getFunction()->getName($translator) ?><br>
        </label>
    </div>
<?php endforeach ?>
    </div>
</div>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php
        $submit = $form->get('submit');
        $submit->setLabel($submit->getValue());
        $submit->setAttribute('class', 'btn btn-primary');
        $submit->setAttribute('id', 'board-discharge-submit');
        $submit->setAttribute('disabled', 'disabled');
        ?>
        <?= $this->formButton($submit) ?>
    </div>
</div>

<?= $this->form()->closeTag() ?>
