<script>
$(document).ready(function() {
    $('#board-member .member-autocomplete').autocomplete({
        minLength: 2, // at least two chars before request
        delay: 0, // no delay before request
        source: function (rq, response) {
            // make an AJAX request
            $.ajax({
                dataType: 'json',
                url: '<?= $this->url('member/searchFiltered') ?>?q=' + rq.term,
                context: document.body
            }).done(function(data) {
                var ret = [];
                $.each(data.json, function (idx, member) {
                    // assemble member name and add to list
                    var name = member.fullName + ' (' + member.lidnr + ')';

                    ret.push({
                        label: name,
                        value: name,
                        id: member.lidnr
                    });
                });

                // show data
                response(ret);
            });
        },
        select: function (event, ui) {
            $(event.target).parent().find("input.member-lidnr").val(ui.item.id);
        }
    })
});
</script>
<?php
$form->prepare();

$form->setAttribute('action', $this->url('meeting/decision/form', array('form' => 'board_install')));
$form->setAttribute('method', 'post');

$form->setAttribute('role', 'form');
$form->setAttribute('class', 'form-horizontal');
?>
<?= $this->form()->openTag($form) ?>
<?php
// default hidden elements for the meeting and decision reference
$fs = $form->get('meeting')
?>
<?= $this->formHidden($fs->get('type')) ?>
<?= $this->formHidden($fs->get('number')) ?>
<?= $this->formHidden($form->get('point')) ?>
<?= $this->formHidden($form->get('decision')) ?>


<div class="form-group" id="board-member">
<?php
$fs = $form->get('member');
$element = $fs->get('name');
$element->setAttribute('class', 'form-control member-autocomplete');
$element->setAttribute('placeholder', $element->getLabel());
$element->setLabelAttributes(array(
    'class' => 'col-md-2 control-label'
));
?>
    <?= $this->formLabel($element) ?>
    <div class="col-md-10">
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element) ?>
        <?php
        // hidden element for actual membership number
        $el = $fs->get('lidnr');
        $el->setAttribute('class', 'member-lidnr');
        ?>
        <?= $this->formHidden($el) ?>
        <?= $this->formElementErrors($el) ?>
    </div>
</div>

<div class="form-group">
<?php
$element = $form->get('function');
$element->setAttribute('class', 'form-control');
$element->setAttribute('placeholder', $element->getLabel());
$element->setLabelAttributes(array(
    'class' => 'col-md-2 control-label'
));
?>
    <?= $this->formLabel($element) ?>
    <div class="col-md-10">
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>

<div class="form-group">
<?php
$element = $form->get('date');
$element->setAttribute('class', 'form-control');
$element->setAttribute('placeholder', $element->getLabel());
$element->setLabelAttributes(array(
    'class' => 'col-md-2 control-label'
));
?>
    <?= $this->formLabel($element) ?>
    <div class="col-md-10">
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php
        $submit = $form->get('submit');
        $submit->setLabel($submit->getValue());
        $submit->setAttribute('class', 'btn btn-primary');
        ?>
        <?= $this->formButton($submit) ?>
    </div>
</div>

<?= $this->form()->closeTag() ?>
