<script>
$(document).ready(function () {
    $('#abolish-organ').autocomplete({
            minLength: 2, // at least two chars before request
            delay: 0, // no delay before request
            source: function (rq, response) {
                // make an AJAX request
                $.ajax({
                    dataType: 'json',
                    url: '<?= $this->url('organ/default', array('action' => 'search')) ?>?q=' + rq.term,
                    context: document.body
                }).done(function(data) {
                    console.log(data);
                    var ret = [];
                    $.each(data.json, function (idx, organ) {
                        // assemble organ info and add to list
                        var decision = organ.meeting_type + ' '
                                     + organ.meeting_number + '.'
                                     + organ.decision_point + '.'
                                     + organ.decision_number;

                        var name = organ.abbr + ' (' + organ.name + ', ' + decision + ')';

                        ret.push({
                            label: name,
                            value: name,
                            id: decision
                        });
                    });

                    // show data
                    response(ret);
                });
            },
            select: function (event, ui) {
                console.log($(event.target).parent());
                $(event.target).parent().find("input.organ-decision").val(ui.item.id);
            }
        });
});
</script>
<?php
$form = $this->form;
$form->prepare();

$form->setAttribute('action', $this->url('meeting/decision/form', array('form' => 'abolish')));
$form->setAttribute('method', 'post');

$form->setAttribute('role', 'form');

echo $this->form()->openTag($form);
?>
<?php /* first do hidden elements */ ?>
<?php
$fs = $form->get('meeting')
?>
<?= $this->formHidden($fs->get('type')) ?>
<?= $this->formHidden($fs->get('number')) ?>
<?= $this->formHidden($form->get('point')) ?>
<?= $this->formHidden($form->get('decision')) ?>
<div class="form-group">
<?php
$element = $form->get('name');
$element->setAttribute('class', 'form-control');
$element->setAttribute('id', 'abolish-organ');
$element->setAttribute('placeholder', 'Orgaan');
?>
    <?= $this->formLabel($element) ?>
    <?= $this->formInput($element) ?>
    <?= $this->formElementErrors($element) ?>
    <input type="hidden" class="organ-decision">
</div>

<?php
$submit = $form->get('submit');
$submit->setLabel('Hef orgaan op');
$submit->setAttribute('class', 'btn btn-primary');
?>
<?= $this->formButton($submit) ?>

<?= $this->form()->closeTag(); ?>
