<?php

declare(strict_types=1);

use Application\View\HelperTrait;
use Database\Form\Annulment as AnnulmentForm;
use Laminas\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer|HelperTrait $this
 * @var AnnulmentForm $form
 */
?>
<script>
$(document).ready(function() {
    $('#annulment-decision').autocomplete({
        minLength: 2,
        delay: 0,
        source: function(rq, response) {
            $.ajax({
                dataType: 'json',
                url: '<?= $this->url('meeting/decision/search') ?>?q=' + rq.term,
                context: document.body
            }).done(function(data) {
                var ret = [];
                $.each(data.json, function(idx, decision) {
                    var num = decision.meeting_type + " " + decision.meeting_number;
                    num += "." + decision.decision_point + "." + decision.decision_number;
                    decision.num = num;
                    var content = decision.content;
                    if (content.length > 100) {
                        content = content.substring(0, 100) + "...";
                    }
                    var result = num + " " + content;

                    ret.push({
                        label: result,
                        value: num,
                        id: decision
                    });
                })

                response(ret);
            });
        },
        select: function(event, ui) {
            var decision = ui.item.id;
            $('#annulment-meeting-type').val(decision.meeting_type);
            $('#annulment-meeting-number').val(decision.meeting_number);
            $('#annulment-decision-point').val(decision.decision_point);
            $('#annulment-number').val(decision.decision_number);
            $('.annulment-decision-num').text(decision.num);
            $('.annulment-decision-content').text(decision.content);
            $('.annulment-decision-display').show();
            $('#annulment-decision-button').prop('disabled', false);
        }
    });
});

</script>
<?php
$form->prepare();

$form->setAttribute('action', $this->url('meeting/decision/form', array('form' => 'annulment')));
$form->setAttribute('method', 'post');

$form->setAttribute('role', 'form');

echo $this->form()->openTag($form);
?>
<?php /* first do hidden elements */ ?>
<?php
$fs = $form->get('meeting')
?>
<?= $this->formHidden($fs->get('type')) ?>
<?= $this->formHidden($fs->get('number')) ?>
<?= $this->formHidden($form->get('point')) ?>
<?= $this->formHidden($form->get('decision')) ?>
<?php
$fs = $form->get('fdecision');
?>
<?php
$element = $fs->get('meeting_type');
$element->setAttribute('id', 'annulment-meeting-type');
?>
<?= $this->formHidden($element) ?>
<?php
$element = $fs->get('meeting_number');
$element->setAttribute('id', 'annulment-meeting-number');
?>
<?= $this->formHidden($element) ?>
<?php
$element = $fs->get('point');
$element->setAttribute('id', 'annulment-decision-point');
?>
<?= $this->formHidden($element) ?>
<?php
$element = $fs->get('number');
$element->setAttribute('id', 'annulment-number');
?>
<?= $this->formHidden($element) ?>
<div class="form-group">
<?php
$element = $form->get('name');
$element->setAttribute('class', 'form-control');
$element->setAttribute('id', 'annulment-decision');
$element->setAttribute('placeholder', $this->translate('Decision'));
?>
    <?= $this->formLabel($element) ?>
    <?= $this->formInput($element) ?>
    <?= $this->formElementErrors($element) ?>
</div>

<p class="annulment-decision-display" style="display: none;">
<strong><?= $this->translate('Decision') ?></strong> <strong class="annulment-decision-num"></strong>: <span class="annulment-decision-content"></span>
</p>

<?php
$submit = $form->get('submit');
$submit->setLabel($this->translate('Annul Decision'));
$submit->setAttribute('class', 'btn btn-primary');
$submit->setAttribute('id', 'annulment-decision-button');
$submit->setAttribute('disabled', 'disabled');
?>
<?= $this->formButton($submit) ?>

<?= $this->form()->closeTag(); ?>
