<?php
$form = $this->form;
$form->prepare();

$form->setAttribute('action', $this->url('meeting/decision/form', array('form' => 'budget')));
$form->setAttribute('method', 'post');

$form->setAttribute('role', 'form');

echo $this->form()->openTag($form);
?>
<div class="form-group">
<?php
$element = $form->get('type');
$element->setAttribute('class', 'form-control');

?>
    <?= $this->formLabel($element) ?>
    <?= $this->formSelect($element) ?>
    <?= $this->formElementErrors($element) ?>
</div>

<div class="form-group">
<?php
$element = $form->get('name');
$element->setAttribute('class', 'form-control');
$element->setAttribute('placeholder', 'Naam');
?>
    <?= $this->formLabel($element) ?>
    <?= $this->formInput($element) ?>
    <?= $this->formElementErrors($element) ?>
</div>

<div class="form-group">
<?php
$element = $form->get('date');
$element->setAttribute('class', 'form-control');
$element->setAttribute('placeholder', 'Datum begroting / afrekening');
?>
    <?= $this->formLabel($element) ?>
    <?= $this->formInput($element) ?>
    <?= $this->formElementErrors($element) ?>
</div>

<div class="form-group">
<?php
$element = $form->get('author');
$element->setAttribute('class', 'form-control');
$element->setAttribute('placeholder', 'Auteur');
?>
    <?= $this->formLabel($element) ?>
    <?= $this->formInput($element) ?>
    <?= $this->formElementErrors($element) ?>
</div>

<div class="form-group">
<?php
$element = $form->get('version');
$element->setAttribute('class', 'form-control');
$element->setAttribute('placeholder', 'Versie');
?>
    <?= $this->formLabel($element) ?>
    <?= $this->formInput($element) ?>
    <?= $this->formElementErrors($element) ?>
</div>

<div class="form-group">
<?php
$element = $form->get('organ');
$element->setAttribute('class', 'form-control');
$element->setAttribute('placeholder', 'Orgaan');
?>
    <?= $this->formLabel($element) ?>
    <?= $this->formInput($element) ?>
    <?= $this->formElementErrors($element) ?>
</div>

<div class="form-group">
<?php
$element = $form->get('approve');
$element->setLabelAttributes(array('class' => 'radio-inline'));
?>
    <?= $this->formRadio($element) ?>
    <?= $this->formElementErrors($element) ?>
</div>


<?php
$submit = $form->get('submit');
$submit->setLabel('Submit');
$submit->setAttribute('class', 'btn btn-primary');
?>
<?= $this->formButton($submit) ?>

<?= $this->form()->closeTag(); ?>
