<?php

declare(strict_types=1);

use Application\View\HelperTrait;
use Laminas\View\Renderer\PhpRenderer;

/** @var PhpRenderer|HelperTrait $this */

if (isset($success) && $success): ?>
    <?= $this->translate('Meeting added successfully!') ?>
<?php else: ?>
<?php
$form = $this->form;
$form->prepare();

$form->setAttribute('action', $this->url('meeting/create'));
$form->setAttribute('method', 'post');

$form->setAttribute('role', 'form');
$form->setAttribute('class', 'form-horizontal');

echo $this->form()->openTag($form);
?>
<h1><?= $this->translate('Add Meeting') ?></h1>
<div class="form-group">
<?php
$element = $form->get('type');
$element->setAttribute('class', 'form-control');
$element->setLabelAttributes(array(
    'class' => 'col-sm-2'
));
?>
    <?= $this->formLabel($element) ?>
    <div class="col-sm-10">
        <?= $this->formSelect($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>
<div class="form-group">
<?php
$element = $form->get('number');
$element->setAttribute('class', 'form-control');
$element->setAttribute('placeholder', $this->translate('Meeting Number'));
$element->setLabelAttributes(array(
    'class' => 'col-sm-2'
));
?>
    <?= $this->formLabel($element) ?>
    <div class="col-sm-10">
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>
<div class="form-group">
<?php
$element = $form->get('date');
$element->setAttribute('class', 'form-control');
$element->setAttribute('placeholder', $this->translate('Meeting Date'));
$element->setLabelAttributes(array(
    'class' => 'col-sm-2'
));
?>
    <?= $this->formLabel($element) ?>
    <div class="col-sm-10">
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php
        $submit = $form->get('submit');
        $submit->setLabel('Submit');
        $submit->setAttribute('class', 'btn btn-primary');
        ?>
        <?= $this->formButton($submit) ?>
    </div>
</div>

<?= $this->form()->closeTag(); ?>
<?php endif; ?>
