<?php
use Database\Model\Meeting;
?>
<?php if (isset($form)): ?>
<?php
switch ($type) {
case 'budget':
    echo $this->partial('database/meeting/budgetform', array(
        'form' => $form
    ));
    break;
case 'other':
    echo $this->partial('database/meeting/otherform', array(
        'form' => $form
    ));
    break;
}
?>
<?php else: ?>
<?php
$meeting = $decision->getMeeting();
$decisionNum = $meeting->getType() . ' ' . $meeting->getNumber() . '.' . $decision->getPoint() . '.' . $decision->getNumber();
?>
<h2>Besluit <?= $decisionNum ?> luidt als volgt:</h1>
<?php foreach ($decision->getSubdecisions() as $subdecision): ?>
    <?= $subdecision->getContent() ?>
<?php endforeach; ?>
<?php endif; ?>
