<?php
use Database\Model\Meeting;
function showType($type)
{
    switch ($type) {
    case Meeting::TYPE_BV:
        return 'BV';
    case Meeting::TYPE_AV:
        return 'AV';
    case Meeting::TYPE_VV:
        return 'VV';
    case Meeting::TYPE_VIRT:
        return 'Virt';
    }
}
?>
<h1>Toevoegen besluit <?= showType($meeting->getType()) . ' ' ?>
<?= $meeting->getNumber() ?>.<?= $point ?>.<?= $decision ?>
</h1>

<ul class="nav nav-pills" id="decision-tabs">
    <li class="active"><a href="#begroting" data-toggle="tab">Begroting / Afrekening</a></li>
    <li><a href="#oprichting" data-toggle="tab">Oprichting</a></li>
    <li><a href="#opheffing" data-toggle="tab">Opheffing</a></li>
    <li><a href="#installatie" data-toggle="tab">Installatie / Decharge</a></li>
    <li><a href="#functiewissel" data-toggle="tab">Functiewissel</a></li>
    <li><a href="#overig" data-toggle="tab">Overig</a></li>
</ul>

<br />

<div class="tab-content">
    <div class="tab-pane active" id="begroting">
    <?= $this->partial('database/meeting/budgetform', array(
        'form' => $forms['budget']
    )); ?>
    </div>
    <div class="tab-pane" id="oprichting">
    <?= $this->partial('database/meeting/foundationform', array(
        'form' => $forms['foundation']
    )); ?>
    </div>
    <div class="tab-pane" id="opheffing">
    <?= $this->partial('database/meeting/abolishform', array(
        'form' => $forms['abolish']
    )); ?>
    </div>
    <div class="tab-pane" id="installatie">
    <?= $this->partial('database/meeting/installform', array(
        'form' => $forms['install']
    )); ?>
    </div>
    <div class="tab-pane" id="functiewissel">
        Here: use AJAX to get the members of the committee. Then make nice
        interface for changing functions.
    </div>
    <div class="tab-pane" id="overig">
        Overig
    </div>
</div>
