<?php
use Database\Model\Meeting;
?>
<?php if (isset($form)): ?>
<?php
switch ($type) {
case 'budget':
    echo $this->partial('database/meeting/budgetform', array(
        'form' => $form
    ));
    break;
case 'foundation':
    echo $this->partial('database/meeting/foundationform', array(
        'form' => $form
    ));
    break;
case 'destroy':
    echo $this->partial('database/meeting/destroyform', array(
        'form' => $form
    ));
    break;
case 'board_install':
    echo $this->partial('database/meeting/board/installform', array(
        'form' => $form
    ));
    break;
case 'board_discharge':
    echo $this->partial('database/meeting/board/dischargeform', array(
        'form' => $form,
        'installs' => $installs
    ));
    break;
case 'board_release':
    echo $this->partial('database/meeting/board/releaseform', array(
        'form' => $form,
        'installs' => $installs
    ));
    break;
case 'other':
    echo $this->partial('database/meeting/otherform', array(
        'form' => $form
    ));
    break;
}
?>
<?php else: ?>
<?php
$meeting = $decision->getMeeting();
$decisionNum = $meeting->getType() . ' ' . $meeting->getNumber() . '.' . $decision->getPoint() . '.' . $decision->getNumber();
?>
<h2>Besluit <?= $decisionNum ?> luidt als volgt:</h1>
<?php foreach ($decision->getSubdecisions() as $subdecision): ?>
    <?= $subdecision->getContent() ?>
<?php endforeach; ?>
<br />
    <a href="<?= $this->url('meeting/view', array('type' => $meeting->getType(), 'number' => $meeting->getNumber())) ?>">Terug naar <?= $meeting->getType() ?> <?= $meeting->getNumber() ?></a>
<?php endif; ?>
