<?php
use Database\Model\Meeting;
?>
<?php if (isset($error) && $error): ?>
<h1>Dit besluit bestaat al</h1>
<?php else: ?>
<h1>Toevoegen besluit <?= $meeting->getType() . ' ' ?>
<?= $meeting->getNumber() ?>.<?= $point ?>.<?= $decision ?>
</h1>

<ul class="nav nav-pills" id="decision-tabs">
    <li class="active"><a href="#begroting" data-toggle="tab">Begroting / Afrekening</a></li>
    <li><a href="#oprichting" data-toggle="tab">Oprichting</a></li>
    <li><a href="#opheffing" data-toggle="tab">Opheffing</a></li>
    <li><a href="#installatie" data-toggle="tab">Installatie / Decharge</a></li>
    <li><a href="#vernietig" data-toggle="tab">Vernietig besluit</a></li>
    <li><a href="#overig" data-toggle="tab">Overig</a></li>
</ul>

<br />

<div class="tab-content">
    <div class="tab-pane active" id="begroting">
    <?= $this->partial('database/meeting/budgetform', array(
        'form' => $forms['budget']
    )); ?>
    </div>
    <div class="tab-pane" id="oprichting">
    <?= $this->partial('database/meeting/foundationform', array(
        'form' => $forms['foundation']
    )); ?>
    </div>
    <div class="tab-pane" id="opheffing">
    <?= $this->partial('database/meeting/abolishform', array(
        'form' => $forms['abolish']
    )); ?>
    </div>
    <div class="tab-pane" id="installatie">
    <?= $this->partial('database/meeting/installform', array(
        'form' => $forms['install'],
        'memberfunction' => $memberfunction
    )); ?>
    </div>
    <div class="tab-pane" id="vernietig">
    <?= $this->partial('database/meeting/destroyform', array(
        'form' => $forms['destroy'],
    )); ?>
    </div>
    <div class="tab-pane" id="overig">
    <?= $this->partial('database/meeting/otherform', array(
        'form' => $forms['other']
    )); ?>
    </div>
</div>
<?php endif ?>
