<?php

declare(strict_types=1);

use Application\Model\Enums\AppLanguages;
use Application\View\HelperTrait;
use Database\Model\Decision as DecisionModel;
use Database\Model\Meeting;
use Laminas\View\Renderer\PhpRenderer;

/** @var PhpRenderer|HelperTrait $this */
$translator = $this->plugin('translate')->getTranslator();
?>
<?php if (isset($form)): ?>
<?php
switch ($type) {
case 'budget':
    echo $this->partial('database/meeting/budgetform', array(
        'form' => $form
    ));
    break;
case 'foundation':
    echo $this->partial('database/meeting/foundationform', array(
        'form' => $form
    ));
    break;
case 'organ_regulation':
    echo $this->partial('database/meeting/regulationform', array(
        'form' => $form
    ));
    break;
case 'annulment':
    echo $this->partial('database/meeting/annulmentform', array(
        'form' => $form
    ));
    break;
case 'board_install':
    echo $this->partial('database/meeting/board/installform', array(
        'form' => $form
    ));
    break;
case 'board_discharge':
    echo $this->partial('database/meeting/board/dischargeform', array(
        'form' => $form,
        'installs' => $installs
    ));
    break;
case 'board_release':
    echo $this->partial('database/meeting/board/releaseform', array(
        'form' => $form,
        'installs' => $installs_filtered
    ));
    break;
case 'key_grant':
    echo $this->partial('database/meeting/key/grantform', array(
        'form' => $form,
    ));
    break;
case 'key_withdraw':
    echo $this->partial('database/meeting/key/withdrawform', array(
        'form' => $form,
        'grants' => $grants
    ));
    break;
case 'minutes':
    echo $this->partial('database/meeting/minutesform', array(
        'form' => $form
    ));
    break;
case 'other':
    echo $this->partial('database/meeting/otherform', array(
        'form' => $form
    ));
    break;
}
?>
<?php else: ?>
<?php
/** @var DecisionModel $decision */
?>
<h1><?= $this->translate('Decision') ?> <?= $decision->getHash() ?> <?= $this->translate('reads as follows:') ?></h1>
<?php foreach (AppLanguages::cases() as $language): ?>
    <p>
        <?php foreach ($decision->getSubdecisions() as $subdecision): ?>
            <?= $this->escapeHtml($subdecision->getTranslatedContent($translator, $language)) ?>
        <?php endforeach; ?>
    </p>
    <br>
<?php endforeach; ?>

<br>
<span class="hidden" id="decision-contents">
    <?= sprintf(
        '\decision[%s]{%s}',
        $this->escapeHtml($decision->getTranslatedContent($translator, AppLanguages::English, true)),
        $this->escapeHtml($decision->getTranslatedContent($translator, AppLanguages::Dutch, true)),
) ?>
</span>

<button onclick="copyDecision()" class="btn btn-info">
    <span class="glyphicon glyphicon-floppy-disk"></span> <?= $this->translate('Copy Decision')?>
</button>
<a href="<?= $this->url(
    'meeting/view',
    [
        'type' => $decision->getMeetingType()->value,
        'number' => $decision->getMeetingNumber(),
    ],
) ?>" class="btn btn-success">
    <?=
    sprintf(
        $this->translate('Back to %s %d'),
        $decision->getMeetingType()->value,
        $decision->getMeetingNumber(),
    )
    ?>
</a>
    <script>
        function copyDecision() {
            navigator.clipboard.writeText(document.getElementById('decision-contents').textContent.trim());
        }
    </script>
<?php endif; ?>
