<h1>Toevoegen besluit</h1>

<ul class="nav nav-pills" id="decision-tabs">
    <li class="active"><a href="#begroting" data-toggle="tab">Begroting / Afrekening</a></li>
    <li><a href="#oprichting" data-toggle="tab">Oprichting</a></li>
    <li><a href="#opheffing" data-toggle="tab">Opheffing</a></li>
    <li><a href="#installatie" data-toggle="tab">Installatie / Decharge</a></li>
    <li><a href="#functiewissel" data-toggle="tab">Functiewissel</a></li>
    <li><a href="#overig" data-toggle="tab">Overig</a></li>
</ul>

<br />

<div class="tab-content">
    <div class="tab-pane active" id="begroting">
    <?= $this->partial('database/meeting/budgetform', array(
        'form' => $budgetform
    )); ?>
    </div>
    <div class="tab-pane" id="oprichting">
    <?= $this->partial('database/meeting/foundationform', array(
        'form' => $foundationform
    )); ?>
    </div>
    <div class="tab-pane" id="opheffing">
    <?= $this->partial('database/meeting/abolishform', array(
        'form' => $abolishform
    )); ?>
    </div>
    <div class="tab-pane" id="installatie">
    <?= $this->partial('database/meeting/installform', array(
        'form' => $installform
    )); ?>
    </div>
    <div class="tab-pane" id="functiewissel">
        Functiewissel
    </div>
    <div class="tab-pane" id="overig">
        Overig
    </div>
</div>
