<?php
use Database\Model\Meeting;
?>
<?php if (isset($error) && $error): ?>
<h1>Besluit kan niet verwijderd worden</h1>
Er bestaan nog besluiten die naar dit besluit verwijzen.
<?php else: ?>
<?php if (!isset($form)): ?>
<p>Besluit verwijderd.</p>
<a href="<?= $this->url('meeting/view', array('type' => $type->value, 'number' => $number)) ?>">Terug naar <?= $type->value ?> <?= $number ?></a>
<?php else:
$form->prepare();

$form->setAttribute('action', $this->url('meeting/decision/delete', array(
    'type' => $type->value,
    'number' => $number,
    'point' => $point,
    'decision' => $decision
)));
$form->setAttribute('method', 'post');
$form->setAttribute('role', 'form');

echo $this->form()->openTag($form);
?>

<p>
Weet je zeker dat besluit
<?= $type->value . " $number.$point.$decision " ?>
verwijderd moet worden?
</p>
<div class="form-group">
<?php
$submit = $form->get('submit_yes');
$submit->setLabel('Ja');
$submit->setAttribute('class', 'btn btn-primary');
?>
<?= $this->formButton($submit) ?>
&nbsp;&nbsp;&nbsp;
<?php
$submit = $form->get('submit_no');
$submit->setLabel('Nee');
$submit->setAttribute('class', 'btn btn-default');
?>
<?= $this->formButton($submit) ?>
</div>

<?= $this->form()->closeTag(); ?>
<?php endif ?>
<?php endif ?>
