<?php

declare(strict_types=1);

use Application\View\HelperTrait;
use Database\Model\Meeting;
use Laminas\View\Renderer\PhpRenderer;

/** @var PhpRenderer|HelperTrait $this */
?>
<?php if (isset($error) && $error): ?>
<h1><?= $this->translate('Decision Cannot Be Removed') ?></h1>
<?= $this->translate('There are other decisions that still refer to this decision.') ?>
<?php else: ?>
<?php if (!isset($form)): ?>
<p><?= $this->translate('Decision removed.') ?></p>
<a href="<?= $this->url('meeting/view', array('type' => $type->value, 'number' => $number)) ?>">
    <?=
        sprintf(
            $this->translate('Back to %s %d'),
            $type->value,
            $number,
        )
    ?>
</a>
<?php else:
$form->prepare();

$form->setAttribute('action', $this->url('meeting/decision/delete', array(
    'type' => $type->value,
    'number' => $number,
    'point' => $point,
    'decision' => $decision
)));
$form->setAttribute('method', 'post');
$form->setAttribute('role', 'form');

echo $this->form()->openTag($form);
?>

<p>
    <?=
        sprintf(
            $this->translate('Are your sure that you want to delete decision %s %d.%d.%d?'),
            $type->value,
            $number,
            $point,
            $decision,
        )
    ?>
</p>
<div class="form-group">
<?php
$submit = $form->get('submit_yes');
$submit->setLabel('Ja');
$submit->setAttribute('class', 'btn btn-primary');
?>
<?= $this->formButton($submit) ?>
&nbsp;&nbsp;&nbsp;
<?php
$submit = $form->get('submit_no');
$submit->setLabel('Nee');
$submit->setAttribute('class', 'btn btn-default');
?>
<?= $this->formButton($submit) ?>
</div>

<?= $this->form()->closeTag(); ?>
<?php endif ?>
<?php endif ?>
