<script>
    function enable_autocomplete() {
        $('#members .member-autocomplete').autocomplete({
            minLength: 2, // at least two chars before request
            delay: 0, // no delay before request
            source: function (rq, response) {
                // make an AJAX request
                $.ajax({
                    dataType: 'json',
                    url: '<?= $this->url('member/default', array('action' => 'search')) ?>?q=' + rq.term,
                    context: document.body
                }).done(function(data) {
                    var ret = [];
                    $.each(data.json, function (idx, member) {
                        // assemble member name and add to list
                        var name = member.fullName + ' (' + member.lidnr + ')';

                        ret.push({
                            label: name,
                            value: name,
                            id: member.lidnr
                        });
                    });

                    // show data
                    response(ret);
                });
            },
            select: function (event, ui) {
                $(event.target).parent().find("input.member-lidnr").val(ui.item.id);
            }
        });
    }
    var count = 2;
    function add_member() {
        var template = $('#members-template').data('template');
        template = template.replace(/__index__/g, count++);

        $('#members').append(template);

        enable_autocomplete();
    }
    function remove_member(ele) {
        $(ele).parent().remove();
    }
    $(document).ready(function(){
        enable_autocomplete();
    });
</script>
<?php
$form = $this->form;
$form->prepare();

$form->setAttribute('action', $this->url('meeting/decision/form', array('form' => 'foundation')));
$form->setAttribute('method', 'post');

$form->setAttribute('role', 'form');

echo $this->form()->openTag($form);
?>
<div class="form-group">
<?php
$element = $form->get('type');
$element->setLabelAttributes(array('class' => 'radio-inline'));
?>
    <?= $this->formRadio($element) ?>
    <?= $this->formElementErrors($element) ?>
</div>
<div class="form-group">
<?php
$element = $form->get('name');
$element->setAttribute('class', 'form-control');
$element->setAttribute('placeholder', 'Naam');
?>
    <?= $this->formLabel($element) ?>
    <?= $this->formInput($element) ?>
    <?= $this->formElementErrors($element) ?>
</div>

<div class="form-group">
<?php
$element = $form->get('abbr');
$element->setAttribute('class', 'form-control');
$element->setAttribute('placeholder', 'Afkorting');
?>
    <?= $this->formLabel($element) ?>
    <?= $this->formInput($element) ?>
    <?= $this->formElementErrors($element) ?>
</div>

<div class="form-group" id="members">
<strong>Leden</strong>
<?php
$element = $form->get('members');

$fs = $element->getTemplateElement();
// render template element
ob_start();
?>
    <div class="form-inline" style="margin-bottom: 5px;">
        <div class="form-group">
            <?php
            $el = $fs->get('name');
            $el->setAttribute('class', 'form-control member-autocomplete');
            $el->setAttribute('placeholder', $el->getLabel());
            ?>
            <?= $this->formInput($el) ?>
            <?php
            // hidden element for actual membership number
            $el = $fs->get('lidnr');
            $el->setAttribute('class', 'member-lidnr');
            ?>
            <?= $this->formHidden($el) ?>
            <?= $this->formElementErrors($el) ?>
        </div>
        <div class="form-group">
            <?php
            $el = $fs->get('function');
            $el->setAttribute('class', 'form-control');
            $el->setAttribute('placeholder', $el->getLabel());
            ?>
            <?= $this->formSelect($el) ?>
            <?= $this->formElementErrors($el) ?>
        </div>
        <button type="button" class="btn btn-danger" onclick="remove_member(this)"><span class="glyphicon glyphicon-remove"></span> Verwijder</button>
    </div>
<?php $tpl = trim(ob_get_clean()); ?>
<span data-template="<?= $this->escapeHtmlAttr($tpl) ?>" id="members-template"></span>
<?php foreach ($element->getIterator() as $fs): ?>
    <div class="form-inline" style="margin-bottom: 5px;">
        <div class="form-group">
            <?php
            $el = $fs->get('name');
            $el->setAttribute('class', 'form-control member-autocomplete');
            $el->setAttribute('placeholder', $el->getLabel());
            ?>
            <?= $this->formInput($el) ?>
            <?php
            // hidden element for actual membership number
            $el = $fs->get('lidnr');
            $el->setAttribute('class', 'member-lidnr');
            ?>
            <?= $this->formHidden($el) ?>
            <?= $this->formElementErrors($el) ?>
        </div>
        <div class="form-group">
            <?php
            $el = $fs->get('function');
            $el->setAttribute('class', 'form-control');
            $el->setAttribute('placeholder', $el->getLabel());
            ?>
            <?= $this->formSelect($el) ?>
            <?= $this->formElementErrors($el) ?>
        </div>
        <button type="button" class="btn btn-danger" onclick="remove_member(this)"><span class="glyphicon glyphicon-remove"></span> Verwijder</button>
    </div>
<?php endforeach; ?>
</div>
<button type="button" class="btn btn-success" onclick="add_member()"><span class="glyphicon glyphicon-plus"></span> Voeg toe</button>
<br><br>

<?php
$submit = $form->get('submit');
$submit->setLabel('Richt op');
$submit->setAttribute('class', 'btn btn-primary');
?>
<?= $this->formButton($submit) ?>

<?= $this->form()->closeTag(); ?>
