<script>
     function add_member() {
         var currentCount = $('#members').children().length;
         var template = $('#members-template').data('template');
         template = template.replace(/__index__/g, currentCount);

         $('#members').append(template);

         return false;
     }
</script>
<?php
$form = $this->form;
$form->prepare();

$form->setAttribute('action', $this->url('meeting/default', array('action' => 'decision')));
$form->setAttribute('method', 'post');

$form->setAttribute('role', 'form');

echo $this->form()->openTag($form);
?>
<div class="form-group">
<?php
$element = $form->get('name');
$element->setAttribute('class', 'form-control');
$element->setAttribute('placeholder', 'Naam');
?>
    <?= $this->formLabel($element) ?>
    <?= $this->formInput($element) ?>
    <?= $this->formElementErrors($element) ?>
</div>

<div class="form-group">
<?php
$element = $form->get('abbr');
$element->setAttribute('class', 'form-control');
$element->setAttribute('placeholder', 'Afkorting');
?>
    <?= $this->formLabel($element) ?>
    <?= $this->formInput($element) ?>
    <?= $this->formElementErrors($element) ?>
</div>

<div class="form-group" id="members">
<strong>Leden</strong>
<?php
$element = $form->get('members');

$fs = $element->getTemplateElement();
// render template element
ob_start();
?>
    <div class="form-inline" style="margin-bottom: 5px;">
    <?php foreach ($fs->getIterator() as $el): ?>
        <div class="form-group">
        <?php
        $el->setAttribute('class', 'form-control');
        $el->setAttribute('placeholder', $el->getLabel());
        ?>
        <?= $this->formInput($el) ?>
        <?= $this->formElementErrors($el) ?>
        </div>
    <?php endforeach; ?>
        <button type="button" class="btn btn-danger"><span class="glyphicon glyphicon-remove"></span> Verwijder</button>
    </div>
<?php $tpl = trim(ob_get_clean()); ?>
<span data-template="<?= $this->escapeHtmlAttr($tpl) ?>" id="members-template"></span>
<?php foreach ($element->getIterator() as $fs): ?>
    <div class="form-inline" style="margin-bottom: 5px;">
    <?php foreach ($fs->getIterator() as $el): ?>
        <div class="form-group">
        <?php
        $el->setAttribute('class', 'form-control');
        $el->setAttribute('placeholder', $el->getLabel());
        ?>
        <?= $this->formInput($el) ?>
        <?= $this->formElementErrors($el) ?>
        </div>
    <?php endforeach; ?>
        <button type="button" class="btn btn-danger"><span class="glyphicon glyphicon-remove"></span> Verwijder</button>
    </div>
<?php endforeach; ?>
</div>
<button type="button" class="btn btn-success" onclick="add_member()"><span class="glyphicon glyphicon-plus"></span> Voeg toe</button>
<br><br>

<?php
$submit = $form->get('submit');
$submit->setLabel('Submit');
$submit->setAttribute('class', 'btn btn-primary');
?>
<?= $this->formButton($submit) ?>

<?= $this->form()->closeTag(); ?>
