<?php
use Database\Model\Meeting;
?>
<table class="table table-hover">
    <thead>
    <tr>
        <th>Type</th>
        <th>Vergadernummer</th>
        <th>Datum</th>
        <th># Besluiten</th>
    </tr>
    </thead>
    <tbody>
<?php foreach ($meetings as $info): ?>
<?php $meeting = $info[0]; ?>
<?php $url = $this->url('meeting/view', array('type' => $meeting->getType(), 'number' => $meeting->getNumber())) ?>
    <tr>
        <td><a href="<?= $url ?>" style="display: block; height: 100%; width:100%;"><?= $meeting->getType() ?></a></td>
        <td><a href="<?= $url ?>" style="display: block; height: 100%; width:100%;"><?= $meeting->getNumber() ?></a></td>
        <td><a href="<?= $url ?>" style="display: block; height: 100%; width:100%;"><?= $this->dateFormat(
            $meeting->getDate(),
            \IntlDateFormatter::FULL,
            \IntlDateFormatter::NONE,
            'nl_NL'
        ) ?></a></td>
        <td><a href="<?= $url ?>" style="display: block; height: 100%; width:100%;"><?= $info[1] ?></a></td>
    </tr>
<?php endforeach; ?>
    </tbody>
</table>
<a href="<?= $this->url('meeting/create') ?>" class="btn btn-success"><span class="glyphicon glyphicon-plus"></span> Maak nieuwe vergadering</a>
