<?php
use Database\Model\Meeting;
function showType($type)
{
    switch ($type) {
    case Meeting::TYPE_BV:
        return 'BV';
    case Meeting::TYPE_AV:
        return 'AV';
    case Meeting::TYPE_VV:
        return 'VV';
    case Meeting::TYPE_VIRT:
        return 'Virt';
    }
}
?>
<table class="table table-hover">
    <thead>
    <tr>
        <th>Type</th>
        <th>Vergadernummer</th>
        <th>Datum</th>
    </tr>
    </thead>
    <tbody>
<?php foreach ($meetings as $meeting): ?>
<?php $url = $this->url('meeting/view', array('type' => $meeting->getType(), 'number' => $meeting->getNumber())) ?>
    <tr>
        <td><a href="<?= $url ?>" style="display: block; height: 100%; width:100%;"><?= showType($meeting->getType()) ?></a></td>
        <td><a href="<?= $url ?>" style="display: block; height: 100%; width:100%;"><?= $meeting->getNumber() ?></a></td>
        <td><a href="<?= $url ?>" style="display: block; height: 100%; width:100%;"><?= $meeting->getDate()->format('l j F Y') ?></a></td>
    </tr>
<?php endforeach; ?>
    </tbody>
</table>
<a href="<?= $this->url('meeting/create') ?>" class="btn btn-success"><span class="glyphicon glyphicon-plus"></span> Maak nieuwe vergadering</a>
