<script>
var urlTemplate = '<?= $this->url('organ/info', array(
    'type' => '__type__',
    'number' => '__number__',
    'point' => '__point__',
    'decision' => '__decision__',
    'subdecision' => '__subdecision__'
)) ?>';
function getUrl(type, meeting, point, decision, subdecision)
{
    url = urlTemplate.replace('__type__', type);
    url = url.replace('__number__', meeting);
    url = url.replace('__point__', point);
    url = url.replace('__decision__', decision);
    return url.replace('__subdecision__', subdecision);
}
$(document).ready(function () {
    $('#install-organ').autocomplete({
            minLength: 2, // at least two chars before request
            delay: 0, // no delay before request
            source: function (rq, response) {
                // make an AJAX request
                $.ajax({
                    dataType: 'json',
                    url: '<?= $this->url('organ/default', array('action' => 'search')) ?>?q=' + rq.term,
                    context: document.body
                }).done(function(data) {
                    var ret = [];
                    $.each(data.json, function (idx, organ) {
                        // assemble organ info and add to list
                        var decision = organ.meeting_type + ' '
                                     + organ.meeting_number + '.'
                                     + organ.decision_point + '.'
                                     + organ.decision_number;

                        var name = organ.abbr + ' (' + organ.name + ', ' + decision + ')';

                        ret.push({
                            label: name,
                            value: name,
                            id: organ
                        });
                    });

                    // show data
                    response(ret);
                });
            },
            select: function (event, ui) {
                $.ajax({
                    dataType: 'json',
                    url: getUrl(ui.item.id.meeting_type, ui.item.id.meeting_number, ui.item.id.decision_point, ui.item.id.decision_number, ui.item.id.subdecision_number),
                    context: document.body
                }).done(function(data) {
                    var content = '';
                    var content2 = '';
                    $.each(data.json.members, function(idx, install) {
                        var toAdd = '<tr data-lidnr="' + install.member.lidnr + '">'
                            + '<td class="name">' + install.member.fullName + '</td>'
                            + '<td class="function">' + install.function + '</td>';
                        content += toAdd + '</tr>';
                        toAdd += '<td><button type="button" class="btn btn-danger btn-xs discharge">'
                            + '<span class="glyphicon glyphicon-remove"></span> Dechargeer</button></td>';
                        toAdd += '<td><button type="button" class="btn btn-warning btn-xs functionchange">'
                            + '<span class="glyphicon glyphicon-plus"></span> Geef functie</button></td>';
                        content2 += toAdd + '</tr>';
                    });
                    $('#members-install').html(content);
                    $('#members-result').html(content2);
                    $('#install-changes').html('');

                    $('#install-members-hide').show();

                    $('button.discharge').click(function(e)
                    {
                        var element = $(e.target).parent().parent();
                        var name = element.find('.name').html();
                        var func = element.find('.function').html();
                        $('#install-modal-discharge div.modal-body span.name').html(name);
                        $('#install-modal-discharge div.modal-body span.function').html(func);
                        $('#install-modal-discharge').attr('data-lidnr', element.attr('data-lidnr'));
                        $('#install-modal-discharge').modal();
                    });

                    $('button.functionchange').click(function(e)
                    {
                        var element = $(e.target).parent().parent();
                        var name = element.find('.name').html();
                        $('#install-modal-function div.modal-body span.name').html(name);
                        $('#install-modal-function').attr('data-lidnr', element.attr('data-lidnr'));
                        $('#install-modal-function').modal();
                    });
                });
            }
        });
});
</script>
<?php
$form = $this->form;
$form->prepare();

$form->setAttribute('action', $this->url('meeting/decision/form', array('form' => 'install')));
$form->setAttribute('method', 'post');

$form->setAttribute('role', 'form');

echo $this->form()->openTag($form);
?>
<?php /* first do hidden elements */ ?>
<?php
$fs = $form->get('meeting')
?>
<?= $this->formHidden($fs->get('type')) ?>
<?= $this->formHidden($fs->get('number')) ?>
<?= $this->formHidden($form->get('point')) ?>
<?= $this->formHidden($form->get('decision')) ?>
<div class="form-group">
<?php
$element = $form->get('name');
$element->setAttribute('class', 'form-control');
$element->setAttribute('placeholder', 'Orgaan');
$element->setAttribute('id', 'install-organ');
?>
    <?= $this->formLabel($element) ?>
    <?= $this->formInput($element) ?>
    <?= $this->formElementErrors($element) ?>
</div>

<div id="install-members-hide" style="display: none;">
<div class="row">
    <div class="col-md-6">
        <h2>Huidige Leden</h2>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Naam</th>
                    <th>Functie</th>
                </tr>
            </thead>
            <tbody id="members-install">
            </tbody>
        </table>
    </div>
    <div class="col-md-6">
        <h2>Resultaat</h2>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Naam</th>
                    <th>Functie</th>
                    <th>Dechargeer</th>
                    <th>Geef functie</th>
                </tr>
            </thead>
            <tbody id="members-result">
            </tbody>
        </table>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <h2>Wijzigingen</h2>
        <div id="install-changes">
        </div>
    </div>
    <div class="col-md-6 form-inline">
        <h2>Nieuw lid toevoegen</h2>
        <div class="form-group">
            <input type="text" id="install-member" class="form-control" placeholder="Lid" />
            <input type="hidden" id="install-member-lidnr" />
        </div>
        <button type="button" class="btn btn-success">
            <span class="glyphicon glyphicon-plus"></span>
            Voeg lid toe
        </button>
    </div>
</div>
<br />
<br />
</div>

<?php
$submit = $form->get('submit');
$submit->setLabel('Maak wijzigingen');
$submit->setAttribute('class', 'btn btn-primary');
?>
<?= $this->formButton($submit) ?>

<?= $this->form()->closeTag(); ?>
<?php /* Modals that might be used */ ?>
<div id="install-modal-discharge" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="install-model-discharge-label" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="install-model-discharge-label">Dechargeer lid</h4>
      </div>
      <div class="modal-body">
        Dechargeer <span class="name"></span> als <span class="function"></span>?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Nee</button>
        <button type="button" class="btn btn-primary">Ja</button>
      </div>
    </div>
  </div>
</div>

<div id="install-modal-function" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="install-model-function-label" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="install-model-function-label">Geef functie aan lid</h4>
      </div>
      <div class="modal-body">
        <div class="form-group">
            <label for="function">Functie van <span class="name"></span></label>
            <select name="function" class="form-control">
                <option value="voorzitter">chairman</option>
                <option value="secretaris">secretary</option>
                <option value="treasurer">treasurer</option>
                <option value="vice-chairman">vice-chairman</option>
                <option value="pr-officer">pr-officer</option>
                <option value="education-officer">education-officer</option>
            </select>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Nee</button>
        <button type="button" class="btn btn-primary">Ja</button>
      </div>
    </div>
  </div>
</div>
