<script>
var urlTemplate = '<?= $this->url('organ/info', array(
    'type' => '__type__',
    'number' => '__number__',
    'point' => '__point__',
    'decision' => '__decision__',
    'subdecision' => '__subdecision__'
)) ?>';
function getUrl(type, meeting, point, decision, subdecision)
{
    url = urlTemplate.replace('__type__', type);
    url = url.replace('__number__', meeting);
    url = url.replace('__point__', point);
    url = url.replace('__decision__', decision);
    return url.replace('__subdecision__', subdecision);
}
$(document).ready(function () {
    $('#install-organ').autocomplete({
        minLength: 2, // at least two chars before request
        delay: 0, // no delay before request
        source: function (rq, response) {
            // make an AJAX request
            $.ajax({
                dataType: 'json',
                url: '<?= $this->url('organ/default', array('action' => 'search')) ?>?q=' + rq.term,
                context: document.body
            }).done(function(data) {
                var ret = [];
                $.each(data.json, function (idx, organ) {
                    // assemble organ info and add to list
                    var decision = organ.meeting_type + ' '
                                 + organ.meeting_number + '.'
                                 + organ.decision_point + '.'
                                 + organ.decision_number;

                    var name = organ.abbr + ' (' + organ.name + ', ' + decision + ')';

                    ret.push({
                        label: name,
                        value: name,
                        id: organ
                    });
                });

                // show data
                response(ret);
            });
        },
        select: function (event, ui) {
            $.ajax({
                dataType: 'json',
                url: getUrl(ui.item.id.meeting_type, ui.item.id.meeting_number, ui.item.id.decision_point, ui.item.id.decision_number, ui.item.id.subdecision_number),
                context: document.body
            }).done(function(data) {
                var content = '';
                var content2 = '';
                // set the data for all current members
                $.each(data.json.members, function(idx, install) {
                    var decNum = install.meeting_type + '-' + install.meeting_number
                        + '-' + install.decision_point + '-' + install.decision_number
                        + '-' + install.subdecision_number;
                    var toAdd = '<tr data-lidnr="' + install.member.lidnr + '"'
                        + ' data-meeting-type="' + install.meeting_type + '"'
                        + ' data-meeting-number="' + install.meeting_number + '"'
                        + ' data-decision-point="' + install.decision_point + '"'
                        + ' data-decision-number="' + install.decision_number + '"'
                        + ' data-subdecision-number="' + install.subdecision_number + '"'
                        + ' class="dec-' + decNum + '"'
                        + '>'
                        + '<td class="name">' + install.member.fullName + '</td>'
                        + '<td class="function">' + install.function + '</td>';
                    content += toAdd + '</tr>';
                    toAdd += '<td><button type="button" class="btn btn-danger btn-xs discharge">'
                        + '<span class="glyphicon glyphicon-remove"></span> Dechargeer</button></td>';
                    toAdd += '<td><button type="button" class="btn btn-warning btn-xs functionchange">'
                        + '<span class="glyphicon glyphicon-plus"></span> Geef functie</button></td>';
                    content2 += toAdd + '</tr>';
                });
                $('#members-install').html(content);
                $('#members-result').html(content2);
                $('#install-changes').html('');

                // set foundation of organ
                $('#install-foundation-meeting-type').val(data.json.meeting_type);
                $('#install-foundation-meeting-name').val(data.json.meeting_number);
                $('#install-foundation-decision-point').val(data.json.decision_point);
                $('#install-foundation-decision-number').val(data.json.decision_number);
                $('#install-foundation-subdecision-number').val(data.json.subdecision_number);

                // show the rest of the form
                $('#install-members-hide').show();

                // enable member change events
                $('button.discharge').click(function(e)
                {
                    var element = $(e.target).parent().parent();
                    var name = element.find('.name').html();
                    var func = element.find('.function').html();
                    $('#install-modal-discharge div.modal-body span.name').html(name);
                    $('#install-modal-discharge div.modal-body span.function').html(func);
                    var modal = $('#install-modal-discharge');
                    modal.data('meeting-type', element.data('meeting-type'));
                    modal.data('meeting-number', element.data('meeting-number'));
                    modal.data('decision-point', element.data('decision-point'));
                    modal.data('decision-number', element.data('decision-number'));
                    modal.data('subdecision-number', element.data('subdecision-number'));
                    modal.modal();
                });

                $('button.functionchange').click(function(e)
                {
                    var element = $(e.target).parent().parent();
                    var name = element.find('.name').html();
                    $('#install-modal-function div.modal-body span.name').html(name);
                    $('#install-modal-function').data('lidnr', element.data('lidnr'));
                    $('#install-modal-function').modal();
                });
            });
        }
    });
    $('#install-member').autocomplete({
        minLength: 2, // at least two chars before request
        delay: 0, // no delay before request
        source: function (rq, response) {
            // make an AJAX request
            $.ajax({
                dataType: 'json',
                url: '<?= $this->url('member/default', array('action' => 'search')) ?>?q=' + rq.term,
                context: document.body
            }).done(function(data) {
                var ret = [];
                $.each(data.json, function (idx, member) {
                    // assemble member name and add to list
                    var name = member.fullName + ' (' + member.lidnr + ')';

                    ret.push({
                        label: name,
                        value: name,
                        name: member.fullName,
                        id: member.lidnr
                    });
                });

                // show data
                response(ret);
            });
        },
        select: function (event, ui) {
            $('#install-member-lidnr').val(ui.item.id);
            $('#install-member-name').val(ui.item.name);
            $('#install-member-btn').prop('disabled', false);
        }
    });

    // count for subdecision numbers
    var count = 0;
    /**
     * Create an installation.
     */
    function createInstallation(func, lidnr, name) {
        // initialize the form data
        var template = $('#install-template').data('template');
        template = template.replace(/__index__/g, count++);
        template = template.replace(/__function__/g, func);
        template = template.replace(/__lidnr__/g, lidnr);
        template = template.replace(/__name__/g, name);
        $('#install-changes').append($(template));

        // add to 'result'
        var toAdd = '<tr data-lidnr="' + lidnr + '">'
            + '<td class="name">' + name + '</td>'
            + '<td class="function">' + func + '</td>';
        toAdd += '<td></td>';
        toAdd += '<td><button type="button" class="btn btn-warning btn-xs functionchange">'
            + '<span class="glyphicon glyphicon-plus"></span> Geef functie</button></td>';
        toAdd += '</tr>';

        toAdd = $(toAdd);
        $('#members-result').append(toAdd);

        // also add ability to give a function, using the function modal
        toAdd.find('button.functionchange').click(function(e)
        {
            var element = $(e.target).parent().parent();
            var name = element.find('.name').html();
            $('#install-modal-function div.modal-body span.name').html(name);
            $('#install-modal-function').data('lidnr', element.data('lidnr'));
            $('#install-modal-function').modal();
        });
    }
    $('#install-member-btn').click(function(e)
    {
        var lidnr = $('#install-member-lidnr').val();
        var name = $('#install-member-name').val();
        createInstallation('Lid', lidnr, name);
        $('#install-member').val('');
        $('#install-member-btn').prop('disabled', true);
    });
    $('#install-modal-yes').click(function(e)
    {
        var lidnr = $('#install-modal-function').data('lidnr');
        var name = $('#install-modal-function div.form-group span.name').text();
        var func = $('#install-modal-function div.form-group select').val();
        createInstallation(func, lidnr, name);
        $('#install-modal-function').modal('hide');
    });

    // discharge modal stuff
    $('#discharge-modal-yes').click(function(e)
    {
        var modal = $('#install-modal-discharge');
        var meeting_type = modal.data('meeting-type');
        var meeting_number = modal.data('meeting-number');
        var decision_point = modal.data('decision-point');
        var decision_number = modal.data('decision-number');
        var subdecision_number = modal.data('subdecision-number');
        var name = $('#install-modal-discharge div.modal-body span.name').text();
        var func = $('#install-modal-discharge div.modal-body span.function').text();

        // create the discharge, and add to all changes
        var template = $('#discharge-template').data('template');
        template = template.replace(/__index__/g, count++);
        template = template.replace(/__function__/g, func);
        template = template.replace(/__name__/g, name);

        template = template.replace(/__meeting_type__/g, meeting_type);
        template = template.replace(/__meeting_number__/g, meeting_number);
        template = template.replace(/__decision_point__/g, decision_point);
        template = template.replace(/__decision_number__/g, decision_number);
        template = template.replace(/__number__/g, subdecision_number);
        $('#install-changes').append($(template));

        var select = '.dec-' + meeting_type + '-' + meeting_number
            + '-' + decision_point + '-' + decision_number
            + '-' + subdecision_number;
        $('#members-result').find(select).remove();

        // dismiss the dialog
        modal.modal('hide');
    });
});
</script>
<?php
$form = $this->form;
$form->prepare();

$form->setAttribute('action', $this->url('meeting/decision/form', array('form' => 'install')));
$form->setAttribute('method', 'post');

$form->setAttribute('role', 'form');

echo $this->form()->openTag($form);
?>
<?php
// default hidden elements for the meeting and decision reference
$fs = $form->get('meeting')
?>
<?= $this->formHidden($fs->get('type')) ?>
<?= $this->formHidden($fs->get('number')) ?>
<?= $this->formHidden($form->get('point')) ?>
<?= $this->formHidden($form->get('decision')) ?>
<div class="form-group">
<?php
// organ search box
$element = $form->get('name');
$element->setAttribute('class', 'form-control');
$element->setAttribute('placeholder', 'Orgaan');
$element->setAttribute('id', 'install-organ');
?>
    <?= $this->formLabel($element) ?>
    <?= $this->formInput($element) ?>
    <?= $this->formElementErrors($element) ?>
</div>
<?php
// hidden elements for form foundation
$fs = $form->get('subdecision');
$fs->get('meeting_type')->setAttribute('id', 'install-foundation-meeting-type');
$fs->get('meeting_number')->setAttribute('id', 'install-foundation-meeting-name');
$fs->get('decision_point')->setAttribute('id', 'install-foundation-decision-point');
$fs->get('decision_number')->setAttribute('id', 'install-foundation-decision-number');
$fs->get('number')->setAttribute('id', 'install-foundation-subdecision-number');
?>
<?= $this->formHidden($fs->get('meeting_type')) ?>
<?= $this->formHidden($fs->get('meeting_number')) ?>
<?= $this->formHidden($fs->get('decision_point')) ?>
<?= $this->formHidden($fs->get('decision_number')) ?>
<?= $this->formHidden($fs->get('number')) ?>

<div id="install-members-hide" style="display: none;">
<div class="row">
    <div class="col-md-6">
        <h2>Huidige Leden</h2>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Naam</th>
                    <th>Functie</th>
                </tr>
            </thead>
            <tbody id="members-install">
            </tbody>
        </table>
    </div>
    <div class="col-md-6">
        <h2>Resultaat</h2>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Naam</th>
                    <th>Functie</th>
                    <th>Dechargeer</th>
                    <th>Geef functie</th>
                </tr>
            </thead>
            <tbody id="members-result">
            </tbody>
        </table>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <h2>Wijzigingen</h2>
<?php
// installation element template
$element = $form->get('installations');
$fs = $element->getTemplateElement();
$mfs = $fs->get('member');
// render template element
ob_start();
?>
<div class="organ-installation">
    __name__ wordt ge&iuml;nstalleerd als __function__.
    <?php
    $el = $fs->get('function');
    $el->setAttribute('class', 'install-function');
    $el->setValue('__function__');
    ?>
    <?= $this->formHidden($el) ?>
    <?php
    $el = $mfs->get('lidnr');
    $el->setAttribute('class', 'member-lidnr');
    $el->setValue('__lidnr__');
    ?>
    <?= $this->formHidden($el) ?>
</div>
<?php
$tpl = trim(ob_get_clean());
?>
<span data-template="<?= $this->escapeHtmlAttr($tpl) ?>" id="install-template"></span>
<?php
// discharge element template
$element = $form->get('discharges');
$fs = $element->getTemplateElement();
// render template element
ob_start();
?>
<div class="organ-discharge">
    __name__ wordt gedechargeerd als __function__.
    <?php
    $el = $fs->get('meeting_type');
    $el->setValue('__meeting_type__');
    ?>
    <?= $this->formHidden($el) ?>
    <?php
    $el = $fs->get('meeting_number');
    $el->setValue('__meeting_number__');
    ?>
    <?= $this->formHidden($el) ?>
    <?php
    $el = $fs->get('decision_point');
    $el->setValue('__decision_point__');
    ?>
    <?= $this->formHidden($el) ?>
    <?php
    $el = $fs->get('decision_number');
    $el->setValue('__decision_number__');
    ?>
    <?= $this->formHidden($el) ?>
    <?php
    $el = $fs->get('number');
    $el->setValue('__number__');
    ?>
    <?= $this->formHidden($el) ?>
</div>
<?php
$tpl = trim(ob_get_clean());
?>
<span data-template="<?= $this->escapeHtmlAttr($tpl) ?>" id="discharge-template"></span>
        <div id="install-changes">
        </div>
    </div>
    <div class="col-md-6 form-inline">
        <h2>Nieuw lid toevoegen</h2>
        <div class="form-group">
            <input type="text" id="install-member" class="form-control" placeholder="Lid" />
            <input type="hidden" id="install-member-lidnr" />
            <input type="hidden" id="install-member-name" />
        </div>
        <button type="button" class="btn btn-success" id="install-member-btn" disabled>
            <span class="glyphicon glyphicon-plus"></span>
            Voeg lid toe
        </button>
    </div>
</div>
<br />
<br />

<?php
$submit = $form->get('submit');
$submit->setLabel('Bevestig wijzigingen');
$submit->setAttribute('class', 'btn btn-primary');
?>
<?= $this->formButton($submit) ?>

</div>


<?= $this->form()->closeTag(); ?>
<?php /* Modals that might be used */ ?>
<div id="install-modal-discharge" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="install-model-discharge-label" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="install-model-discharge-label">Dechargeer lid</h4>
      </div>
      <div class="modal-body">
        Dechargeer <span class="name"></span> als <span class="function"></span>?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Nee</button>
        <button type="button" class="btn btn-primary" id="discharge-modal-yes">Ja</button>
      </div>
    </div>
  </div>
</div>

<div id="install-modal-function" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="install-model-function-label" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="install-model-function-label">Geef functie aan lid</h4>
      </div>
      <div class="modal-body">
        <div class="form-group">
            <label for="function">Functie van <span class="name"></span></label>
            <?php
            $element = $memberfunction->get('function');
            $element->setAttribute('class', 'form-control');
            $element->setAttribute('placeholder', 'Functienaam');
            ?>
            <?= $this->formSelect($element) ?>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Nee</button>
        <button type="button" class="btn btn-primary" id="install-modal-yes">Ja</button>
      </div>
    </div>
  </div>
</div>
