<script>
    function enable_autocomplete_install() {
        $('#members-install .member-autocomplete').autocomplete({
            minLength: 2, // at least two chars before request
            delay: 0, // no delay before request
            source: function (rq, response) {
                // make an AJAX request
                $.ajax({
                    dataType: 'json',
                    url: '<?= $this->url('member/default', array('action' => 'search')) ?>?q=' + rq.term,
                    context: document.body
                }).done(function(data) {
                    var ret = [];
                    $.each(data.json, function (idx, member) {
                        // assemble member name and add to list
                        var name = member.fullName + ' (' + member.lidnr + ')';

                        ret.push({
                            label: name,
                            value: name,
                            id: member.lidnr
                        });
                    });

                    // show data
                    response(ret);
                });
            },
            select: function (event, ui) {
                $(event.target).parent().find("input.member-lidnr").val(ui.item.id);
            }
        });
    }
    var count = 1;
    function add_member_install() {
        var template = $('#members-template-install').data('template');
        template = template.replace(/__index__/g, count++);

        $('#members-install').append(template);

        enable_autocomplete_install();
    }
    function remove_member_install(ele) {
        $(ele).parent().remove();
    }
    $(document).ready(function(){
        enable_autocomplete_install();
    });
</script>
<?php
$form = $this->form;
$form->prepare();

$form->setAttribute('action', $this->url('meeting/decision/form', array('form' => 'install')));
$form->setAttribute('method', 'post');

$form->setAttribute('role', 'form');

echo $this->form()->openTag($form);
?>
<?php /* first do hidden elements */ ?>
<?php
$fs = $form->get('meeting')
?>
<?= $this->formHidden($fs->get('type')) ?>
<?= $this->formHidden($fs->get('number')) ?>
<?= $this->formHidden($form->get('point')) ?>
<?= $this->formHidden($form->get('decision')) ?>
<div class="form-group">
<?php
$element = $form->get('name');
$element->setAttribute('class', 'form-control');
$element->setAttribute('placeholder', 'Orgaan');
?>
    <?= $this->formLabel($element) ?>
    <?= $this->formInput($element) ?>
    <?= $this->formElementErrors($element) ?>
</div>

<?php
$submit = $form->get('submit');
$submit->setLabel('Installeer leden');
$submit->setAttribute('class', 'btn btn-primary');
?>
<?= $this->formButton($submit) ?>

<?= $this->form()->closeTag(); ?>
