<?php
$form->prepare();

$form->setAttribute('action', $this->url('meeting/decision/form', array('form' => 'other')));
$form->setAttribute('method', 'post');

$form->setAttribute('role', 'form');

echo $this->form()->openTag($form);
?>
<?php /* first do hidden elements */ ?>
<?php
$fs = $form->get('meeting')
?>
<?= $this->formHidden($fs->get('type')) ?>
<?= $this->formHidden($fs->get('number')) ?>
<?= $this->formHidden($form->get('point')) ?>
<?= $this->formHidden($form->get('decision')) ?>
<div class="form-group">
<?php
$element = $form->get('content');
$element->setAttribute('class', 'form-control');
$element->setAttribute('placeholder', 'Besluit');
?>
    <?= $this->formLabel($element) ?>
    <?= $this->formInput($element) ?>
    <?= $this->formElementErrors($element) ?>
</div>
<br><br>

<?php
$submit = $form->get('submit');
$submit->setLabel('Maak besluit');
$submit->setAttribute('class', 'btn btn-primary');
?>
<?= $this->formButton($submit) ?>

<?= $this->form()->closeTag(); ?>
