<script>
$(document).ready(function () {
    $('#createdecision').click(function () {
        var url = "<?= $this->url('meeting/decision/create', array(
            'type' => $meeting->getType(),
            'number' => $meeting->getNumber(),
            'point' => '__point__',
            'decision' => '__decision__'
        )) ?>";
        url = url.replace('__point__', $('#create_point').val());
        url = url.replace('__decision__', $('#create_decision').val());
        location.href = url;
    });
});
</script>
<?php
use Database\Model\Meeting;
function showType($type)
{
    switch ($type) {
    case Meeting::TYPE_BV:
        return 'BV';
    case Meeting::TYPE_AV:
        return 'AV';
    case Meeting::TYPE_VV:
        return 'VV';
    case Meeting::TYPE_VIRT:
        return 'Virt';
    }
}
?>
    <h1><?= showType($meeting->getType()) ?> <?= $meeting->getNumber() ?>
    <small><?= $meeting->getDate()->format('l j F Y') ?></small></h1>

<h2>Besluiten</h2>

<ul>
<?php foreach ($meeting->getDecisions() as $decision): ?>
    <li>
        Besluit <?= "{$meeting->getNumber()}.{$decision->getPoint()}.{$decision->getNumber()}" ?>:
        <ul>
        <?php foreach ($decision->getSubdecisions() as $subdecision): ?>
            <li><?= $subdecision->getContent() ?></li>
        <?php endforeach; ?>
        </ul>
    </li>
<?php endforeach; ?>
</ul>

<h2>Besluit toevoegen</h2>

<form role="form" class="form-inline">
<div class="form-group">
    <label class="sr-only" for="point">Punt</label>
    <input type="text" class="form-control" name="point" id="create_point" placeholder="Punt">
</div>
<div class="form-group">
    <label class="sr-only" for="decision">Punt</label>
    <input type="text" class="form-control" name="decision" id="create_decision" placeholder="Besluitnummer">
</div>
<button type="button" class="btn btn-success" id="createdecision">
    <span class="glyphicon glyphicon-plus"></span>
    Voeg toe
</button>
</form>
