<?php

declare(strict_types=1);

use Application\View\HelperTrait;
use Laminas\View\Renderer\PhpRenderer;

/** @var PhpRenderer|HelperTrait $this */

// determine last decision of each point
$map = array();
foreach ($meeting->getDecisions() as $decision) {
    $point = $decision->getPoint();
    if (!isset($map[$point]) || $map[$point] < $decision->getNumber()) {
        $map[$point] = $decision->getNumber();
    }
}
$mapjs = array();
foreach ($map as $point => $num) {
    $mapjs[] = '"' . $point . '": ' . $num;
}
?>
<script>
$(document).ready(function () {
    $('#createdecision').click(function () {
        var url = "<?= $this->url('meeting/decision/create', array(
            'type' => $meeting->getType()->value,
            'number' => $meeting->getNumber(),
            'point' => '__point__',
            'decision' => '__decision__'
        )) ?>";
        if ($('#create_point').val() == '' || $('#create_decision').val() == '') {
            alert('Please fill in a valid point and decision number');
            return;
        }
        url = url.replace('__point__', $('#create_point').val());
        url = url.replace('__decision__', $('#create_decision').val());
        location.href = url;
    });
    var map = {<?= implode(", ", $mapjs) ?>};
    $('#create_point').keyup(function (e) {
        var val = $(e.target).val();
        if (val in map) {
            $('#create_decision').val(map[val] + 1);
        } else {
            $('#create_decision').val('');
        }
    });
});
</script>
<?php
use Database\Model\Meeting;
?>
    <h1><?= $meeting->getType()->value ?> <?= $meeting->getNumber() ?>
    <small><?= $this->dateFormat(
        $meeting->getDate(),
        \IntlDateFormatter::FULL,
        \IntlDateFormatter::NONE,
    ) ?></small></h1>

<h2><?= $this->translate('Decisions') ?></h2>

<?php if (count($meeting->getDecisions()) > 0): ?>
<ul>
<?php foreach ($meeting->getDecisions() as $decision): ?>
    <li>
        <?= $this->translate('Decision') ?> <?= "{$meeting->getNumber()}.{$decision->getPoint()}.{$decision->getNumber()}" ?>:
        <?php if ($decision->isDestroyed()): ?>
        <?php
        $dec = $decision->getDestroyedBy()->getDecision();
        $mt = $dec->getMeeting();
        ?>
        <strong>
            <?=
                sprintf(
                    $this->translate('(Annulled by decision %s %d.%d.%d)'),
                    $mt->getType()->value,
                    $mt->getNumber(),
                    $dec->getPoint(),
                    $dec->getNumber(),
                )
            ?>
        </strong>
        <?php endif; ?>
        <br />
        <a href="<?= $this->url('meeting/decision/delete', array(
            'type' => $meeting->getType()->value,
            'number' => $meeting->getNumber(),
            'point' => $decision->getPoint(),
            'decision' => $decision->getNumber()
        )) ?>" class="btn btn-danger">
            <span class="glyphicon glyphicon-remove"></span> <?= $this->translate('Delete Decision') ?>
        </a>
        <button onclick="copyDecision(this)" class="btn btn-success" value="<?= $this->escapeHtmlAttr($decision->getContent()) ?>">
            <span class="glyphicon glyphicon-floppy-disk"></span> <?= $this->translate('Copy Decision')?>
        </button>
        <ul>
        <?php foreach ($decision->getSubdecisions() as $subdecision): ?>
            <li><?= $this->escapeHtmlAttr($subdecision->getContent()) ?></li>
        <?php endforeach; ?>
        </ul>
    </li>
<?php endforeach; ?>
<script>
    function copyDecision(decision) {
        navigator.clipboard.writeText(decision.value).then(
            () => {
                // Clipboard succeeded
            },
            () => {
                // Clipboard failed
                console.log("Copying the decision has failed, please try again.");
            }
        );
    }
</script>

</ul>
<?php else: ?>
    <?= $this->translate('This meeting has no decisions (yet).') ?>
<?php endif; ?>

<h2><?= $this->translate('Add New Decision') ?></h2>

<form role="form" class="form-inline">
<div class="form-group">
    <label class="sr-only" for="point"><?= $this->translate('Point') ?></label>
    <input type="text" class="form-control" name="point" id="create_point" placeholder="<?= $this->translate('Point') ?>">
</div>
<div class="form-group">
    <label class="sr-only" for="decision"><?= $this->translate('Decision Number') ?></label>
    <input type="text" class="form-control" name="decision" id="create_decision" placeholder="<?= $this->translate('Decision Number') ?>">
</div>
<button type="button" class="btn btn-success" id="createdecision">
    <span class="glyphicon glyphicon-plus"></span>
    <?= $this->translate('Add Decision') ?>
</button>
</form>
