<?php
function showDecisionNumber($decision)
{
    $ret = strtoupper($decision->getMeeting()->getType());
    $ret .= ' ' . $decision->getMeeting()->getNumber();
    $ret .= '.' . $decision->getPoint();
    $ret .= '.' . $decision->getNumber();
    return $ret;
}
function determineCategory($decision)
{
    $subdecisions = $decision->getSubdecisions();
    $class = get_class($subdecisions[0]);
    $class = explode('\\', $class);
    $type = $class[count($class) - 1];

    switch (strtolower($type)) {
    case 'budget':
    case 'reckoning':
        return 'budget';
        break;
    case 'foundation':
    case 'abrogation':
    case 'installation':
    case 'discharge':
        return 'install';
        break;
    default:
        return 'other';
    }
}
// to show a single category
function showCategory($decisions)
{ ?>
<?php foreach ($decisions as $decision): ?>

<strong>Besluit <?= showDecisionNumber($decision) ?>:</strong>
<?php foreach ($decision->getSubdecisions() as $subdecision): ?>
<?= $subdecision->getContent() . ' ' ?>
<?php endforeach; ?>

<?php endforeach; ?>
<?php } // function showCategory
?>
<?php if (isset($data)): ?>
<?php
$categories = array(
    'budget' => array(),
    'install' => array(),
    'other' => array()
);
// first we do some preprocessing, by putting everything in categories
foreach ($data as $decision) {
    $categories[determineCategory($decision)][] = $decision;
}
?>
<pre style="height: 32em; overflow: scroll"><code>
<h2>Begrotingen en Afrekeningen</h2>
<?php showCategory($categories['budget']) ?>

<h2>Installaties en Decharges</h2>
<?php showCategory($categories['install']) ?>

<h2>Overige besluiten</h2>
<?php showCategory($categories['other']) ?>
</code></pre>
<?php else: ?>
<?php
$form->prepare();

$form->setAttribute('action', $this->url('export'));
$form->setAttribute('method', 'post');

$form->setAttribute('role', 'form');

echo $this->form()->openTag($form);
?>
<h1>Exporteren besluiten</h2>
<div class="container">
    <div class="col-md-3">
        <div class="form-group">
        <?php
        $element = $form->get('meetings');
        $element->setAttribute('class', 'form-control');
        $element->setAttribute('size', 32);
        ?>
            <?= $this->formLabel($element) ?>
            <?= $this->formSelect($element) ?>
            <?= $this->formElementErrors($element) ?>
        </div>
    </div>
    <div class="col-md-9">
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <?php
        $submit = $form->get('submit');
        $submit->setLabel('Exporteer');
        $submit->setAttribute('class', 'btn btn-primary');
        ?>
        <?= $this->formButton($submit) ?>
    </div>
</div>
<?= $this->form()->closeTag() ?>
<?php endif; ?>
