<?php

declare(strict_types=1);

use Application\View\HelperTrait;
use Database\Form\QueryExport as QueryExportForm;
use Laminas\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer|HelperTrait $this
 * @var QueryExportForm $form
 */

$escaper = new Laminas\Escaper\Escaper('UTF-8');

function showDecisionNumber($decision)
{
    $ret = strtoupper($decision->getMeeting()->getType()->value);
    $ret .= ' ' . $decision->getMeeting()->getNumber();
    $ret .= '.' . $decision->getPoint();
    $ret .= '.' . $decision->getNumber();
    return $ret;
}

function determineCategory($decision)
{
    $subdecisions = $decision->getSubdecisions();
    $class = get_class($subdecisions[0]);
    $class = explode('\\', $class);
    $type = $class[count($class) - 1];

    switch (strtolower($type)) {
        case 'budget':
        case 'reckoning':
            return 'budget';
            break;
        case 'foundation':
        case 'abrogation':
        case 'installation':
        case 'discharge':
            return 'install';
            break;
        default:
            return 'other';
    }
}

// to show a single category
function showCategory($escaper, $decisions)
{
    foreach ($decisions as $decision) {
        echo sprintf(
            '<strong>\besluit{%s}{%s}</strong>{%s}<br><br>',
            showDecisionNumber($decision),
            $decision->getMeeting()->getDate()->format('d-m-Y'),
            $escaper->escapeHtml(
                implode(
                    ' ',
                    array_map(
                        function ($subdecision) {
                            return $subdecision->getContent();
                        },
                        $decision->getSubdecisions()->toArray(),
                    ),
                ),
            ),
        );
    }
}
?>
<?php
if (isset($data)): ?>
    <?php
    $categories = array(
        'budget' => array(),
        'install' => array(),
        'other' => array(),
    );
    // first we do some preprocessing, by putting everything in categories
    foreach ($data as $decision) {
        if (count($decision->getSubdecisions()) > 0) {
            $categories[determineCategory($decision)][] = $decision;
        }
    }
    ob_start();
    ?>
    <h2>\subsection*{Begrotingen en Afrekeningen}</h2>
    <?php showCategory($escaper, $categories['budget']) ?>

    <h2>\subsection*{Installaties en Decharges}</h2>
    <?php showCategory($escaper, $categories['install']) ?>

    <h2>\subsection*{Overige besluiten}</h2>
    <?php showCategory($escaper, $categories['other']) ?>
    <?php $decisionList = ob_get_clean(); ?>
    <pre style="height: 80vh; overflow: scroll">
        <code>
            <?php
            echo $this->partial('database/export/latex.phtml', array(
                'decisions' => $decisionList,
            ));
            ?>
        </code>
    </pre>
<?php
else: ?>
    <?php
    $form->prepare();

    $form->setAttribute('action', $this->url('export'));
    $form->setAttribute('method', 'post');

    $form->setAttribute('role', 'form');

    echo $this->form()->openTag($form);
    ?>
    <h1><?= $this->translate('Export Decisions') ?></h1>
    <div class="container">
        <div class="col-md-3">
            <div class="form-group">
                <?php
                $element = $form->get('meetings');
                $element->setAttribute('class', 'form-control');
                $element->setAttribute('size', 32);
                ?>
                <?= $this->formLabel($element) ?>
                <?= $this->formSelect($element) ?>
                <?= $this->formElementErrors($element) ?>
            </div>
        </div>
        <div class="col-md-9">
            <br/>
            <br/>
            <br/>
            <br/>
            <br/>
            <br/>
            <br/>
            <br/>
            <br/>
            <br/>
            <br/>
            <br/>
            <br/>
            <br/>
            <br/>
            <br/>
            <br/>
            <br/>
            <br/>
            <br/>
            <br/>
            <br/>
            <br/>
            <br/>
            <br/>
            <br/>
            <br/>
            <?php
            $submit = $form->get('submit');
            $submit->setLabel($this->translate('Export'));
            $submit->setAttribute('class', 'btn btn-primary');
            ?>
            <?= $this->formButton($submit) ?>
        </div>
    </div>
    <?= $this->form()->closeTag() ?>
<?php
endif; ?>
