name: Symfony Migration

on:
    push:
        branches:
            - chore/migrate-to-symfony
    pull_request:

concurrency:
    group: '${{ github.workflow }}-${{ github.ref }}'
    cancel-in-progress: true

jobs:
    phpstan-src:
        name: PHPStan (src)
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Install PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.4'
                    extensions: calendar, curl, intl, opcache, pgsql, pdo_pgsql, zip
                    tools: cs2pr

            -   name: Install dependencies with Composer
                uses: ramsey/composer-install@v3

            -   name: Run PHPStan
                run: vendor/bin/phpstan analyse --memory-limit 1G --no-progress --error-format=checkstyle | cs2pr

    phpcs-src:
        name: PHP CodeSniffer (src)
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Install PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.4'
                    extensions: calendar, curl, intl, opcache, pgsql, pdo_pgsql, zip
                    tools: cs2pr

            -   name: Install dependencies with Composer
                uses: ramsey/composer-install@v3

            -   name: Run PHP CodeSniffer
                run: vendor/bin/phpcs src --report=checkstyle | cs2pr
