<?php

declare(strict_types=1);

use Database\Model\Member as MemberModel;

/** @var MemberModel $member */

?>

<!DOCTYPE html>
<html lang="en" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:v="urn:schemas-microsoft-com:vml">
<head>
    <title>Happy Birthday!!!</title>
    <meta charset="utf-8"/>
    <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
    <!--[if mso]>
    <xml>
        <o:OfficeDocumentSettings>
            <o:PixelsPerInch>96</o:PixelsPerInch>
            <o:AllowPNG/>
        </o:OfficeDocumentSettings>
    </xml>
    <![endif]-->
    <!--[if !mso]><!-->
    <!--<![endif]-->
    <style>
        :root {
            --gewisred: #D40000;
            --black: #000000;
            --white: #FFFFFF;
            --gewisdarkred: #C40000;
            --gewisdarkgray: #333333;
            --gewislightgray: #F2F2F2;
            --slightlydarkergray: #DDDDDD;
            --gewisdarkblue: #293065;
        }
        * {
            box-sizing: border-box;
        }
        body {
            margin: 0;
            padding: 0;
        }
        th.column {
            padding: 0
        }
        .pleft {
            text-align: right;
        }
        a[x-apple-data-detectors] {
            color: inherit !important;
            text-decoration: inherit !important;
        }
        #MessageViewBody a {
            color: inherit;
            text-decoration: none;
        }
        p {
            line-height: inherit
        }
        @media (max-width:720px) {
            .icons-inner {
                text-align: center;
            }
            .icons-inner td {
                margin: 0 auto;
            }
            .fullMobileWidth,
            .row-content {
                width: 100% !important;
            }
            .image_block img.big {
                width: auto !important;
            }
            .stack .column {
                width: 100%;
                display: block;
            }
            .pleft {
                text-align: left;
            }
            .reverse {
                display: table;
                width: 100%;
            }
            .reverse th.first {
                display: table-footer-group !important;
            }
            .reverse th.last {
                display: table-header-group !important;
            }
            .row-11 th.column.first>table,
            .row-11 th.column.last>table {
                padding-left: 25px;
                padding-right: 25px;
            }
            .hiddensmall {
                display: none;
            }
        }
    </style>
</head>
<body style="background-color: #DDDDDD; margin: 0; padding: 0; text-align: center;">
</body>
</html>
