<p>Dear <?= $firstName ?>,</p>
<p>
    You are currently registered as a Graduate (<i>Afgestudeerde</i>) at GEWIS until <b><?= $currentExpiration->format('F jS, Y') ?></b>. 
    We care about your privacy, so we'd like to confirm that you want to renew this graduate status.
</p>
<p>
    Please click <a href="<?= $url ?>" style="color: #C40000; text-decoration: none;" target="_blank" rel="noopener nofollow">here</a> to review your personal details and renew your status as graduate of GEWIS until <b><?= $newExpiration->format('F jS, Y') ?></b>.
    If you do not click this link, your status will automatically expire and we will delete your data in the way described in our <a href="https://gewis.nl/association/regulations/privacy-statement" style="color: #C40000; text-decoration: none;" target="_blank" rel="noopener nofollow">privacy statement</a>.
</p>
<? if ($isInstalled): ?>
<p>
    <span style="font-weight: bold;">Please note:</span> you are currently an (in)active member of one or more committees/fraternities.
    If you do not renew your status, those memberships will end on <?= $currentExpiration->format('F jS, Y') ?>. 
</p>
<? endif; ?>
<p>
    If you prefer this, you can also renew your graduate status by replying to this email.
    Please keep the subject intact so we can process it more efficiently.
</p>
<p>
    On behalf of the the board,
    <br><br>Sven Mokveld
    <br><i>Secretary of GEWIS 2023-2024</i>
</p>
