<p>Dear <?= $firstName ?>,</p>
<p>
    You have requested renewal of your status as a Graduate (<i>Afgestudeerde</i>) of GEWIS.
    We are happy to inform you that your status has been renewed until <b><?= $newExpiration->format('F jS, Y') ?></b>.
</p>
<p>
    Within 24 hours this change will be visible on <a href="https://gewis.nl/member/self" style="color: #C40000; text-decoration: none;" target="_blank" rel="noopener nofollow">your memberpage</a>.<br/>
<?php if ($oldExpiration <= new DateTime()): ?>
    If your account is currently deactivated because your membership had expired, it will be activated automatically within that same timeframe.<br/>
<?php endif; ?>
    Note: if you updated your email address, you have to sign in to the GEWIS website using your new email address.<br/>
    Feel free to let us know if you have any questions.
</p>
<p>
    Kind regards,
    <br>The Secretary of GEWIS
</p>
